# 04 — Baseline LSTM Training (4 variants × 3 seeds)

Trains **4 baseline LSTMs × 3 seeds = 12 runs** by invoking `src/train_LSTM_baseline.py` per variant per seed. Each variant runs Optuna once (seed 42) and reuses those hyperparameters for seeds 43 / 44 via the new `--fixed-hparams` CLI arg, saving ~60 % Colab time vs rerunning Optuna each seed.

| Variant | Features | Seeds trained | Artifact names |
|---|---|---|---|
| **O** | stationary (5) | 42, 43, 44 | `lstm_baseline_O_seed{N}.pt` |
| **A** | stationary + sentiment (7) | 42, 43, 44 | `lstm_baseline_seed{N}.pt` |
| **H** | A + `p_volatile` (8) | 42, 43, 44 | `lstm_baseline_H_seed{N}.pt` |
| **B** | A + VIX family (10) | 42, 43, 44 | `lstm_baseline_B_seed{N}.pt` |

## Why 3 seeds

Per `supplementary/discussion.md`, single-seed ensemble MSE swung +53 % between reruns with identical config (Optuna TPE non-determinism + CPU PyTorch float noise). k=3 gives a coarse-but-honest mean±std across seeds, disclosing the training variance.

Aggregation: **simple mean** of per-seed predictions in nb 06 / nb 07. Paper claims quote `mean ± std` across the 3 seeds.

## Why Optuna-once-per-variant

Optuna is expensive (~60 % of training wall time). Hyperparameters are a property of the *data + architecture + objective*, not the seed; reusing seed-42's best_params for seeds 43 / 44 doesn't bias the variance estimate because it leaves the two known sources of seed-level variance (Optuna trial order + weight init + float-noise in retrain) both active across seeds. If Optuna's TPE state itself were a material variance source, we'd need to rerun it — we're betting it isn't, which matches the standard "architecture fixed, retrain with new seed" convention in deep-learning research.

## Prerequisites (from upstream notebooks)

- `data/processed/train.parquet` etc. with the variant H feature `p_volatile` injected (nb 03 § 10c).
- Full training window: ~3,690 rows for variants O/A/H; ~2,030 rows for variant B (VIX3M history limit).

In [1]:
import json
import subprocess
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path().resolve().parent
SCRIPT = REPO_ROOT / "src" / "train_LSTM_baseline.py"
assert SCRIPT.exists(), f"Missing: {SCRIPT}"
sys.path.insert(0, str(REPO_ROOT))

import config

print("Repo root:", REPO_ROOT)
print("Script   :", SCRIPT)

Repo root: /content/repo
Script   : /content/repo/src/train_LSTM_baseline.py

## Prerequisite check

Verifies train.parquet contains every feature column required by any variant (including `p_volatile` for variant H). Raises a clear error if nb 03's cell 10c hasn't run.

In [2]:
train_df = pd.read_parquet(config.DATA_PROCESSED / "train.parquet")

required_cols = (
    set(config.LSTM_VARIANT_O_FEATURES)
    | set(config.LSTM_VARIANT_A_FEATURES)
    | set(config.LSTM_VARIANT_H_FEATURES)
    | set(config.LSTM_VARIANT_B_FEATURES)
    | {config.LSTM_TARGET}
)
missing = sorted(required_cols - set(train_df.columns))
if missing:
    raise RuntimeError(
        f"train.parquet missing columns: {missing}. "
        f"Run nb 01 (features) and nb 03 (§10c p_volatile injection) first."
    )

def _trainable_rows(df, feats):
    return int(df[list(feats) + [config.LSTM_TARGET]].dropna().shape[0])

summary = pd.DataFrame({
    "variant":    ["O", "A", "H", "B"],
    "n_features": [len(config.LSTM_VARIANT_O_FEATURES),
                   len(config.LSTM_VARIANT_A_FEATURES),
                   len(config.LSTM_VARIANT_H_FEATURES),
                   len(config.LSTM_VARIANT_B_FEATURES)],
    "trainable_rows": [_trainable_rows(train_df, config.LSTM_VARIANT_O_FEATURES),
                       _trainable_rows(train_df, config.LSTM_VARIANT_A_FEATURES),
                       _trainable_rows(train_df, config.LSTM_VARIANT_H_FEATURES),
                       _trainable_rows(train_df, config.LSTM_VARIANT_B_FEATURES)],
})
print("Per-variant trainable rows (after dropping NaN):")
print(summary.to_string(index=False))

Per-variant trainable rows (after dropping NaN):
variant  n_features  trainable_rows
      O           5            3691
      A           7            3691
      H           8            3690
      B          10            2034

## Configure variants × seeds

Edit `VARIANTS` or `SEEDS` below to skip configs for partial reruns. Default runs all 12.

In [3]:
VARIANTS = [
    {"name": "O", "features": config.LSTM_VARIANT_O_FEATURES, "prefix_base": "lstm_baseline_O"},
    {"name": "A", "features": config.LSTM_VARIANT_A_FEATURES, "prefix_base": "lstm_baseline"},
    {"name": "H", "features": config.LSTM_VARIANT_H_FEATURES, "prefix_base": "lstm_baseline_H"},
    {"name": "B", "features": config.LSTM_VARIANT_B_FEATURES, "prefix_base": "lstm_baseline_B"},
]
SEEDS = [42, 43, 44]

for v in VARIANTS:
    for s in SEEDS:
        print(f"  variant {v['name']}  seed {s}  → {v['prefix_base']}_seed{s}.pt  ({len(v['features'])} feats)")
print(f"\nTotal runs: {len(VARIANTS) * len(SEEDS)}")

  variant O  seed 42  → lstm_baseline_O_seed42.pt  (5 feats)
  variant O  seed 43  → lstm_baseline_O_seed43.pt  (5 feats)
  variant O  seed 44  → lstm_baseline_O_seed44.pt  (5 feats)
  variant A  seed 42  → lstm_baseline_seed42.pt  (7 feats)
  variant A  seed 43  → lstm_baseline_seed43.pt  (7 feats)
  variant A  seed 44  → lstm_baseline_seed44.pt  (7 feats)
  variant H  seed 42  → lstm_baseline_H_seed42.pt  (8 feats)
  variant H  seed 43  → lstm_baseline_H_seed43.pt  (8 feats)
  variant H  seed 44  → lstm_baseline_H_seed44.pt  (8 feats)
  variant B  seed 42  → lstm_baseline_B_seed42.pt  (10 feats)
  variant B  seed 43  → lstm_baseline_B_seed43.pt  (10 feats)
  variant B  seed 44  → lstm_baseline_B_seed44.pt  (10 feats)

Total runs: 12

## Training sweep

Per variant: seed 42 does full Optuna and writes an hparams JSON; seeds 43 / 44 load that JSON via `--fixed-hparams` and skip Optuna.

Runs are streamed live. If one variant's seed 42 fails, the whole variant is skipped (seeds 43/44 need its JSON). Other variants continue.

Expected wall time per *variant* (all 3 seeds): ~15 min Optuna + 2 × ~5 min retrain ≈ 25 min on Colab GPU. Total for 4 variants: ~90-120 min.

In [4]:
variant_outputs = {}

MODELS_DIR = config.MODELS_DIR
MODELS_DIR.mkdir(parents=True, exist_ok=True)


def _run_one_seed(script_path, args_list, label):
    """Run one training invocation, streaming output live. Returns captured stdout."""
    cmd = [sys.executable, "-u", str(script_path), *args_list]
    print("=" * 80)
    print(f"[{label}]")
    print("Command:", " ".join(cmd))
    print("-" * 80)
    lines = []
    proc = subprocess.Popen(
        cmd, cwd=str(REPO_ROOT),
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, bufsize=1,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        print(line, end="")
        lines.append(line)
    rc = proc.wait()
    return rc, "".join(lines)


for v in VARIANTS:
    vname = v["name"]
    hparams_json_path = MODELS_DIR / f"hparams_{v['prefix_base']}.json"
    variant_outputs[vname] = {"seeds": {}}

    for seed_idx, seed in enumerate(SEEDS):
        prefix = f"{v['prefix_base']}_seed{seed}"
        label = f"variant {vname}  seed {seed}"

        args_list = [
            "--features", *v["features"],
            "--output-prefix", prefix,
            "--seed", str(seed),
        ]
        # Seeds 43, 44: use seed 42's JSON to skip Optuna
        if seed_idx > 0:
            if not hparams_json_path.exists():
                print(f"  [{label}]  SKIPPED — seed 42 didn't produce {hparams_json_path}")
                variant_outputs[vname]["seeds"][seed] = {"status": "skipped"}
                continue
            args_list += ["--fixed-hparams", str(hparams_json_path)]

        try:
            rc, text = _run_one_seed(SCRIPT, args_list, label)
        except Exception as exc:
            print(f"[{label}]  EXCEPTION: {exc}")
            variant_outputs[vname]["seeds"][seed] = {"status": "exception", "error": str(exc)}
            continue

        if rc != 0:
            print(f"[{label}]  FAILED (rc={rc})")
            variant_outputs[vname]["seeds"][seed] = {"status": "failed", "return_code": rc, "output": text}
            # If seed 42 failed, skip subsequent seeds for this variant.
            if seed_idx == 0:
                print(f"  Variant {vname}: seed 42 failed — skipping seeds {SEEDS[1:]}")
                break
            continue

        variant_outputs[vname]["seeds"][seed] = {"status": "ok", "output": text}

        # After seed 42 succeeds, extract its JSON and persist for seeds 43/44.
        if seed_idx == 0:
            marker = "=== Baseline LSTM results ==="
            idx = text.find(marker)
            if idx != -1:
                try:
                    blob = text[idx + len(marker):].strip()
                    results = json.loads(blob)
                    hparams_json_path.write_text(json.dumps(results, indent=2))
                    print(f"  [seed 42]  hparams JSON saved → {hparams_json_path.name}")
                except json.JSONDecodeError as exc:
                    print(f"  [seed 42]  JSON parse failed: {exc}; seeds 43/44 will skip.")

================================================================================
[variant O  seed 42]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d --output-prefix lstm_baseline_O_seed42 --seed 42
--------------------------------------------------------------------------------

22:19:23 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d']
22:19:23 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:19:23 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:19:23 | INFO    | train_LSTM_baseline | n_features=5 | rows — train=3691 val=1089 test=1481
22:19:23 | INFO    | train_LSTM_baseline | Starting Optuna study with 20 trials…

22:19:28 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.976401 | val_mse_raw=0.00004664 | best=0.00004664

22:19:29 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.151301 | val_mse_raw=0.00004741 | best=0.00004664

22:19:29 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.126267 | val_mse_raw=0.00004552 | best=0.00004552

22:19:29 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.111484 | val_mse_raw=0.00004247 | best=0.00004247

22:19:29 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.106226 | val_mse_raw=0.00004270 | best=0.00004247

22:19:30 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.106861 | val_mse_raw=0.00004316 | best=0.00004247

22:19:30 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.102764 | val_mse_raw=0.00004259 | best=0.00004247

22:19:30 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.100109 | val_mse_raw=0.00004219 | best=0.00004219

22:19:30 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.100668 | val_mse_raw=0.00004207 | best=0.00004207

22:19:31 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.099410 | val_mse_raw=0.00004268 | best=0.00004207

22:19:31 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098197 | val_mse_raw=0.00004305 | best=0.00004207

22:19:31 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.096430 | val_mse_raw=0.00004286 | best=0.00004207

22:19:32 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.098792 | val_mse_raw=0.00004220 | best=0.00004207

22:19:32 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.095729 | val_mse_raw=0.00004121 | best=0.00004121

22:19:32 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.095063 | val_mse_raw=0.00004235 | best=0.00004121

22:19:32 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.095975 | val_mse_raw=0.00004032 | best=0.00004032

22:19:33 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.094106 | val_mse_raw=0.00004244 | best=0.00004032

22:19:33 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.095194 | val_mse_raw=0.00004282 | best=0.00004032

22:19:33 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.099647 | val_mse_raw=0.00003995 | best=0.00003995

22:19:34 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.093760 | val_mse_raw=0.00003928 | best=0.00003928

22:19:34 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.093176 | val_mse_raw=0.00004171 | best=0.00003928

22:19:34 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.096617 | val_mse_raw=0.00004091 | best=0.00003928

22:19:34 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.098303 | val_mse_raw=0.00004142 | best=0.00003928

22:19:35 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.098567 | val_mse_raw=0.00004404 | best=0.00003928

22:19:35 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.096045 | val_mse_raw=0.00004105 | best=0.00003928

22:19:35 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.091525 | val_mse_raw=0.00004239 | best=0.00003928

22:19:36 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.091440 | val_mse_raw=0.00004356 | best=0.00003928

22:19:36 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.090529 | val_mse_raw=0.00004401 | best=0.00003928

22:19:36 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.092597 | val_mse_raw=0.00004281 | best=0.00003928

22:19:37 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.089740 | val_mse_raw=0.00004343 | best=0.00003928
22:19:37 | INFO    | train_LSTM_baseline | Early stopping at epoch 30

22:19:37 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=16.267324 | val_mse_raw=0.00364456 | best=0.00364456

22:19:38 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=1.329353 | val_mse_raw=0.00006698 | best=0.00006698

22:19:38 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.254275 | val_mse_raw=0.00006571 | best=0.00006571

22:19:39 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.247341 | val_mse_raw=0.00006587 | best=0.00006571

22:19:39 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.246213 | val_mse_raw=0.00006564 | best=0.00006564

22:19:40 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.245202 | val_mse_raw=0.00006539 | best=0.00006539

22:19:40 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.243839 | val_mse_raw=0.00006507 | best=0.00006507

22:19:41 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.241713 | val_mse_raw=0.00006434 | best=0.00006434

22:19:41 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.238558 | val_mse_raw=0.00006307 | best=0.00006307

22:19:42 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.230050 | val_mse_raw=0.00006010 | best=0.00006010

22:19:42 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.204179 | val_mse_raw=0.00005305 | best=0.00005305

22:19:43 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.136052 | val_mse_raw=0.00004719 | best=0.00004719

22:19:43 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.109660 | val_mse_raw=0.00004373 | best=0.00004373

22:19:44 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.106498 | val_mse_raw=0.00004366 | best=0.00004366

22:19:45 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.103650 | val_mse_raw=0.00004344 | best=0.00004344

22:19:45 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.102512 | val_mse_raw=0.00004348 | best=0.00004344

22:19:46 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.102253 | val_mse_raw=0.00004537 | best=0.00004344

22:19:46 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.101811 | val_mse_raw=0.00004464 | best=0.00004344

22:19:47 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.102291 | val_mse_raw=0.00004333 | best=0.00004333

22:19:47 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.098079 | val_mse_raw=0.00004414 | best=0.00004333

22:19:48 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.097718 | val_mse_raw=0.00004443 | best=0.00004333

22:19:48 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.095894 | val_mse_raw=0.00004447 | best=0.00004333

22:19:49 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.097363 | val_mse_raw=0.00004453 | best=0.00004333

22:19:50 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.095304 | val_mse_raw=0.00004449 | best=0.00004333

22:19:50 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.094960 | val_mse_raw=0.00004503 | best=0.00004333

22:19:51 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.094996 | val_mse_raw=0.00004498 | best=0.00004333

22:19:51 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.094454 | val_mse_raw=0.00004481 | best=0.00004333

22:19:52 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.094081 | val_mse_raw=0.00004457 | best=0.00004333

22:19:52 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.093361 | val_mse_raw=0.00004494 | best=0.00004333
22:19:52 | INFO    | train_LSTM_baseline | Early stopping at epoch 29

22:19:55 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=0.827000 | val_mse_raw=0.00006916 | best=0.00006916

22:19:57 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.228888 | val_mse_raw=0.00006893 | best=0.00006893

22:20:00 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.247510 | val_mse_raw=0.00006437 | best=0.00006437

22:20:03 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.252237 | val_mse_raw=0.00006548 | best=0.00006437

22:20:05 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.162376 | val_mse_raw=0.00005467 | best=0.00005467

22:20:08 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.130363 | val_mse_raw=0.00005637 | best=0.00005467

22:20:10 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.122520 | val_mse_raw=0.00004643 | best=0.00004643

22:20:13 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.109909 | val_mse_raw=0.00004765 | best=0.00004643

22:20:16 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.112239 | val_mse_raw=0.00004531 | best=0.00004531

22:20:18 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.111168 | val_mse_raw=0.00004334 | best=0.00004334

22:20:21 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.104729 | val_mse_raw=0.00004514 | best=0.00004334

22:20:23 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.104132 | val_mse_raw=0.00004183 | best=0.00004183

22:20:26 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.099430 | val_mse_raw=0.00004228 | best=0.00004183

22:20:29 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.097888 | val_mse_raw=0.00004272 | best=0.00004183

22:20:31 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.092427 | val_mse_raw=0.00004361 | best=0.00004183

22:20:34 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.090055 | val_mse_raw=0.00004080 | best=0.00004080

22:20:37 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.091330 | val_mse_raw=0.00004581 | best=0.00004080

22:20:39 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.085448 | val_mse_raw=0.00004610 | best=0.00004080

22:20:42 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.081312 | val_mse_raw=0.00004571 | best=0.00004080

22:20:45 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.076530 | val_mse_raw=0.00004671 | best=0.00004080

22:20:47 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.079511 | val_mse_raw=0.00004730 | best=0.00004080

22:20:50 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.069174 | val_mse_raw=0.00005219 | best=0.00004080

22:20:53 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.095876 | val_mse_raw=0.00005271 | best=0.00004080

22:20:55 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.070987 | val_mse_raw=0.00006809 | best=0.00004080

22:20:58 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.057376 | val_mse_raw=0.00007403 | best=0.00004080

22:21:00 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.058152 | val_mse_raw=0.00005823 | best=0.00004080
22:21:00 | INFO    | train_LSTM_baseline | Early stopping at epoch 26

22:21:02 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=9.434460 | val_mse_raw=0.00006388 | best=0.00006388

22:21:03 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.227727 | val_mse_raw=0.00005745 | best=0.00005745

22:21:04 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.167857 | val_mse_raw=0.00004939 | best=0.00004939

22:21:05 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.115774 | val_mse_raw=0.00004747 | best=0.00004747

22:21:06 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.108891 | val_mse_raw=0.00004566 | best=0.00004566

22:21:07 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.106704 | val_mse_raw=0.00004560 | best=0.00004560

22:21:08 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.101617 | val_mse_raw=0.00004566 | best=0.00004560

22:21:09 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.101375 | val_mse_raw=0.00004503 | best=0.00004503

22:21:10 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.098588 | val_mse_raw=0.00004328 | best=0.00004328

22:21:11 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.097867 | val_mse_raw=0.00004251 | best=0.00004251

22:21:13 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098458 | val_mse_raw=0.00004245 | best=0.00004245

22:21:14 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.097340 | val_mse_raw=0.00004253 | best=0.00004245

22:21:15 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.097758 | val_mse_raw=0.00004182 | best=0.00004182

22:21:16 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.096543 | val_mse_raw=0.00004210 | best=0.00004182

22:21:17 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.095170 | val_mse_raw=0.00004241 | best=0.00004182

22:21:18 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.095549 | val_mse_raw=0.00004281 | best=0.00004182

22:21:19 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.095101 | val_mse_raw=0.00004201 | best=0.00004182

22:21:20 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.095517 | val_mse_raw=0.00004307 | best=0.00004182

22:21:21 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.096561 | val_mse_raw=0.00004311 | best=0.00004182

22:21:22 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.095184 | val_mse_raw=0.00004252 | best=0.00004182

22:21:24 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.094106 | val_mse_raw=0.00004314 | best=0.00004182

22:21:25 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.095102 | val_mse_raw=0.00004229 | best=0.00004182

22:21:26 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.093195 | val_mse_raw=0.00004170 | best=0.00004170

22:21:27 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.095234 | val_mse_raw=0.00004211 | best=0.00004170

22:21:28 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.094689 | val_mse_raw=0.00004355 | best=0.00004170

22:21:29 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.094196 | val_mse_raw=0.00004351 | best=0.00004170

22:21:30 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.093413 | val_mse_raw=0.00004281 | best=0.00004170

22:21:31 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.093335 | val_mse_raw=0.00004290 | best=0.00004170

22:21:32 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.093212 | val_mse_raw=0.00004230 | best=0.00004170

22:21:33 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.092268 | val_mse_raw=0.00004206 | best=0.00004170

22:21:34 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.092236 | val_mse_raw=0.00004230 | best=0.00004170

22:21:35 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.092227 | val_mse_raw=0.00004247 | best=0.00004170

22:21:37 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.090773 | val_mse_raw=0.00004250 | best=0.00004170
22:21:37 | INFO    | train_LSTM_baseline | Early stopping at epoch 33
22:21:37 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=22.983752 | val_mse_raw=0.89574450 | best=0.89574450

22:21:37 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=21.471891 | val_mse_raw=0.55688602 | best=0.55688602
22:21:37 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=17.312249 | val_mse_raw=0.07188694 | best=0.07188694

22:21:37 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=7.143149 | val_mse_raw=0.00234316 | best=0.00234316
22:21:37 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=1.933247 | val_mse_raw=0.00020492 | best=0.00020492

22:21:38 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.527810 | val_mse_raw=0.00006935 | best=0.00006935
22:21:38 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.242259 | val_mse_raw=0.00005655 | best=0.00005655

22:21:38 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.192819 | val_mse_raw=0.00005936 | best=0.00005655
22:21:38 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.179635 | val_mse_raw=0.00006909 | best=0.00005655

22:21:38 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.170340 | val_mse_raw=0.00008128 | best=0.00005655
22:21:38 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.162741 | val_mse_raw=0.00009818 | best=0.00005655

22:21:38 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.155684 | val_mse_raw=0.00010882 | best=0.00005655
22:21:39 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.149635 | val_mse_raw=0.00011389 | best=0.00005655

22:21:39 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.143836 | val_mse_raw=0.00011019 | best=0.00005655
22:21:39 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.138576 | val_mse_raw=0.00010451 | best=0.00005655

22:21:39 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.133468 | val_mse_raw=0.00009256 | best=0.00005655
22:21:39 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.128802 | val_mse_raw=0.00008329 | best=0.00005655
22:21:39 | INFO    | train_LSTM_baseline | Early stopping at epoch 17

22:21:40 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=14.171747 | val_mse_raw=0.00006011 | best=0.00006011

22:21:42 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.161597 | val_mse_raw=0.00005572 | best=0.00005572

22:21:43 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.118870 | val_mse_raw=0.00005191 | best=0.00005191

22:21:44 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.110712 | val_mse_raw=0.00005034 | best=0.00005034

22:21:46 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.108061 | val_mse_raw=0.00004860 | best=0.00004860

22:21:47 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.106048 | val_mse_raw=0.00004840 | best=0.00004840

22:21:49 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.103286 | val_mse_raw=0.00004799 | best=0.00004799

22:21:50 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.101916 | val_mse_raw=0.00004693 | best=0.00004693

22:21:51 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.099908 | val_mse_raw=0.00004576 | best=0.00004576

22:21:53 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.099902 | val_mse_raw=0.00004508 | best=0.00004508

22:21:54 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098704 | val_mse_raw=0.00004494 | best=0.00004494

22:21:55 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.097616 | val_mse_raw=0.00004371 | best=0.00004371

22:21:57 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.097230 | val_mse_raw=0.00004345 | best=0.00004345

22:21:58 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.096417 | val_mse_raw=0.00004309 | best=0.00004309

22:22:00 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.096154 | val_mse_raw=0.00004291 | best=0.00004291

22:22:01 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.096505 | val_mse_raw=0.00004314 | best=0.00004291

22:22:02 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.095848 | val_mse_raw=0.00004233 | best=0.00004233

22:22:04 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.095839 | val_mse_raw=0.00004385 | best=0.00004233

22:22:05 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.096453 | val_mse_raw=0.00004398 | best=0.00004233

22:22:07 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.096301 | val_mse_raw=0.00004262 | best=0.00004233

22:22:08 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.095402 | val_mse_raw=0.00004303 | best=0.00004233

22:22:09 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.095722 | val_mse_raw=0.00004279 | best=0.00004233

22:22:11 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.094623 | val_mse_raw=0.00004224 | best=0.00004224

22:22:12 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.095197 | val_mse_raw=0.00004203 | best=0.00004203

22:22:14 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.095436 | val_mse_raw=0.00004288 | best=0.00004203

22:22:15 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.094376 | val_mse_raw=0.00004318 | best=0.00004203

22:22:17 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.095107 | val_mse_raw=0.00004267 | best=0.00004203

22:22:18 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.094677 | val_mse_raw=0.00004307 | best=0.00004203

22:22:19 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.094371 | val_mse_raw=0.00004280 | best=0.00004203

22:22:21 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.093674 | val_mse_raw=0.00004252 | best=0.00004203

22:22:22 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.093782 | val_mse_raw=0.00004249 | best=0.00004203

22:22:23 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.093429 | val_mse_raw=0.00004219 | best=0.00004203

22:22:25 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.094076 | val_mse_raw=0.00004343 | best=0.00004203

22:22:26 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.093745 | val_mse_raw=0.00004202 | best=0.00004202

22:22:28 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.094627 | val_mse_raw=0.00004206 | best=0.00004202

22:22:29 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.093473 | val_mse_raw=0.00004387 | best=0.00004202

22:22:30 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.093876 | val_mse_raw=0.00004237 | best=0.00004202

22:22:32 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.092733 | val_mse_raw=0.00004361 | best=0.00004202

22:22:33 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.092591 | val_mse_raw=0.00004392 | best=0.00004202

22:22:35 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.092964 | val_mse_raw=0.00004269 | best=0.00004202

22:22:35 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.697244 | val_mse_raw=0.24464278 | best=0.24464278

22:22:35 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=3.993581 | val_mse_raw=0.00006918 | best=0.00006918

22:22:36 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.267262 | val_mse_raw=0.00005989 | best=0.00005989

22:22:36 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.214278 | val_mse_raw=0.00005615 | best=0.00005615

22:22:37 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.197916 | val_mse_raw=0.00005229 | best=0.00005229

22:22:37 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.183083 | val_mse_raw=0.00004835 | best=0.00004835

22:22:37 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.165559 | val_mse_raw=0.00004425 | best=0.00004425

22:22:38 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.145330 | val_mse_raw=0.00004144 | best=0.00004144

22:22:38 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.121350 | val_mse_raw=0.00004229 | best=0.00004144

22:22:39 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.109728 | val_mse_raw=0.00004503 | best=0.00004144

22:22:39 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.105179 | val_mse_raw=0.00004544 | best=0.00004144

22:22:39 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.104196 | val_mse_raw=0.00004563 | best=0.00004144

22:22:40 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.102801 | val_mse_raw=0.00004497 | best=0.00004144

22:22:40 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.102686 | val_mse_raw=0.00004489 | best=0.00004144

22:22:41 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.102308 | val_mse_raw=0.00004433 | best=0.00004144

22:22:41 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.101870 | val_mse_raw=0.00004390 | best=0.00004144

22:22:41 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.100185 | val_mse_raw=0.00004385 | best=0.00004144

22:22:42 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.098842 | val_mse_raw=0.00004348 | best=0.00004144
22:22:42 | INFO    | train_LSTM_baseline | Early stopping at epoch 18

22:22:42 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=22.734191 | val_mse_raw=0.93612534 | best=0.93612534

22:22:43 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=22.230345 | val_mse_raw=0.82119191 | best=0.82119191

22:22:43 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=21.635170 | val_mse_raw=0.68618309 | best=0.68618309

22:22:43 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=20.761634 | val_mse_raw=0.50004077 | best=0.50004077

22:22:44 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=18.717304 | val_mse_raw=0.16526490 | best=0.16526490

22:22:44 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=9.930847 | val_mse_raw=0.01130399 | best=0.01130399

22:22:44 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=3.074964 | val_mse_raw=0.00080061 | best=0.00080061

22:22:45 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=1.336597 | val_mse_raw=0.00020237 | best=0.00020237

22:22:45 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.634184 | val_mse_raw=0.00009147 | best=0.00009147

22:22:45 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.357592 | val_mse_raw=0.00006445 | best=0.00006445

22:22:46 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.255338 | val_mse_raw=0.00005666 | best=0.00005666

22:22:46 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.218938 | val_mse_raw=0.00005390 | best=0.00005390

22:22:46 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.204523 | val_mse_raw=0.00005296 | best=0.00005296

22:22:47 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.196257 | val_mse_raw=0.00005346 | best=0.00005296

22:22:47 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.190366 | val_mse_raw=0.00005587 | best=0.00005296

22:22:47 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.186018 | val_mse_raw=0.00005849 | best=0.00005296

22:22:48 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.182568 | val_mse_raw=0.00006178 | best=0.00005296

22:22:48 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.178916 | val_mse_raw=0.00006524 | best=0.00005296

22:22:48 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.175222 | val_mse_raw=0.00006849 | best=0.00005296

22:22:49 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.171204 | val_mse_raw=0.00007120 | best=0.00005296

22:22:49 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.166930 | val_mse_raw=0.00007454 | best=0.00005296

22:22:49 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.162436 | val_mse_raw=0.00007913 | best=0.00005296

22:22:50 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.157782 | val_mse_raw=0.00008282 | best=0.00005296
22:22:50 | INFO    | train_LSTM_baseline | Early stopping at epoch 23

22:22:50 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=22.298901 | val_mse_raw=0.57124305 | best=0.57124305

22:22:50 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=11.243310 | val_mse_raw=0.00186292 | best=0.00186292

22:22:51 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=1.276908 | val_mse_raw=0.00009075 | best=0.00009075

22:22:51 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.256717 | val_mse_raw=0.00006663 | best=0.00006663

22:22:51 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.184629 | val_mse_raw=0.00008740 | best=0.00006663

22:22:52 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.162472 | val_mse_raw=0.00011266 | best=0.00006663

22:22:52 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.140150 | val_mse_raw=0.00010112 | best=0.00006663

22:22:52 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.122792 | val_mse_raw=0.00008155 | best=0.00006663

22:22:52 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.114417 | val_mse_raw=0.00006827 | best=0.00006663

22:22:53 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.110997 | val_mse_raw=0.00006082 | best=0.00006082

22:22:53 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.108976 | val_mse_raw=0.00005567 | best=0.00005567

22:22:53 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.107705 | val_mse_raw=0.00005290 | best=0.00005290

22:22:54 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.106076 | val_mse_raw=0.00005097 | best=0.00005097

22:22:54 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.104975 | val_mse_raw=0.00004904 | best=0.00004904

22:22:54 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.104255 | val_mse_raw=0.00004759 | best=0.00004759

22:22:54 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.103251 | val_mse_raw=0.00004603 | best=0.00004603

22:22:55 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.102678 | val_mse_raw=0.00004542 | best=0.00004542

22:22:55 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.101774 | val_mse_raw=0.00004451 | best=0.00004451

22:22:55 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.101261 | val_mse_raw=0.00004379 | best=0.00004379

22:22:56 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.100552 | val_mse_raw=0.00004320 | best=0.00004320

22:22:56 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.100122 | val_mse_raw=0.00004295 | best=0.00004295

22:22:56 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.099480 | val_mse_raw=0.00004263 | best=0.00004263

22:22:57 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.099168 | val_mse_raw=0.00004231 | best=0.00004231

22:22:57 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.098864 | val_mse_raw=0.00004243 | best=0.00004231

22:22:57 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.098292 | val_mse_raw=0.00004212 | best=0.00004212

22:22:57 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.097932 | val_mse_raw=0.00004205 | best=0.00004205

22:22:58 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.097913 | val_mse_raw=0.00004195 | best=0.00004195

22:22:58 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.097517 | val_mse_raw=0.00004214 | best=0.00004195

22:22:58 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.096858 | val_mse_raw=0.00004220 | best=0.00004195

22:22:59 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.096677 | val_mse_raw=0.00004207 | best=0.00004195

22:22:59 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.096217 | val_mse_raw=0.00004206 | best=0.00004195

22:22:59 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.096018 | val_mse_raw=0.00004217 | best=0.00004195

22:22:59 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.095346 | val_mse_raw=0.00004244 | best=0.00004195

22:23:00 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.095248 | val_mse_raw=0.00004217 | best=0.00004195

22:23:00 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.095150 | val_mse_raw=0.00004243 | best=0.00004195

22:23:00 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.094760 | val_mse_raw=0.00004216 | best=0.00004195

22:23:01 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.094808 | val_mse_raw=0.00004247 | best=0.00004195
22:23:01 | INFO    | train_LSTM_baseline | Early stopping at epoch 37

22:23:02 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.673109 | val_mse_raw=0.46893787 | best=0.46893787

22:23:03 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=14.102845 | val_mse_raw=0.00272620 | best=0.00272620

22:23:04 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=1.104154 | val_mse_raw=0.00006328 | best=0.00006328

22:23:05 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.239129 | val_mse_raw=0.00006121 | best=0.00006121

22:23:06 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.224981 | val_mse_raw=0.00005934 | best=0.00005934

22:23:06 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.215709 | val_mse_raw=0.00005737 | best=0.00005737

22:23:07 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.204558 | val_mse_raw=0.00005561 | best=0.00005561

22:23:08 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.184188 | val_mse_raw=0.00005461 | best=0.00005461

22:23:09 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.159401 | val_mse_raw=0.00005372 | best=0.00005372

22:23:10 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.136456 | val_mse_raw=0.00005054 | best=0.00005054

22:23:11 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.119064 | val_mse_raw=0.00004918 | best=0.00004918

22:23:12 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.109845 | val_mse_raw=0.00004864 | best=0.00004864

22:23:13 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.105610 | val_mse_raw=0.00004839 | best=0.00004839

22:23:14 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.103496 | val_mse_raw=0.00004791 | best=0.00004791

22:23:15 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.101439 | val_mse_raw=0.00004776 | best=0.00004776

22:23:16 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.100472 | val_mse_raw=0.00004759 | best=0.00004759

22:23:16 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.099665 | val_mse_raw=0.00004688 | best=0.00004688

22:23:17 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.098109 | val_mse_raw=0.00004689 | best=0.00004688

22:23:18 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.097832 | val_mse_raw=0.00004661 | best=0.00004661

22:23:19 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.097440 | val_mse_raw=0.00004639 | best=0.00004639

22:23:20 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.098077 | val_mse_raw=0.00004601 | best=0.00004601

22:23:21 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.096821 | val_mse_raw=0.00004597 | best=0.00004597

22:23:22 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.095816 | val_mse_raw=0.00004579 | best=0.00004579

22:23:23 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.096193 | val_mse_raw=0.00004556 | best=0.00004556

22:23:24 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.095201 | val_mse_raw=0.00004585 | best=0.00004556

22:23:24 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.094947 | val_mse_raw=0.00004536 | best=0.00004536

22:23:25 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.094450 | val_mse_raw=0.00004516 | best=0.00004516

22:23:26 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.094796 | val_mse_raw=0.00004510 | best=0.00004510

22:23:27 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.094113 | val_mse_raw=0.00004557 | best=0.00004510

22:23:28 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.093788 | val_mse_raw=0.00004535 | best=0.00004510

22:23:29 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.094602 | val_mse_raw=0.00004533 | best=0.00004510

22:23:30 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.093309 | val_mse_raw=0.00004518 | best=0.00004510

22:23:31 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.092917 | val_mse_raw=0.00004512 | best=0.00004510

22:23:32 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.092689 | val_mse_raw=0.00004527 | best=0.00004510

22:23:33 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.092527 | val_mse_raw=0.00004537 | best=0.00004510

22:23:34 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.092397 | val_mse_raw=0.00004512 | best=0.00004510

22:23:34 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.092311 | val_mse_raw=0.00004516 | best=0.00004510

22:23:35 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.091357 | val_mse_raw=0.00004513 | best=0.00004510
22:23:35 | INFO    | train_LSTM_baseline | Early stopping at epoch 38

22:23:36 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.360589 | val_mse_raw=0.00006534 | best=0.00006534

22:23:37 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.248544 | val_mse_raw=0.00006511 | best=0.00006511

22:23:38 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.247985 | val_mse_raw=0.00006500 | best=0.00006500

22:23:39 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.251046 | val_mse_raw=0.00006600 | best=0.00006500

22:23:40 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.249121 | val_mse_raw=0.00006568 | best=0.00006500

22:23:41 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.251569 | val_mse_raw=0.00006511 | best=0.00006500

22:23:42 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.248963 | val_mse_raw=0.00006661 | best=0.00006500

22:23:42 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.248743 | val_mse_raw=0.00006504 | best=0.00006500

22:23:43 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.241017 | val_mse_raw=0.00006243 | best=0.00006243

22:23:44 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.187554 | val_mse_raw=0.00005355 | best=0.00005355

22:23:45 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.135008 | val_mse_raw=0.00004652 | best=0.00004652

22:23:46 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.114063 | val_mse_raw=0.00004342 | best=0.00004342

22:23:47 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.114285 | val_mse_raw=0.00004383 | best=0.00004342

22:23:48 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.113055 | val_mse_raw=0.00003964 | best=0.00003964

22:23:49 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.109200 | val_mse_raw=0.00004329 | best=0.00003964

22:23:50 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.102331 | val_mse_raw=0.00004250 | best=0.00003964

22:23:50 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.101301 | val_mse_raw=0.00004313 | best=0.00003964

22:23:51 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.097895 | val_mse_raw=0.00004219 | best=0.00003964

22:23:52 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.114864 | val_mse_raw=0.00005253 | best=0.00003964

22:23:53 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.117538 | val_mse_raw=0.00005542 | best=0.00003964

22:23:54 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.119593 | val_mse_raw=0.00004086 | best=0.00003964

22:23:55 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.097915 | val_mse_raw=0.00004175 | best=0.00003964

22:23:56 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.093406 | val_mse_raw=0.00004310 | best=0.00003964

22:23:56 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.086737 | val_mse_raw=0.00004718 | best=0.00003964
22:23:56 | INFO    | train_LSTM_baseline | Early stopping at epoch 24

22:23:57 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.236221 | val_mse_raw=0.00006612 | best=0.00006612

22:23:58 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.248436 | val_mse_raw=0.00006495 | best=0.00006495

22:23:59 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.248312 | val_mse_raw=0.00006489 | best=0.00006489

22:24:00 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.250778 | val_mse_raw=0.00006660 | best=0.00006489

22:24:01 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.250371 | val_mse_raw=0.00006587 | best=0.00006489

22:24:02 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.252215 | val_mse_raw=0.00006491 | best=0.00006489

22:24:03 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.246958 | val_mse_raw=0.00006511 | best=0.00006489

22:24:04 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.197737 | val_mse_raw=0.00004981 | best=0.00004981

22:24:04 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.133449 | val_mse_raw=0.00004525 | best=0.00004525

22:24:05 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.119263 | val_mse_raw=0.00004231 | best=0.00004231

22:24:06 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.112975 | val_mse_raw=0.00004105 | best=0.00004105

22:24:07 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.112666 | val_mse_raw=0.00004101 | best=0.00004101

22:24:08 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.112741 | val_mse_raw=0.00004030 | best=0.00004030

22:24:09 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.104309 | val_mse_raw=0.00003817 | best=0.00003817

22:24:09 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.104111 | val_mse_raw=0.00003921 | best=0.00003817

22:24:10 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.094971 | val_mse_raw=0.00004301 | best=0.00003817

22:24:11 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.088484 | val_mse_raw=0.00004408 | best=0.00003817

22:24:12 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.085844 | val_mse_raw=0.00004439 | best=0.00003817

22:24:13 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.077770 | val_mse_raw=0.00004615 | best=0.00003817

22:24:14 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.075942 | val_mse_raw=0.00004563 | best=0.00003817

22:24:15 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.072542 | val_mse_raw=0.00004999 | best=0.00003817

22:24:16 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.068063 | val_mse_raw=0.00004985 | best=0.00003817

22:24:17 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.064347 | val_mse_raw=0.00005368 | best=0.00003817

22:24:17 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.061929 | val_mse_raw=0.00004843 | best=0.00003817
22:24:17 | INFO    | train_LSTM_baseline | Early stopping at epoch 24

22:24:18 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.411762 | val_mse_raw=0.00006489 | best=0.00006489

22:24:19 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.249845 | val_mse_raw=0.00006534 | best=0.00006489

22:24:20 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.247817 | val_mse_raw=0.00006487 | best=0.00006487

22:24:21 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.247501 | val_mse_raw=0.00006489 | best=0.00006487

22:24:22 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.250404 | val_mse_raw=0.00006526 | best=0.00006487

22:24:22 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.238466 | val_mse_raw=0.00006214 | best=0.00006214

22:24:23 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.167837 | val_mse_raw=0.00005124 | best=0.00005124

22:24:24 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.127163 | val_mse_raw=0.00004604 | best=0.00004604

22:24:25 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.112824 | val_mse_raw=0.00004588 | best=0.00004588

22:24:26 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.109681 | val_mse_raw=0.00004247 | best=0.00004247

22:24:27 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.101638 | val_mse_raw=0.00004211 | best=0.00004211

22:24:28 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.099468 | val_mse_raw=0.00004483 | best=0.00004211

22:24:28 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.097924 | val_mse_raw=0.00004504 | best=0.00004211

22:24:29 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.097381 | val_mse_raw=0.00004844 | best=0.00004211

22:24:30 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.093392 | val_mse_raw=0.00004568 | best=0.00004211

22:24:31 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.090259 | val_mse_raw=0.00005199 | best=0.00004211

22:24:32 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.092528 | val_mse_raw=0.00005251 | best=0.00004211

22:24:33 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.088583 | val_mse_raw=0.00005255 | best=0.00004211

22:24:33 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.086557 | val_mse_raw=0.00005113 | best=0.00004211

22:24:34 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.087725 | val_mse_raw=0.00005407 | best=0.00004211

22:24:35 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.082963 | val_mse_raw=0.00004963 | best=0.00004211
22:24:35 | INFO    | train_LSTM_baseline | Early stopping at epoch 21

22:24:36 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.097174 | val_mse_raw=0.00006562 | best=0.00006562

22:24:37 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.248774 | val_mse_raw=0.00006562 | best=0.00006562

22:24:38 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.247677 | val_mse_raw=0.00006488 | best=0.00006488

22:24:39 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.248009 | val_mse_raw=0.00006488 | best=0.00006488

22:24:39 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.250825 | val_mse_raw=0.00006499 | best=0.00006488

22:24:40 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.248249 | val_mse_raw=0.00006487 | best=0.00006487

22:24:41 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.248750 | val_mse_raw=0.00006507 | best=0.00006487

22:24:42 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.244333 | val_mse_raw=0.00006365 | best=0.00006365

22:24:43 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.199587 | val_mse_raw=0.00005783 | best=0.00005783

22:24:44 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.157054 | val_mse_raw=0.00004814 | best=0.00004814

22:24:44 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.126748 | val_mse_raw=0.00004771 | best=0.00004771

22:24:45 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.119003 | val_mse_raw=0.00004617 | best=0.00004617

22:24:46 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.110468 | val_mse_raw=0.00004297 | best=0.00004297

22:24:47 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.114209 | val_mse_raw=0.00004405 | best=0.00004297

22:24:48 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.104558 | val_mse_raw=0.00004087 | best=0.00004087

22:24:49 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.102563 | val_mse_raw=0.00004168 | best=0.00004087

22:24:50 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.104734 | val_mse_raw=0.00004204 | best=0.00004087

22:24:51 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.096329 | val_mse_raw=0.00004298 | best=0.00004087

22:24:51 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.097153 | val_mse_raw=0.00004057 | best=0.00004057

22:24:52 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.096158 | val_mse_raw=0.00004299 | best=0.00004057

22:24:53 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.091231 | val_mse_raw=0.00004060 | best=0.00004057

22:24:54 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.091218 | val_mse_raw=0.00004768 | best=0.00004057

22:24:55 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.088469 | val_mse_raw=0.00004217 | best=0.00004057

22:24:56 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.088451 | val_mse_raw=0.00004163 | best=0.00004057

22:24:56 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.084499 | val_mse_raw=0.00004830 | best=0.00004057

22:24:57 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.084762 | val_mse_raw=0.00004202 | best=0.00004057

22:24:58 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.084264 | val_mse_raw=0.00004326 | best=0.00004057

22:24:59 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.077777 | val_mse_raw=0.00004694 | best=0.00004057

22:25:00 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.079000 | val_mse_raw=0.00004469 | best=0.00004057
22:25:00 | INFO    | train_LSTM_baseline | Early stopping at epoch 29

22:25:01 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.234294 | val_mse_raw=0.00006609 | best=0.00006609

22:25:02 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.248453 | val_mse_raw=0.00006494 | best=0.00006494

22:25:03 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.248259 | val_mse_raw=0.00006488 | best=0.00006488

22:25:03 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.250812 | val_mse_raw=0.00006660 | best=0.00006488

22:25:04 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.250626 | val_mse_raw=0.00006592 | best=0.00006488

22:25:05 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.252471 | val_mse_raw=0.00006500 | best=0.00006488

22:25:06 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.249491 | val_mse_raw=0.00006628 | best=0.00006488

22:25:07 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.249160 | val_mse_raw=0.00006496 | best=0.00006488

22:25:07 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.249382 | val_mse_raw=0.00006688 | best=0.00006488

22:25:08 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.264325 | val_mse_raw=0.00006612 | best=0.00006488

22:25:09 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.254344 | val_mse_raw=0.00006587 | best=0.00006488

22:25:10 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.248390 | val_mse_raw=0.00006160 | best=0.00006160

22:25:11 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.157066 | val_mse_raw=0.00005053 | best=0.00005053

22:25:11 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.128425 | val_mse_raw=0.00004711 | best=0.00004711

22:25:12 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.161578 | val_mse_raw=0.00004887 | best=0.00004711

22:25:13 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.152121 | val_mse_raw=0.00004899 | best=0.00004711

22:25:14 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.147830 | val_mse_raw=0.00004939 | best=0.00004711

22:25:15 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.137110 | val_mse_raw=0.00004728 | best=0.00004711

22:25:15 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.115972 | val_mse_raw=0.00004188 | best=0.00004188

22:25:16 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.113262 | val_mse_raw=0.00004492 | best=0.00004188

22:25:17 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.114183 | val_mse_raw=0.00004350 | best=0.00004188

22:25:18 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.112604 | val_mse_raw=0.00004695 | best=0.00004188

22:25:19 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.111760 | val_mse_raw=0.00004501 | best=0.00004188

22:25:19 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.103894 | val_mse_raw=0.00004352 | best=0.00004188

22:25:20 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.101397 | val_mse_raw=0.00004379 | best=0.00004188

22:25:21 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.099666 | val_mse_raw=0.00004523 | best=0.00004188

22:25:22 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.106566 | val_mse_raw=0.00004343 | best=0.00004188

22:25:23 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.101017 | val_mse_raw=0.00004447 | best=0.00004188

22:25:23 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.100357 | val_mse_raw=0.00004388 | best=0.00004188
22:25:23 | INFO    | train_LSTM_baseline | Early stopping at epoch 29

22:25:24 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=3.723509 | val_mse_raw=0.00005057 | best=0.00005057

22:25:24 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.164134 | val_mse_raw=0.00004676 | best=0.00004676

22:25:24 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.133055 | val_mse_raw=0.00005145 | best=0.00004676

22:25:25 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.120292 | val_mse_raw=0.00004237 | best=0.00004237

22:25:25 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.111304 | val_mse_raw=0.00004237 | best=0.00004237

22:25:25 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.108904 | val_mse_raw=0.00004255 | best=0.00004237

22:25:25 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.102111 | val_mse_raw=0.00004433 | best=0.00004237

22:25:26 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.099638 | val_mse_raw=0.00004289 | best=0.00004237

22:25:26 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.098528 | val_mse_raw=0.00004416 | best=0.00004237

22:25:26 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.097019 | val_mse_raw=0.00004317 | best=0.00004237

22:25:27 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.096768 | val_mse_raw=0.00004470 | best=0.00004237

22:25:27 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.094740 | val_mse_raw=0.00004431 | best=0.00004237

22:25:27 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.095567 | val_mse_raw=0.00004116 | best=0.00004116

22:25:27 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.094101 | val_mse_raw=0.00003992 | best=0.00003992

22:25:28 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.092980 | val_mse_raw=0.00004260 | best=0.00003992

22:25:28 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.093626 | val_mse_raw=0.00004348 | best=0.00003992

22:25:28 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.092434 | val_mse_raw=0.00004282 | best=0.00003992

22:25:28 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.092284 | val_mse_raw=0.00004194 | best=0.00003992

22:25:29 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.094475 | val_mse_raw=0.00004249 | best=0.00003992

22:25:29 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.091120 | val_mse_raw=0.00004213 | best=0.00003992

22:25:29 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.090635 | val_mse_raw=0.00004211 | best=0.00003992

22:25:29 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.093214 | val_mse_raw=0.00004184 | best=0.00003992

22:25:30 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.095122 | val_mse_raw=0.00004280 | best=0.00003992

22:25:30 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.091812 | val_mse_raw=0.00004528 | best=0.00003992
22:25:30 | INFO    | train_LSTM_baseline | Early stopping at epoch 24

22:25:31 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.419752 | val_mse_raw=0.00006633 | best=0.00006633

22:25:31 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.247518 | val_mse_raw=0.00006498 | best=0.00006498

22:25:32 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.243503 | val_mse_raw=0.00006354 | best=0.00006354

22:25:33 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.206896 | val_mse_raw=0.00005619 | best=0.00005619

22:25:34 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.125088 | val_mse_raw=0.00005040 | best=0.00005040

22:25:35 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.109152 | val_mse_raw=0.00004991 | best=0.00004991

22:25:35 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.105163 | val_mse_raw=0.00004589 | best=0.00004589

22:25:36 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.102946 | val_mse_raw=0.00004483 | best=0.00004483

22:25:37 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.102583 | val_mse_raw=0.00004406 | best=0.00004406

22:25:38 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.103861 | val_mse_raw=0.00004349 | best=0.00004349

22:25:39 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098875 | val_mse_raw=0.00004352 | best=0.00004349

22:25:40 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.097557 | val_mse_raw=0.00004424 | best=0.00004349

22:25:41 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.096754 | val_mse_raw=0.00004493 | best=0.00004349

22:25:41 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.094573 | val_mse_raw=0.00004243 | best=0.00004243

22:25:42 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.093291 | val_mse_raw=0.00004359 | best=0.00004243

22:25:43 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.091529 | val_mse_raw=0.00004539 | best=0.00004243

22:25:44 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.090852 | val_mse_raw=0.00004547 | best=0.00004243

22:25:45 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.091338 | val_mse_raw=0.00004586 | best=0.00004243

22:25:45 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.088460 | val_mse_raw=0.00004727 | best=0.00004243

22:25:46 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.088620 | val_mse_raw=0.00004812 | best=0.00004243

22:25:47 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.085768 | val_mse_raw=0.00004463 | best=0.00004243

22:25:48 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.086672 | val_mse_raw=0.00004614 | best=0.00004243

22:25:49 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.083422 | val_mse_raw=0.00004360 | best=0.00004243

22:25:50 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.083502 | val_mse_raw=0.00004335 | best=0.00004243
22:25:50 | INFO    | train_LSTM_baseline | Early stopping at epoch 24

22:25:50 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=3.018126 | val_mse_raw=0.00006496 | best=0.00006496

22:25:51 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.249928 | val_mse_raw=0.00006531 | best=0.00006496

22:25:52 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.248234 | val_mse_raw=0.00006486 | best=0.00006486

22:25:53 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.247134 | val_mse_raw=0.00006483 | best=0.00006483

22:25:54 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.247406 | val_mse_raw=0.00006471 | best=0.00006471

22:25:55 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.201951 | val_mse_raw=0.00262677 | best=0.00006471

22:25:55 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.125320 | val_mse_raw=0.00004951 | best=0.00004951

22:25:56 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.112980 | val_mse_raw=0.00004604 | best=0.00004604

22:25:57 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.109096 | val_mse_raw=0.00004602 | best=0.00004602

22:25:58 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.103606 | val_mse_raw=0.00004418 | best=0.00004418

22:25:59 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.099141 | val_mse_raw=0.00004274 | best=0.00004274

22:26:00 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.096493 | val_mse_raw=0.00004394 | best=0.00004274

22:26:00 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.096183 | val_mse_raw=0.00004437 | best=0.00004274

22:26:01 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.094799 | val_mse_raw=0.00004467 | best=0.00004274

22:26:02 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.091176 | val_mse_raw=0.00004249 | best=0.00004249

22:26:03 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.089036 | val_mse_raw=0.00004471 | best=0.00004249

22:26:04 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.088738 | val_mse_raw=0.00004269 | best=0.00004249

22:26:05 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.089807 | val_mse_raw=0.00004297 | best=0.00004249

22:26:06 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.085549 | val_mse_raw=0.00004665 | best=0.00004249

22:26:06 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.086760 | val_mse_raw=0.00004419 | best=0.00004249

22:26:07 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.083583 | val_mse_raw=0.00004363 | best=0.00004249

22:26:08 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.083425 | val_mse_raw=0.00004466 | best=0.00004249

22:26:09 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.080298 | val_mse_raw=0.00004824 | best=0.00004249

22:26:10 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.077937 | val_mse_raw=0.00004714 | best=0.00004249

22:26:11 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.078385 | val_mse_raw=0.00004552 | best=0.00004249
22:26:11 | INFO    | train_LSTM_baseline | Early stopping at epoch 25

22:26:11 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.954202 | val_mse_raw=0.00005156 | best=0.00005156

22:26:11 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.152429 | val_mse_raw=0.00007067 | best=0.00005156

22:26:12 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.130018 | val_mse_raw=0.00004548 | best=0.00004548

22:26:12 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.118067 | val_mse_raw=0.00004396 | best=0.00004396

22:26:13 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.115223 | val_mse_raw=0.00004374 | best=0.00004374

22:26:13 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.109897 | val_mse_raw=0.00004319 | best=0.00004319

22:26:14 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.105521 | val_mse_raw=0.00004336 | best=0.00004319

22:26:14 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.107119 | val_mse_raw=0.00004431 | best=0.00004319

22:26:14 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.105767 | val_mse_raw=0.00004417 | best=0.00004319

22:26:15 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.103839 | val_mse_raw=0.00004436 | best=0.00004319

22:26:15 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.102639 | val_mse_raw=0.00004588 | best=0.00004319

22:26:16 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.100208 | val_mse_raw=0.00004603 | best=0.00004319

22:26:16 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.099656 | val_mse_raw=0.00004486 | best=0.00004319

22:26:16 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.098623 | val_mse_raw=0.00004563 | best=0.00004319

22:26:17 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.102145 | val_mse_raw=0.00004480 | best=0.00004319

22:26:17 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.096912 | val_mse_raw=0.00004462 | best=0.00004319
22:26:17 | INFO    | train_LSTM_baseline | Early stopping at epoch 16
22:26:17 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=19.238368 | val_mse_raw=0.01770068 | best=0.01770068

22:26:18 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=1.689978 | val_mse_raw=0.00005025 | best=0.00005025
22:26:18 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.183991 | val_mse_raw=0.00005504 | best=0.00005025

22:26:18 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.157189 | val_mse_raw=0.00007319 | best=0.00005025
22:26:18 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.140657 | val_mse_raw=0.00007467 | best=0.00005025

22:26:18 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.129379 | val_mse_raw=0.00006429 | best=0.00005025
22:26:18 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.121041 | val_mse_raw=0.00005308 | best=0.00005025

22:26:19 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.114495 | val_mse_raw=0.00004666 | best=0.00004666
22:26:19 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.109613 | val_mse_raw=0.00004269 | best=0.00004269

22:26:19 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.106495 | val_mse_raw=0.00004103 | best=0.00004103
22:26:19 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.104875 | val_mse_raw=0.00004060 | best=0.00004060

22:26:19 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.103853 | val_mse_raw=0.00004039 | best=0.00004039
22:26:19 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.102457 | val_mse_raw=0.00004039 | best=0.00004039

22:26:20 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.101494 | val_mse_raw=0.00004053 | best=0.00004039
22:26:20 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.101176 | val_mse_raw=0.00004045 | best=0.00004039

22:26:20 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.100320 | val_mse_raw=0.00004030 | best=0.00004030

22:26:20 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.100384 | val_mse_raw=0.00004031 | best=0.00004030
22:26:20 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.099286 | val_mse_raw=0.00004036 | best=0.00004030

22:26:21 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.099070 | val_mse_raw=0.00004020 | best=0.00004020
22:26:21 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.098113 | val_mse_raw=0.00004021 | best=0.00004020

22:26:21 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.098037 | val_mse_raw=0.00004007 | best=0.00004007
22:26:21 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.097150 | val_mse_raw=0.00004027 | best=0.00004007

22:26:21 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.097066 | val_mse_raw=0.00004013 | best=0.00004007
22:26:21 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.096866 | val_mse_raw=0.00004079 | best=0.00004007

22:26:22 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.095806 | val_mse_raw=0.00004055 | best=0.00004007
22:26:22 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.095309 | val_mse_raw=0.00004076 | best=0.00004007

22:26:22 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.095736 | val_mse_raw=0.00004027 | best=0.00004007
22:26:22 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.095939 | val_mse_raw=0.00004066 | best=0.00004007

22:26:22 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.094038 | val_mse_raw=0.00004083 | best=0.00004007
22:26:23 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.093813 | val_mse_raw=0.00004056 | best=0.00004007

22:26:23 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.093280 | val_mse_raw=0.00004146 | best=0.00004007
22:26:23 | INFO    | train_LSTM_baseline | Early stopping at epoch 31
22:26:23 | INFO    | train_LSTM_baseline | Best val MSE (raw scale): 0.00003817
22:26:23 | INFO    | train_LSTM_baseline | Best params: {'hidden_size': 64, 'n_layers': 3, 'dropout': 0.4734809381950747, 'lr': 0.009882549701018798, 'batch_size': 64, 'seq_len': 21}

22:26:24 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.236221 | val_mse_raw=0.00006612 | best=0.00006612

22:26:25 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.248436 | val_mse_raw=0.00006495 | best=0.00006495

22:26:26 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.248312 | val_mse_raw=0.00006489 | best=0.00006489

22:26:26 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.250778 | val_mse_raw=0.00006660 | best=0.00006489

22:26:27 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.250371 | val_mse_raw=0.00006587 | best=0.00006489

22:26:28 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.252215 | val_mse_raw=0.00006491 | best=0.00006489

22:26:29 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.246958 | val_mse_raw=0.00006511 | best=0.00006489

22:26:30 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.197737 | val_mse_raw=0.00004981 | best=0.00004981

22:26:31 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.133449 | val_mse_raw=0.00004525 | best=0.00004525

22:26:31 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.119263 | val_mse_raw=0.00004231 | best=0.00004231

22:26:32 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.112975 | val_mse_raw=0.00004105 | best=0.00004105

22:26:33 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.112666 | val_mse_raw=0.00004101 | best=0.00004101

22:26:34 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.112741 | val_mse_raw=0.00004030 | best=0.00004030

22:26:35 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.104309 | val_mse_raw=0.00003817 | best=0.00003817

22:26:35 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.104111 | val_mse_raw=0.00003921 | best=0.00003817

22:26:36 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.094971 | val_mse_raw=0.00004301 | best=0.00003817

22:26:37 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.088484 | val_mse_raw=0.00004408 | best=0.00003817

22:26:38 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.085844 | val_mse_raw=0.00004439 | best=0.00003817

22:26:39 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.077770 | val_mse_raw=0.00004615 | best=0.00003817

22:26:40 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.075942 | val_mse_raw=0.00004563 | best=0.00003817

22:26:41 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.072542 | val_mse_raw=0.00004999 | best=0.00003817

22:26:42 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.068063 | val_mse_raw=0.00004985 | best=0.00003817

22:26:42 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.064347 | val_mse_raw=0.00005368 | best=0.00003817

22:26:43 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.061929 | val_mse_raw=0.00004843 | best=0.00003817
22:26:43 | INFO    | train_LSTM_baseline | Early stopping at epoch 24
22:26:43 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00003817
22:26:43 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.4861100680718664e-05, 'RMSE': 0.0038550097960978746, 'MAE': 0.0024614923167973757, 'n_test_windows': 1461}
22:26:43 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_O_seed42.pt
22:26:43 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_O_seed42_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 3,
    "dropout": 0.4734809381950747,
    "lr": 0.009882549701018798,
    "batch_size": 64,
    "seq_len": 21
  },
  "best_val_mse_raw": 3.817216565948911e-05,
  "retrained_val_mse_raw": 3.817216565948911e-05,
  "test_metrics": {
    "MSE": 1.4861100680718664e-05,
    "RMSE": 0.0038550097960978746,
    "MAE": 0.0024614923167973757,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d"
  ],
  "target": "realized_vol_21d",
  "n_trials": 20,
  "seed": 42,
  "fixed_hparams_source": null
}

  [seed 42]  hparams JSON saved → hparams_lstm_baseline_O.json
================================================================================
[variant O  seed 43]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d --output-prefix lstm_baseline_O_seed43 --seed 43 --fixed-hparams /content/repo/models/hparams_lstm_baseline_O.json
--------------------------------------------------------------------------------

22:26:46 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d']
22:26:46 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:26:46 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:26:46 | INFO    | train_LSTM_baseline | n_features=5 | rows — train=3691 val=1089 test=1481
22:26:46 | INFO    | train_LSTM_baseline | Skipping Optuna — using fixed hparams from /content/repo/models/hparams_lstm_baseline_O.json
22:26:46 | INFO    | train_LSTM_baseline | Fixed params: {'hidden_size': 64, 'n_layers': 3, 'dropout': 0.4734809381950747, 'lr': 0.009882549701018798, 'batch_size': 64, 'seq_len': 21}

22:26:48 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.348302 | val_mse_raw=0.00006552 | best=0.00006552

22:26:49 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.248212 | val_mse_raw=0.00006553 | best=0.00006552

22:26:50 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.249021 | val_mse_raw=0.00006489 | best=0.00006489

22:26:51 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.250581 | val_mse_raw=0.00006495 | best=0.00006489

22:26:52 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.249496 | val_mse_raw=0.00006553 | best=0.00006489

22:26:53 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.247650 | val_mse_raw=0.00006699 | best=0.00006489

22:26:54 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.249988 | val_mse_raw=0.00006555 | best=0.00006489

22:26:55 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.252463 | val_mse_raw=0.00006662 | best=0.00006489

22:26:56 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.257363 | val_mse_raw=0.00006487 | best=0.00006487

22:26:57 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.249789 | val_mse_raw=0.00006677 | best=0.00006487

22:26:58 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.250697 | val_mse_raw=0.00006561 | best=0.00006487

22:26:59 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.250118 | val_mse_raw=0.00006591 | best=0.00006487

22:27:01 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.252217 | val_mse_raw=0.00006488 | best=0.00006487

22:27:02 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.252320 | val_mse_raw=0.00006536 | best=0.00006487

22:27:03 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.255344 | val_mse_raw=0.00006500 | best=0.00006487

22:27:04 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.251250 | val_mse_raw=0.00006674 | best=0.00006487

22:27:05 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.250829 | val_mse_raw=0.00006536 | best=0.00006487

22:27:06 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.250226 | val_mse_raw=0.00006523 | best=0.00006487

22:27:07 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.251638 | val_mse_raw=0.00006758 | best=0.00006487
22:27:07 | INFO    | train_LSTM_baseline | Early stopping at epoch 19
22:27:07 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00006487
22:27:07 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 2.0828423657803796e-05, 'RMSE': 0.004563816823065281, 'MAE': 0.0030773039907217026, 'n_test_windows': 1461}
22:27:07 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_O_seed43.pt
22:27:07 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_O_seed43_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 3,
    "dropout": 0.4734809381950747,
    "lr": 0.009882549701018798,
    "batch_size": 64,
    "seq_len": 21
  },
  "best_val_mse_raw": NaN,
  "retrained_val_mse_raw": 6.48716013529338e-05,
  "test_metrics": {
    "MSE": 2.0828423657803796e-05,
    "RMSE": 0.004563816823065281,
    "MAE": 0.0030773039907217026,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d"
  ],
  "target": "realized_vol_21d",
  "n_trials": 0,
  "seed": 43,
  "fixed_hparams_source": "/content/repo/models/hparams_lstm_baseline_O.json"
}

================================================================================
[variant O  seed 44]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d --output-prefix lstm_baseline_O_seed44 --seed 44 --fixed-hparams /content/repo/models/hparams_lstm_baseline_O.json
--------------------------------------------------------------------------------

22:27:10 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d']
22:27:10 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:27:10 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:27:10 | INFO    | train_LSTM_baseline | n_features=5 | rows — train=3691 val=1089 test=1481
22:27:10 | INFO    | train_LSTM_baseline | Skipping Optuna — using fixed hparams from /content/repo/models/hparams_lstm_baseline_O.json
22:27:10 | INFO    | train_LSTM_baseline | Fixed params: {'hidden_size': 64, 'n_layers': 3, 'dropout': 0.4734809381950747, 'lr': 0.009882549701018798, 'batch_size': 64, 'seq_len': 21}

22:27:12 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.343961 | val_mse_raw=0.00006585 | best=0.00006585

22:27:13 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.248583 | val_mse_raw=0.00006487 | best=0.00006487

22:27:14 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.249052 | val_mse_raw=0.00006567 | best=0.00006487

22:27:15 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.256581 | val_mse_raw=0.00006535 | best=0.00006487

22:27:16 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.252632 | val_mse_raw=0.00006487 | best=0.00006487

22:27:17 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.250241 | val_mse_raw=0.00006496 | best=0.00006487

22:27:18 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.253846 | val_mse_raw=0.00006608 | best=0.00006487

22:27:19 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.255403 | val_mse_raw=0.00006645 | best=0.00006487

22:27:20 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.232187 | val_mse_raw=0.00005667 | best=0.00005667

22:27:21 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.161496 | val_mse_raw=0.00005124 | best=0.00005124

22:27:22 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.137995 | val_mse_raw=0.00004765 | best=0.00004765

22:27:23 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.128263 | val_mse_raw=0.00004956 | best=0.00004765

22:27:24 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.126458 | val_mse_raw=0.00004538 | best=0.00004538

22:27:25 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.112897 | val_mse_raw=0.00004298 | best=0.00004298

22:27:26 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.117245 | val_mse_raw=0.00004907 | best=0.00004298

22:27:27 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.104570 | val_mse_raw=0.00004469 | best=0.00004298

22:27:28 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.103983 | val_mse_raw=0.00004328 | best=0.00004298

22:27:29 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.097891 | val_mse_raw=0.00004847 | best=0.00004298

22:27:30 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.100772 | val_mse_raw=0.00004614 | best=0.00004298

22:27:31 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.089573 | val_mse_raw=0.00004403 | best=0.00004298

22:27:32 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.089634 | val_mse_raw=0.00004902 | best=0.00004298

22:27:33 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.088079 | val_mse_raw=0.00005512 | best=0.00004298

22:27:34 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.084095 | val_mse_raw=0.00005315 | best=0.00004298

22:27:35 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.081477 | val_mse_raw=0.00005313 | best=0.00004298
22:27:35 | INFO    | train_LSTM_baseline | Early stopping at epoch 24
22:27:35 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00004298
22:27:35 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.7472753825131804e-05, 'RMSE': 0.004180042538791895, 'MAE': 0.002664398169144988, 'n_test_windows': 1461}
22:27:35 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_O_seed44.pt
22:27:35 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_O_seed44_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 3,
    "dropout": 0.4734809381950747,
    "lr": 0.009882549701018798,
    "batch_size": 64,
    "seq_len": 21
  },
  "best_val_mse_raw": NaN,
  "retrained_val_mse_raw": 4.297742634662427e-05,
  "test_metrics": {
    "MSE": 1.7472753825131804e-05,
    "RMSE": 0.004180042538791895,
    "MAE": 0.002664398169144988,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d"
  ],
  "target": "realized_vol_21d",
  "n_trials": 0,
  "seed": 44,
  "fixed_hparams_source": "/content/repo/models/hparams_lstm_baseline_O.json"
}

================================================================================
[variant A  seed 42]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish --output-prefix lstm_baseline_seed42 --seed 42
--------------------------------------------------------------------------------

22:27:38 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish']
22:27:38 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:27:38 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:27:38 | INFO    | train_LSTM_baseline | n_features=7 | rows — train=3691 val=1089 test=1481
22:27:38 | INFO    | train_LSTM_baseline | Starting Optuna study with 20 trials…

22:27:39 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.523130 | val_mse_raw=0.00006426 | best=0.00006426

22:27:40 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.139546 | val_mse_raw=0.00006359 | best=0.00006359

22:27:40 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.123490 | val_mse_raw=0.00004595 | best=0.00004595

22:27:40 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.115117 | val_mse_raw=0.00004355 | best=0.00004355

22:27:40 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.112557 | val_mse_raw=0.00004262 | best=0.00004262

22:27:41 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.109189 | val_mse_raw=0.00004335 | best=0.00004262

22:27:41 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.109520 | val_mse_raw=0.00004359 | best=0.00004262

22:27:41 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.103075 | val_mse_raw=0.00004246 | best=0.00004246

22:27:41 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.100800 | val_mse_raw=0.00004369 | best=0.00004246

22:27:42 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.101835 | val_mse_raw=0.00004250 | best=0.00004246

22:27:42 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098821 | val_mse_raw=0.00004341 | best=0.00004246

22:27:42 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.095763 | val_mse_raw=0.00004354 | best=0.00004246

22:27:43 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.094689 | val_mse_raw=0.00004314 | best=0.00004246

22:27:43 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.096225 | val_mse_raw=0.00004392 | best=0.00004246

22:27:43 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.094205 | val_mse_raw=0.00004421 | best=0.00004246

22:27:43 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.095662 | val_mse_raw=0.00004427 | best=0.00004246

22:27:44 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.092893 | val_mse_raw=0.00004380 | best=0.00004246

22:27:44 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.091388 | val_mse_raw=0.00004664 | best=0.00004246
22:27:44 | INFO    | train_LSTM_baseline | Early stopping at epoch 18

22:27:44 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=16.394774 | val_mse_raw=0.00465310 | best=0.00465310

22:27:45 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=1.437245 | val_mse_raw=0.00006584 | best=0.00006584

22:27:45 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.266122 | val_mse_raw=0.00006543 | best=0.00006543

22:27:46 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.243971 | val_mse_raw=0.00006533 | best=0.00006533

22:27:46 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.240810 | val_mse_raw=0.00006474 | best=0.00006474

22:27:47 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.237599 | val_mse_raw=0.00006396 | best=0.00006396

22:27:48 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.231422 | val_mse_raw=0.00006262 | best=0.00006262

22:27:48 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.222017 | val_mse_raw=0.00006028 | best=0.00006028

22:27:49 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.204047 | val_mse_raw=0.00005612 | best=0.00005612

22:27:49 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.172928 | val_mse_raw=0.00005005 | best=0.00005005

22:27:50 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.133609 | val_mse_raw=0.00004525 | best=0.00004525

22:27:50 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.110815 | val_mse_raw=0.00004475 | best=0.00004475

22:27:51 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.107029 | val_mse_raw=0.00004403 | best=0.00004403

22:27:51 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.104505 | val_mse_raw=0.00004358 | best=0.00004358

22:27:52 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.102319 | val_mse_raw=0.00004370 | best=0.00004358

22:27:53 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.101431 | val_mse_raw=0.00004321 | best=0.00004321

22:27:53 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.099528 | val_mse_raw=0.00004327 | best=0.00004321

22:27:54 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.098966 | val_mse_raw=0.00004330 | best=0.00004321

22:27:54 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.098111 | val_mse_raw=0.00004357 | best=0.00004321

22:27:55 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.097068 | val_mse_raw=0.00004327 | best=0.00004321

22:27:55 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.097633 | val_mse_raw=0.00004355 | best=0.00004321

22:27:56 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.097558 | val_mse_raw=0.00004372 | best=0.00004321

22:27:56 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.095839 | val_mse_raw=0.00004368 | best=0.00004321

22:27:57 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.095534 | val_mse_raw=0.00004384 | best=0.00004321

22:27:57 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.095159 | val_mse_raw=0.00004460 | best=0.00004321

22:27:58 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.094068 | val_mse_raw=0.00004409 | best=0.00004321
22:27:58 | INFO    | train_LSTM_baseline | Early stopping at epoch 26

22:28:01 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=0.723365 | val_mse_raw=0.00006643 | best=0.00006643

22:28:03 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.225300 | val_mse_raw=0.00005106 | best=0.00005106

22:28:06 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.121948 | val_mse_raw=0.00004541 | best=0.00004541

22:28:09 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.111341 | val_mse_raw=0.00005028 | best=0.00004541

22:28:11 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.107067 | val_mse_raw=0.00004285 | best=0.00004285

22:28:14 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.102926 | val_mse_raw=0.00005101 | best=0.00004285

22:28:16 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.110137 | val_mse_raw=0.00004581 | best=0.00004285

22:28:19 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.104414 | val_mse_raw=0.00004415 | best=0.00004285

22:28:22 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.117962 | val_mse_raw=0.00004984 | best=0.00004285

22:28:24 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.097346 | val_mse_raw=0.00004942 | best=0.00004285

22:28:27 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.111622 | val_mse_raw=0.00004158 | best=0.00004158

22:28:30 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.090198 | val_mse_raw=0.00004604 | best=0.00004158

22:28:32 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.091714 | val_mse_raw=0.00004948 | best=0.00004158

22:28:35 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.085744 | val_mse_raw=0.00005083 | best=0.00004158

22:28:38 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.091269 | val_mse_raw=0.00005806 | best=0.00004158

22:28:40 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.079810 | val_mse_raw=0.00005035 | best=0.00004158

22:28:43 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.080467 | val_mse_raw=0.00004496 | best=0.00004158

22:28:45 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.081200 | val_mse_raw=0.00009363 | best=0.00004158

22:28:48 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.092807 | val_mse_raw=0.00005107 | best=0.00004158

22:28:51 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.072190 | val_mse_raw=0.00005347 | best=0.00004158

22:28:53 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.085473 | val_mse_raw=0.00005748 | best=0.00004158
22:28:53 | INFO    | train_LSTM_baseline | Early stopping at epoch 21

22:28:54 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=9.124346 | val_mse_raw=0.00006448 | best=0.00006448

22:28:55 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.245569 | val_mse_raw=0.00006301 | best=0.00006301

22:28:56 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.221285 | val_mse_raw=0.00006915 | best=0.00006301

22:28:57 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.158699 | val_mse_raw=0.00005097 | best=0.00005097

22:28:59 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.122890 | val_mse_raw=0.00005077 | best=0.00005077

22:29:00 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.112175 | val_mse_raw=0.00004798 | best=0.00004798

22:29:01 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.107459 | val_mse_raw=0.00004661 | best=0.00004661

22:29:02 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.105103 | val_mse_raw=0.00004641 | best=0.00004641

22:29:03 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.102323 | val_mse_raw=0.00004535 | best=0.00004535

22:29:04 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.099282 | val_mse_raw=0.00004590 | best=0.00004535

22:29:05 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.100067 | val_mse_raw=0.00004462 | best=0.00004462

22:29:06 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.097622 | val_mse_raw=0.00004429 | best=0.00004429

22:29:07 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.097882 | val_mse_raw=0.00004425 | best=0.00004425

22:29:08 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.098017 | val_mse_raw=0.00004452 | best=0.00004425

22:29:09 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.096653 | val_mse_raw=0.00004436 | best=0.00004425

22:29:10 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.096045 | val_mse_raw=0.00004442 | best=0.00004425

22:29:11 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.096174 | val_mse_raw=0.00004380 | best=0.00004380

22:29:12 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.094128 | val_mse_raw=0.00004375 | best=0.00004375

22:29:14 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.094942 | val_mse_raw=0.00004395 | best=0.00004375

22:29:15 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.093861 | val_mse_raw=0.00004427 | best=0.00004375

22:29:16 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.094808 | val_mse_raw=0.00004378 | best=0.00004375

22:29:17 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.092824 | val_mse_raw=0.00004410 | best=0.00004375

22:29:18 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.092487 | val_mse_raw=0.00004410 | best=0.00004375

22:29:19 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.091256 | val_mse_raw=0.00004489 | best=0.00004375

22:29:20 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.091726 | val_mse_raw=0.00004360 | best=0.00004360

22:29:21 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.090070 | val_mse_raw=0.00004374 | best=0.00004360

22:29:22 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.090722 | val_mse_raw=0.00004423 | best=0.00004360

22:29:23 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.089526 | val_mse_raw=0.00004579 | best=0.00004360

22:29:24 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.089556 | val_mse_raw=0.00004603 | best=0.00004360

22:29:25 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.087127 | val_mse_raw=0.00004627 | best=0.00004360

22:29:26 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.086691 | val_mse_raw=0.00004452 | best=0.00004360

22:29:27 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.086453 | val_mse_raw=0.00004495 | best=0.00004360

22:29:28 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.084922 | val_mse_raw=0.00004468 | best=0.00004360

22:29:29 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.084083 | val_mse_raw=0.00004461 | best=0.00004360

22:29:30 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.082978 | val_mse_raw=0.00004441 | best=0.00004360
22:29:30 | INFO    | train_LSTM_baseline | Early stopping at epoch 35
22:29:30 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=21.751756 | val_mse_raw=0.72598451 | best=0.72598451

22:29:31 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=20.248637 | val_mse_raw=0.44971183 | best=0.44971183
22:29:31 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=16.677368 | val_mse_raw=0.07940765 | best=0.07940765

22:29:31 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=7.336832 | val_mse_raw=0.00310524 | best=0.00310524
22:29:31 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=1.572275 | val_mse_raw=0.00025061 | best=0.00025061

22:29:31 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.376331 | val_mse_raw=0.00009668 | best=0.00009668
22:29:31 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.206348 | val_mse_raw=0.00008742 | best=0.00008742

22:29:31 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.178935 | val_mse_raw=0.00010001 | best=0.00008742
22:29:32 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.168802 | val_mse_raw=0.00011548 | best=0.00008742

22:29:32 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.160670 | val_mse_raw=0.00012759 | best=0.00008742
22:29:32 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.153173 | val_mse_raw=0.00012762 | best=0.00008742

22:29:32 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.146198 | val_mse_raw=0.00012537 | best=0.00008742
22:29:32 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.139729 | val_mse_raw=0.00011496 | best=0.00008742

22:29:32 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.134280 | val_mse_raw=0.00010742 | best=0.00008742
22:29:32 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.129832 | val_mse_raw=0.00009955 | best=0.00008742

22:29:33 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.126058 | val_mse_raw=0.00009189 | best=0.00008742
22:29:33 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.122776 | val_mse_raw=0.00008580 | best=0.00008580

22:29:33 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.119895 | val_mse_raw=0.00008488 | best=0.00008488
22:29:33 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.117327 | val_mse_raw=0.00008223 | best=0.00008223

22:29:33 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.114952 | val_mse_raw=0.00007567 | best=0.00007567
22:29:33 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.112837 | val_mse_raw=0.00007452 | best=0.00007452

22:29:33 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.111046 | val_mse_raw=0.00007322 | best=0.00007322
22:29:33 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.109513 | val_mse_raw=0.00006941 | best=0.00006941

22:29:34 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.108403 | val_mse_raw=0.00006809 | best=0.00006809
22:29:34 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.107556 | val_mse_raw=0.00006579 | best=0.00006579

22:29:34 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.106911 | val_mse_raw=0.00006459 | best=0.00006459
22:29:34 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.106449 | val_mse_raw=0.00006280 | best=0.00006280

22:29:34 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.105998 | val_mse_raw=0.00006117 | best=0.00006117
22:29:34 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.105671 | val_mse_raw=0.00006050 | best=0.00006050

22:29:34 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.105508 | val_mse_raw=0.00005968 | best=0.00005968
22:29:35 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.104810 | val_mse_raw=0.00005893 | best=0.00005893

22:29:35 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.104452 | val_mse_raw=0.00005782 | best=0.00005782
22:29:35 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.104056 | val_mse_raw=0.00005635 | best=0.00005635

22:29:35 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.103724 | val_mse_raw=0.00005595 | best=0.00005595
22:29:35 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.103423 | val_mse_raw=0.00005552 | best=0.00005552

22:29:35 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.103102 | val_mse_raw=0.00005433 | best=0.00005433
22:29:35 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.102683 | val_mse_raw=0.00005385 | best=0.00005385

22:29:36 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.102296 | val_mse_raw=0.00005330 | best=0.00005330
22:29:36 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.102112 | val_mse_raw=0.00005201 | best=0.00005201

22:29:36 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.101761 | val_mse_raw=0.00005172 | best=0.00005172

22:29:37 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=13.839638 | val_mse_raw=0.00005709 | best=0.00005709

22:29:39 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.164270 | val_mse_raw=0.00010315 | best=0.00005709

22:29:40 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.132848 | val_mse_raw=0.00005963 | best=0.00005709

22:29:41 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.119827 | val_mse_raw=0.00005375 | best=0.00005375

22:29:42 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.113615 | val_mse_raw=0.00005184 | best=0.00005184

22:29:44 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.109758 | val_mse_raw=0.00005141 | best=0.00005141

22:29:45 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.106228 | val_mse_raw=0.00004987 | best=0.00004987

22:29:46 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.104143 | val_mse_raw=0.00004836 | best=0.00004836

22:29:47 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.102530 | val_mse_raw=0.00004717 | best=0.00004717

22:29:49 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.100778 | val_mse_raw=0.00004764 | best=0.00004717

22:29:50 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.100026 | val_mse_raw=0.00004575 | best=0.00004575

22:29:51 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.098399 | val_mse_raw=0.00004568 | best=0.00004568

22:29:53 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.099362 | val_mse_raw=0.00004537 | best=0.00004537

22:29:54 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.096656 | val_mse_raw=0.00004482 | best=0.00004482

22:29:55 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.097222 | val_mse_raw=0.00004519 | best=0.00004482

22:29:56 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.095782 | val_mse_raw=0.00004431 | best=0.00004431

22:29:58 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.096246 | val_mse_raw=0.00004461 | best=0.00004431

22:29:59 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.095461 | val_mse_raw=0.00004419 | best=0.00004419

22:30:00 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.095485 | val_mse_raw=0.00004426 | best=0.00004419

22:30:02 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.095109 | val_mse_raw=0.00004381 | best=0.00004381

22:30:03 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.094478 | val_mse_raw=0.00004328 | best=0.00004328

22:30:04 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.094841 | val_mse_raw=0.00004339 | best=0.00004328

22:30:06 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.094567 | val_mse_raw=0.00004331 | best=0.00004328

22:30:07 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.094691 | val_mse_raw=0.00004358 | best=0.00004328

22:30:08 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.094025 | val_mse_raw=0.00004323 | best=0.00004323

22:30:09 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.093790 | val_mse_raw=0.00004425 | best=0.00004323

22:30:11 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.094013 | val_mse_raw=0.00004295 | best=0.00004295

22:30:12 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.093721 | val_mse_raw=0.00004389 | best=0.00004295

22:30:14 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.093205 | val_mse_raw=0.00004334 | best=0.00004295

22:30:15 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.092527 | val_mse_raw=0.00004381 | best=0.00004295

22:30:16 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.092221 | val_mse_raw=0.00004337 | best=0.00004295

22:30:17 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.093902 | val_mse_raw=0.00004389 | best=0.00004295

22:30:19 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.092509 | val_mse_raw=0.00004309 | best=0.00004295

22:30:20 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.092048 | val_mse_raw=0.00004328 | best=0.00004295

22:30:21 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.092169 | val_mse_raw=0.00004330 | best=0.00004295

22:30:22 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.092834 | val_mse_raw=0.00004402 | best=0.00004295

22:30:24 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.092088 | val_mse_raw=0.00004371 | best=0.00004295
22:30:24 | INFO    | train_LSTM_baseline | Early stopping at epoch 37

22:30:24 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.680457 | val_mse_raw=0.16749908 | best=0.16749908

22:30:25 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=3.125265 | val_mse_raw=0.00006520 | best=0.00006520

22:30:25 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.231798 | val_mse_raw=0.00005670 | best=0.00005670

22:30:25 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.195677 | val_mse_raw=0.00005290 | best=0.00005290

22:30:26 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.177224 | val_mse_raw=0.00004870 | best=0.00004870

22:30:26 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.156963 | val_mse_raw=0.00004353 | best=0.00004353

22:30:27 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.122487 | val_mse_raw=0.00004219 | best=0.00004219

22:30:27 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.105954 | val_mse_raw=0.00004502 | best=0.00004219

22:30:27 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.104658 | val_mse_raw=0.00004495 | best=0.00004219

22:30:28 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.102275 | val_mse_raw=0.00004457 | best=0.00004219

22:30:28 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.101792 | val_mse_raw=0.00004483 | best=0.00004219

22:30:28 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.102426 | val_mse_raw=0.00004518 | best=0.00004219

22:30:29 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.099935 | val_mse_raw=0.00004426 | best=0.00004219

22:30:29 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.099851 | val_mse_raw=0.00004421 | best=0.00004219

22:30:29 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.098176 | val_mse_raw=0.00004388 | best=0.00004219

22:30:30 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.098207 | val_mse_raw=0.00004350 | best=0.00004219

22:30:30 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.098333 | val_mse_raw=0.00004334 | best=0.00004219
22:30:30 | INFO    | train_LSTM_baseline | Early stopping at epoch 17

22:30:31 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.955185 | val_mse_raw=0.63624948 | best=0.63624948

22:30:31 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=20.470010 | val_mse_raw=0.56198055 | best=0.56198055

22:30:31 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=19.849743 | val_mse_raw=0.46932879 | best=0.46932879

22:30:32 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=18.796213 | val_mse_raw=0.32234228 | best=0.32234228

22:30:32 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=15.354414 | val_mse_raw=0.06361523 | best=0.06361523

22:30:32 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=6.041418 | val_mse_raw=0.00335803 | best=0.00335803

22:30:33 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=2.060024 | val_mse_raw=0.00034479 | best=0.00034479

22:30:33 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.880507 | val_mse_raw=0.00011531 | best=0.00011531

22:30:33 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.421892 | val_mse_raw=0.00006752 | best=0.00006752

22:30:34 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.260313 | val_mse_raw=0.00005578 | best=0.00005578

22:30:34 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.209442 | val_mse_raw=0.00005254 | best=0.00005254

22:30:34 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.191717 | val_mse_raw=0.00005147 | best=0.00005147

22:30:35 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.183884 | val_mse_raw=0.00005096 | best=0.00005096

22:30:35 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.177818 | val_mse_raw=0.00005081 | best=0.00005081

22:30:35 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.171914 | val_mse_raw=0.00005099 | best=0.00005081

22:30:36 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.166359 | val_mse_raw=0.00005167 | best=0.00005081

22:30:36 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.160749 | val_mse_raw=0.00005248 | best=0.00005081

22:30:36 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.155333 | val_mse_raw=0.00005287 | best=0.00005081

22:30:37 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.149766 | val_mse_raw=0.00005418 | best=0.00005081

22:30:37 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.144325 | val_mse_raw=0.00005482 | best=0.00005081

22:30:38 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.138552 | val_mse_raw=0.00005564 | best=0.00005081

22:30:38 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.132766 | val_mse_raw=0.00005643 | best=0.00005081

22:30:38 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.127557 | val_mse_raw=0.00005765 | best=0.00005081

22:30:39 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.122914 | val_mse_raw=0.00005809 | best=0.00005081
22:30:39 | INFO    | train_LSTM_baseline | Early stopping at epoch 24

22:30:39 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=21.086162 | val_mse_raw=0.47441867 | best=0.47441867

22:30:39 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=11.242216 | val_mse_raw=0.00259182 | best=0.00259182

22:30:39 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.935246 | val_mse_raw=0.00014909 | best=0.00014909

22:30:40 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.224407 | val_mse_raw=0.00011192 | best=0.00011192

22:30:40 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.171784 | val_mse_raw=0.00014649 | best=0.00011192

22:30:40 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.152803 | val_mse_raw=0.00013778 | best=0.00011192

22:30:41 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.137332 | val_mse_raw=0.00011810 | best=0.00011192

22:30:41 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.126849 | val_mse_raw=0.00010195 | best=0.00010195

22:30:41 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.119743 | val_mse_raw=0.00009632 | best=0.00009632

22:30:41 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.114044 | val_mse_raw=0.00008487 | best=0.00008487

22:30:42 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.110188 | val_mse_raw=0.00007571 | best=0.00007571

22:30:42 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.107608 | val_mse_raw=0.00007138 | best=0.00007138

22:30:42 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.106205 | val_mse_raw=0.00007000 | best=0.00007000

22:30:43 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.105102 | val_mse_raw=0.00006540 | best=0.00006540

22:30:43 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.104270 | val_mse_raw=0.00006367 | best=0.00006367

22:30:43 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.103439 | val_mse_raw=0.00006127 | best=0.00006127

22:30:44 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.102769 | val_mse_raw=0.00006096 | best=0.00006096

22:30:44 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.102031 | val_mse_raw=0.00005789 | best=0.00005789

22:30:44 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.101207 | val_mse_raw=0.00005670 | best=0.00005670

22:30:44 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.100617 | val_mse_raw=0.00005811 | best=0.00005670

22:30:45 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.100102 | val_mse_raw=0.00005686 | best=0.00005670

22:30:45 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.099475 | val_mse_raw=0.00005480 | best=0.00005480

22:30:45 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.098795 | val_mse_raw=0.00005365 | best=0.00005365

22:30:45 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.098298 | val_mse_raw=0.00005386 | best=0.00005365

22:30:46 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.097723 | val_mse_raw=0.00005501 | best=0.00005365

22:30:46 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.097321 | val_mse_raw=0.00005389 | best=0.00005365

22:30:46 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.096980 | val_mse_raw=0.00005301 | best=0.00005301

22:30:47 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.096345 | val_mse_raw=0.00005501 | best=0.00005301

22:30:47 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.095880 | val_mse_raw=0.00005401 | best=0.00005301

22:30:47 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.095578 | val_mse_raw=0.00005603 | best=0.00005301

22:30:47 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.095481 | val_mse_raw=0.00005563 | best=0.00005301

22:30:48 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.094990 | val_mse_raw=0.00005246 | best=0.00005246

22:30:48 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.094661 | val_mse_raw=0.00005183 | best=0.00005183

22:30:48 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.094394 | val_mse_raw=0.00005367 | best=0.00005183

22:30:49 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.094207 | val_mse_raw=0.00005268 | best=0.00005183

22:30:49 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.093593 | val_mse_raw=0.00005205 | best=0.00005183

22:30:49 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.093756 | val_mse_raw=0.00005565 | best=0.00005183

22:30:50 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.093193 | val_mse_raw=0.00005151 | best=0.00005151

22:30:50 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.092750 | val_mse_raw=0.00005327 | best=0.00005151

22:30:50 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.092435 | val_mse_raw=0.00005149 | best=0.00005149

22:30:51 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.726525 | val_mse_raw=0.48551074 | best=0.48551074

22:30:52 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=14.290021 | val_mse_raw=0.00584256 | best=0.00584256

22:30:52 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=1.700732 | val_mse_raw=0.00006526 | best=0.00006526

22:30:53 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.240883 | val_mse_raw=0.00006316 | best=0.00006316

22:30:54 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.230191 | val_mse_raw=0.00006157 | best=0.00006157

22:30:54 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.217547 | val_mse_raw=0.00005888 | best=0.00005888

22:30:55 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.197577 | val_mse_raw=0.00005459 | best=0.00005459

22:30:56 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.168103 | val_mse_raw=0.00004942 | best=0.00004942

22:30:56 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.137160 | val_mse_raw=0.00004682 | best=0.00004682

22:30:57 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.122376 | val_mse_raw=0.00004678 | best=0.00004678

22:30:58 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.116914 | val_mse_raw=0.00004672 | best=0.00004672

22:30:58 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.113202 | val_mse_raw=0.00004657 | best=0.00004657

22:30:59 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.108971 | val_mse_raw=0.00004646 | best=0.00004646

22:31:00 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.105020 | val_mse_raw=0.00004685 | best=0.00004646

22:31:01 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.101965 | val_mse_raw=0.00004761 | best=0.00004646

22:31:01 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.100054 | val_mse_raw=0.00004740 | best=0.00004646

22:31:02 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.098234 | val_mse_raw=0.00004818 | best=0.00004646

22:31:03 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.098126 | val_mse_raw=0.00004774 | best=0.00004646

22:31:04 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.095764 | val_mse_raw=0.00004784 | best=0.00004646

22:31:04 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.093918 | val_mse_raw=0.00004763 | best=0.00004646

22:31:05 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.092939 | val_mse_raw=0.00004832 | best=0.00004646

22:31:06 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.092498 | val_mse_raw=0.00004821 | best=0.00004646

22:31:06 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.091983 | val_mse_raw=0.00004782 | best=0.00004646
22:31:06 | INFO    | train_LSTM_baseline | Early stopping at epoch 23

22:31:10 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=0.722806 | val_mse_raw=0.00007796 | best=0.00007796

22:31:13 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.268771 | val_mse_raw=0.00006749 | best=0.00006749

22:31:17 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.259803 | val_mse_raw=0.00006647 | best=0.00006647

22:31:20 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.271470 | val_mse_raw=0.00006627 | best=0.00006627

22:31:24 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.263516 | val_mse_raw=0.00007030 | best=0.00006627

22:31:27 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.173953 | val_mse_raw=0.00478753 | best=0.00006627

22:31:31 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.144789 | val_mse_raw=0.00004942 | best=0.00004942

22:31:34 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.146877 | val_mse_raw=0.00006834 | best=0.00004942

22:31:38 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.215058 | val_mse_raw=0.00007231 | best=0.00004942

22:31:41 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.183517 | val_mse_raw=0.00005349 | best=0.00004942

22:31:45 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.162742 | val_mse_raw=0.00005553 | best=0.00004942

22:31:48 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.152382 | val_mse_raw=0.00005481 | best=0.00004942

22:31:52 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.124699 | val_mse_raw=0.00005299 | best=0.00004942

22:31:55 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.121872 | val_mse_raw=0.00004992 | best=0.00004942

22:31:59 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.147717 | val_mse_raw=0.00005589 | best=0.00004942

22:32:03 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.121949 | val_mse_raw=0.00005102 | best=0.00004942

22:32:06 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.116567 | val_mse_raw=0.00005012 | best=0.00004942
22:32:06 | INFO    | train_LSTM_baseline | Early stopping at epoch 17

22:32:09 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.558976 | val_mse_raw=0.00006652 | best=0.00006652

22:32:13 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.234662 | val_mse_raw=0.00006304 | best=0.00006304

22:32:16 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.128814 | val_mse_raw=0.00004906 | best=0.00004906

22:32:19 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.104276 | val_mse_raw=0.00004989 | best=0.00004906

22:32:23 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.096605 | val_mse_raw=0.00004747 | best=0.00004747

22:32:26 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.103994 | val_mse_raw=0.00004962 | best=0.00004747

22:32:29 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.088815 | val_mse_raw=0.00004762 | best=0.00004747

22:32:33 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.090582 | val_mse_raw=0.00004925 | best=0.00004747

22:32:36 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.083841 | val_mse_raw=0.00004934 | best=0.00004747

22:32:40 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.079891 | val_mse_raw=0.00004877 | best=0.00004747

22:32:43 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.076734 | val_mse_raw=0.00004579 | best=0.00004579

22:32:46 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.074237 | val_mse_raw=0.00004670 | best=0.00004579

22:32:50 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.072070 | val_mse_raw=0.00004153 | best=0.00004153

22:32:53 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.067625 | val_mse_raw=0.00004861 | best=0.00004153

22:32:56 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.065718 | val_mse_raw=0.00004491 | best=0.00004153

22:33:00 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.058185 | val_mse_raw=0.00005027 | best=0.00004153

22:33:03 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.053647 | val_mse_raw=0.00004935 | best=0.00004153

22:33:07 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.047319 | val_mse_raw=0.00005371 | best=0.00004153

22:33:10 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.042403 | val_mse_raw=0.00005640 | best=0.00004153

22:33:14 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.040815 | val_mse_raw=0.00005095 | best=0.00004153

22:33:17 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.033059 | val_mse_raw=0.00005361 | best=0.00004153

22:33:20 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.026048 | val_mse_raw=0.00005476 | best=0.00004153

22:33:23 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.024070 | val_mse_raw=0.00005438 | best=0.00004153
22:33:23 | INFO    | train_LSTM_baseline | Early stopping at epoch 23

22:33:27 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.377270 | val_mse_raw=0.00007003 | best=0.00007003

22:33:30 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.201599 | val_mse_raw=0.00007047 | best=0.00007003

22:33:34 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.210355 | val_mse_raw=0.00006513 | best=0.00006513

22:33:37 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.176745 | val_mse_raw=0.00006084 | best=0.00006084

22:33:41 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.160652 | val_mse_raw=0.00005968 | best=0.00005968

22:33:44 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.144730 | val_mse_raw=0.00004475 | best=0.00004475

22:33:47 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.109347 | val_mse_raw=0.00004588 | best=0.00004475

22:33:51 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.105332 | val_mse_raw=0.00005078 | best=0.00004475

22:33:54 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.099103 | val_mse_raw=0.00005290 | best=0.00004475

22:33:58 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.092594 | val_mse_raw=0.00004628 | best=0.00004475

22:34:01 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098804 | val_mse_raw=0.00004586 | best=0.00004475

22:34:05 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.095942 | val_mse_raw=0.00004367 | best=0.00004367

22:34:08 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.087882 | val_mse_raw=0.00004615 | best=0.00004367

22:34:11 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.083761 | val_mse_raw=0.00004762 | best=0.00004367

22:34:15 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.076633 | val_mse_raw=0.00004667 | best=0.00004367

22:34:18 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.070055 | val_mse_raw=0.00005236 | best=0.00004367

22:34:22 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.069721 | val_mse_raw=0.00005283 | best=0.00004367

22:34:25 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.058206 | val_mse_raw=0.00005268 | best=0.00004367

22:34:28 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.056385 | val_mse_raw=0.00005518 | best=0.00004367

22:34:32 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.048929 | val_mse_raw=0.00005884 | best=0.00004367

22:34:35 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.045014 | val_mse_raw=0.00005905 | best=0.00004367

22:34:39 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.035190 | val_mse_raw=0.00005724 | best=0.00004367
22:34:39 | INFO    | train_LSTM_baseline | Early stopping at epoch 22

22:34:42 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.012301 | val_mse_raw=0.00006752 | best=0.00006752

22:34:45 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.252915 | val_mse_raw=0.00006687 | best=0.00006687

22:34:49 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.185686 | val_mse_raw=0.00004995 | best=0.00004995

22:34:52 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.124066 | val_mse_raw=0.00004588 | best=0.00004588

22:34:55 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.111598 | val_mse_raw=0.00004758 | best=0.00004588

22:34:59 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.113029 | val_mse_raw=0.00004538 | best=0.00004538

22:35:02 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.100135 | val_mse_raw=0.00004221 | best=0.00004221

22:35:06 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.095147 | val_mse_raw=0.00004416 | best=0.00004221

22:35:09 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.096352 | val_mse_raw=0.00004771 | best=0.00004221

22:35:12 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.104618 | val_mse_raw=0.00004599 | best=0.00004221

22:35:16 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.094531 | val_mse_raw=0.00004814 | best=0.00004221

22:35:19 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.089805 | val_mse_raw=0.00004143 | best=0.00004143

22:35:23 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.081431 | val_mse_raw=0.00005148 | best=0.00004143

22:35:26 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.083475 | val_mse_raw=0.00004735 | best=0.00004143

22:35:30 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.072111 | val_mse_raw=0.00005250 | best=0.00004143

22:35:33 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.066330 | val_mse_raw=0.00005240 | best=0.00004143

22:35:37 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.059547 | val_mse_raw=0.00005205 | best=0.00004143

22:35:40 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.062179 | val_mse_raw=0.00005791 | best=0.00004143

22:35:43 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.053474 | val_mse_raw=0.00005385 | best=0.00004143

22:35:47 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.041918 | val_mse_raw=0.00005277 | best=0.00004143

22:35:51 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.035021 | val_mse_raw=0.00005810 | best=0.00004143

22:35:54 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.036616 | val_mse_raw=0.00005449 | best=0.00004143
22:35:54 | INFO    | train_LSTM_baseline | Early stopping at epoch 22

22:35:57 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.116123 | val_mse_raw=0.00006695 | best=0.00006695

22:36:01 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.252187 | val_mse_raw=0.00006732 | best=0.00006695

22:36:05 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.212205 | val_mse_raw=0.06954917 | best=0.00006695

22:36:08 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.117965 | val_mse_raw=0.00004944 | best=0.00004944

22:36:12 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.102212 | val_mse_raw=0.00005003 | best=0.00004944

22:36:15 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.105595 | val_mse_raw=0.00004720 | best=0.00004720

22:36:19 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.088787 | val_mse_raw=0.00004564 | best=0.00004564

22:36:22 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.086818 | val_mse_raw=0.00004804 | best=0.00004564

22:36:25 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.091463 | val_mse_raw=0.00004697 | best=0.00004564

22:36:29 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.079412 | val_mse_raw=0.00004824 | best=0.00004564

22:36:33 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.068743 | val_mse_raw=0.00005112 | best=0.00004564

22:36:36 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.066397 | val_mse_raw=0.00005399 | best=0.00004564

22:36:40 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.076733 | val_mse_raw=0.00554837 | best=0.00004564

22:36:43 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.066814 | val_mse_raw=0.00004613 | best=0.00004564

22:36:47 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.066537 | val_mse_raw=0.00005023 | best=0.00004564

22:36:50 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.055166 | val_mse_raw=0.00004644 | best=0.00004564

22:36:54 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.046620 | val_mse_raw=0.00005221 | best=0.00004564
22:36:54 | INFO    | train_LSTM_baseline | Early stopping at epoch 17

22:36:57 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.885535 | val_mse_raw=0.00006627 | best=0.00006627

22:37:01 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.215109 | val_mse_raw=0.00005940 | best=0.00005940

22:37:04 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.135339 | val_mse_raw=0.01394894 | best=0.00005940

22:37:08 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.117354 | val_mse_raw=0.00005224 | best=0.00005224

22:37:11 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.105599 | val_mse_raw=0.00004577 | best=0.00004577

22:37:15 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.112445 | val_mse_raw=0.00004837 | best=0.00004577

22:37:18 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.096708 | val_mse_raw=0.00004580 | best=0.00004577

22:37:22 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.099993 | val_mse_raw=0.00004720 | best=0.00004577

22:37:25 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.099229 | val_mse_raw=0.00005067 | best=0.00004577

22:37:29 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.097129 | val_mse_raw=0.00004638 | best=0.00004577

22:37:32 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.088860 | val_mse_raw=0.00004846 | best=0.00004577

22:37:36 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.090310 | val_mse_raw=0.00005175 | best=0.00004577

22:37:39 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.087884 | val_mse_raw=0.00004711 | best=0.00004577

22:37:43 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.084598 | val_mse_raw=0.00004733 | best=0.00004577

22:37:46 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.084553 | val_mse_raw=0.00005003 | best=0.00004577
22:37:46 | INFO    | train_LSTM_baseline | Early stopping at epoch 15

22:37:50 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.395702 | val_mse_raw=0.00006519 | best=0.00006519

22:37:53 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.170443 | val_mse_raw=0.00005238 | best=0.00005238

22:37:57 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.108215 | val_mse_raw=0.00005015 | best=0.00005015

22:38:00 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.099009 | val_mse_raw=0.00004929 | best=0.00004929

22:38:04 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.107249 | val_mse_raw=0.00004543 | best=0.00004543

22:38:07 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.104552 | val_mse_raw=0.00005092 | best=0.00004543

22:38:11 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.093467 | val_mse_raw=0.00005175 | best=0.00004543

22:38:14 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.094885 | val_mse_raw=0.00005310 | best=0.00004543

22:38:18 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.090607 | val_mse_raw=0.00005790 | best=0.00004543

22:38:21 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.086077 | val_mse_raw=0.00005254 | best=0.00004543

22:38:25 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.083533 | val_mse_raw=0.00005032 | best=0.00004543

22:38:29 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.076245 | val_mse_raw=0.00006344 | best=0.00004543

22:38:32 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.078044 | val_mse_raw=0.00005309 | best=0.00004543

22:38:36 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.066517 | val_mse_raw=0.00005678 | best=0.00004543

22:38:39 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.060845 | val_mse_raw=0.00005657 | best=0.00004543
22:38:39 | INFO    | train_LSTM_baseline | Early stopping at epoch 15

22:38:43 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.688806 | val_mse_raw=0.00006947 | best=0.00006947

22:38:46 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.256157 | val_mse_raw=0.00006609 | best=0.00006609

22:38:50 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.259121 | val_mse_raw=0.00006610 | best=0.00006609

22:38:53 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.250378 | val_mse_raw=0.00006617 | best=0.00006609

22:38:57 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.257215 | val_mse_raw=0.00006889 | best=0.00006609

22:39:00 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.193527 | val_mse_raw=0.00005140 | best=0.00005140

22:39:04 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.119414 | val_mse_raw=0.00004397 | best=0.00004397

22:39:07 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.105387 | val_mse_raw=0.00004929 | best=0.00004397

22:39:11 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.109901 | val_mse_raw=0.00004657 | best=0.00004397

22:39:15 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.097044 | val_mse_raw=0.00004575 | best=0.00004397

22:39:18 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.089312 | val_mse_raw=0.00004022 | best=0.00004022

22:39:21 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.104859 | val_mse_raw=0.00004199 | best=0.00004022

22:39:25 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.092171 | val_mse_raw=0.00004289 | best=0.00004022

22:39:28 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.086312 | val_mse_raw=0.00004803 | best=0.00004022

22:39:32 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.079346 | val_mse_raw=0.00004938 | best=0.00004022

22:39:35 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.073330 | val_mse_raw=0.00005113 | best=0.00004022

22:39:39 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.069642 | val_mse_raw=0.00005141 | best=0.00004022

22:39:42 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.060291 | val_mse_raw=0.00004731 | best=0.00004022

22:39:46 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.053362 | val_mse_raw=0.00005640 | best=0.00004022

22:39:49 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.048911 | val_mse_raw=0.00005497 | best=0.00004022

22:39:53 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.049696 | val_mse_raw=0.00006001 | best=0.00004022
22:39:53 | INFO    | train_LSTM_baseline | Early stopping at epoch 21

22:39:54 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.392454 | val_mse_raw=0.00006655 | best=0.00006655

22:39:56 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.251415 | val_mse_raw=0.00006634 | best=0.00006634

22:39:57 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.250090 | val_mse_raw=0.00006633 | best=0.00006633

22:39:59 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.251591 | val_mse_raw=0.00006798 | best=0.00006633

22:40:00 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.253153 | val_mse_raw=0.00006662 | best=0.00006633

22:40:02 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.248388 | val_mse_raw=0.00006619 | best=0.00006619

22:40:03 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.250220 | val_mse_raw=0.00006626 | best=0.00006619

22:40:05 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.250019 | val_mse_raw=0.00006626 | best=0.00006619

22:40:06 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.252562 | val_mse_raw=0.00006649 | best=0.00006619

22:40:08 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.242549 | val_mse_raw=0.00006333 | best=0.00006333

22:40:09 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.163641 | val_mse_raw=0.00004957 | best=0.00004957

22:40:11 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.126094 | val_mse_raw=0.00004875 | best=0.00004875

22:40:12 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.114062 | val_mse_raw=0.00004704 | best=0.00004704

22:40:13 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.106350 | val_mse_raw=0.00004910 | best=0.00004704

22:40:15 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.097395 | val_mse_raw=0.00004651 | best=0.00004651

22:40:17 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.096063 | val_mse_raw=0.00004591 | best=0.00004591

22:40:18 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.091477 | val_mse_raw=0.00004679 | best=0.00004591

22:40:19 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.091123 | val_mse_raw=0.00004756 | best=0.00004591

22:40:21 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.085233 | val_mse_raw=0.00004705 | best=0.00004591

22:40:22 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.084259 | val_mse_raw=0.00004375 | best=0.00004375

22:40:24 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.083477 | val_mse_raw=0.00004708 | best=0.00004375

22:40:25 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.075945 | val_mse_raw=0.00004578 | best=0.00004375

22:40:27 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.073055 | val_mse_raw=0.00004667 | best=0.00004375

22:40:28 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.075080 | val_mse_raw=0.00005035 | best=0.00004375

22:40:29 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.068930 | val_mse_raw=0.00005252 | best=0.00004375

22:40:31 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.065333 | val_mse_raw=0.00005416 | best=0.00004375

22:40:32 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.061662 | val_mse_raw=0.00005101 | best=0.00004375

22:40:34 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.058764 | val_mse_raw=0.00005013 | best=0.00004375

22:40:35 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.056052 | val_mse_raw=0.00006033 | best=0.00004375

22:40:36 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.049955 | val_mse_raw=0.00006097 | best=0.00004375
22:40:36 | INFO    | train_LSTM_baseline | Early stopping at epoch 30

22:40:37 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=3.433159 | val_mse_raw=0.00006754 | best=0.00006754

22:40:38 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.249440 | val_mse_raw=0.00006632 | best=0.00006632

22:40:39 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.248028 | val_mse_raw=0.00006682 | best=0.00006632

22:40:40 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.249542 | val_mse_raw=0.00006609 | best=0.00006609

22:40:41 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.250612 | val_mse_raw=0.00006660 | best=0.00006609

22:40:42 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.249479 | val_mse_raw=0.00006618 | best=0.00006609

22:40:43 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.251576 | val_mse_raw=0.00006676 | best=0.00006609

22:40:43 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.251690 | val_mse_raw=0.00006653 | best=0.00006609

22:40:44 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.247940 | val_mse_raw=0.00006601 | best=0.00006601

22:40:45 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.241619 | val_mse_raw=0.00006357 | best=0.00006357

22:40:46 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.193525 | val_mse_raw=0.00005818 | best=0.00005818

22:40:47 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.138509 | val_mse_raw=0.00005478 | best=0.00005478

22:40:48 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.121056 | val_mse_raw=0.00005156 | best=0.00005156

22:40:48 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.110177 | val_mse_raw=0.00004630 | best=0.00004630

22:40:49 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.103299 | val_mse_raw=0.00004811 | best=0.00004630

22:40:50 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.108078 | val_mse_raw=0.00004859 | best=0.00004630

22:40:51 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.109265 | val_mse_raw=0.00004428 | best=0.00004428

22:40:52 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.091823 | val_mse_raw=0.00004383 | best=0.00004383

22:40:53 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.089925 | val_mse_raw=0.00004620 | best=0.00004383

22:40:54 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.094863 | val_mse_raw=0.00004277 | best=0.00004277

22:40:55 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.087015 | val_mse_raw=0.00004306 | best=0.00004277

22:40:56 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.083615 | val_mse_raw=0.00004268 | best=0.00004268

22:40:56 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.082734 | val_mse_raw=0.00004284 | best=0.00004268

22:40:57 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.081857 | val_mse_raw=0.00004280 | best=0.00004268

22:40:58 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.080765 | val_mse_raw=0.00004336 | best=0.00004268

22:40:59 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.082428 | val_mse_raw=0.00004120 | best=0.00004120

22:41:00 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.078497 | val_mse_raw=0.00004732 | best=0.00004120

22:41:01 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.072781 | val_mse_raw=0.00004808 | best=0.00004120

22:41:02 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.073405 | val_mse_raw=0.00004735 | best=0.00004120

22:41:02 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.073728 | val_mse_raw=0.00004696 | best=0.00004120

22:41:03 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.065357 | val_mse_raw=0.00004721 | best=0.00004120

22:41:04 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.062843 | val_mse_raw=0.00004913 | best=0.00004120

22:41:05 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.064442 | val_mse_raw=0.00004971 | best=0.00004120

22:41:06 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.058317 | val_mse_raw=0.00005043 | best=0.00004120

22:41:07 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.056090 | val_mse_raw=0.00005009 | best=0.00004120

22:41:08 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.054648 | val_mse_raw=0.00005104 | best=0.00004120
22:41:08 | INFO    | train_LSTM_baseline | Early stopping at epoch 36
22:41:08 | INFO    | train_LSTM_baseline | Best val MSE (raw scale): 0.00004022
22:41:08 | INFO    | train_LSTM_baseline | Best params: {'hidden_size': 128, 'n_layers': 3, 'dropout': 0.3883512544126061, 'lr': 0.003939313238054466, 'batch_size': 64, 'seq_len': 42}

22:41:11 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.688806 | val_mse_raw=0.00006947 | best=0.00006947

22:41:15 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.256157 | val_mse_raw=0.00006609 | best=0.00006609

22:41:18 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.259121 | val_mse_raw=0.00006610 | best=0.00006609

22:41:22 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.250378 | val_mse_raw=0.00006617 | best=0.00006609

22:41:25 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.257215 | val_mse_raw=0.00006889 | best=0.00006609

22:41:29 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.193527 | val_mse_raw=0.00005140 | best=0.00005140

22:41:32 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.119414 | val_mse_raw=0.00004397 | best=0.00004397

22:41:35 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.105387 | val_mse_raw=0.00004929 | best=0.00004397

22:41:39 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.109901 | val_mse_raw=0.00004657 | best=0.00004397

22:41:42 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.097044 | val_mse_raw=0.00004575 | best=0.00004397

22:41:46 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.089312 | val_mse_raw=0.00004022 | best=0.00004022

22:41:49 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.104859 | val_mse_raw=0.00004199 | best=0.00004022

22:41:53 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.092171 | val_mse_raw=0.00004289 | best=0.00004022

22:41:56 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.086312 | val_mse_raw=0.00004803 | best=0.00004022

22:41:59 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.079346 | val_mse_raw=0.00004938 | best=0.00004022

22:42:03 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.073330 | val_mse_raw=0.00005113 | best=0.00004022

22:42:06 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.069642 | val_mse_raw=0.00005141 | best=0.00004022

22:42:10 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.060291 | val_mse_raw=0.00004731 | best=0.00004022

22:42:13 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.053362 | val_mse_raw=0.00005640 | best=0.00004022

22:42:17 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.048911 | val_mse_raw=0.00005497 | best=0.00004022

22:42:20 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.049696 | val_mse_raw=0.00006001 | best=0.00004022
22:42:20 | INFO    | train_LSTM_baseline | Early stopping at epoch 21
22:42:20 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00004022

22:42:20 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.3356764611671679e-05, 'RMSE': 0.0036546906922012568, 'MAE': 0.0024708930868655443, 'n_test_windows': 1440}
22:42:20 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_seed42.pt
22:42:20 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_seed42_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 128,
    "n_layers": 3,
    "dropout": 0.3883512544126061,
    "lr": 0.003939313238054466,
    "batch_size": 64,
    "seq_len": 42
  },
  "best_val_mse_raw": 4.022329085273668e-05,
  "retrained_val_mse_raw": 4.022329085273668e-05,
  "test_metrics": {
    "MSE": 1.3356764611671679e-05,
    "RMSE": 0.0036546906922012568,
    "MAE": 0.0024708930868655443,
    "n_test_windows": 1440
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish"
  ],
  "target": "realized_vol_21d",
  "n_trials": 20,
  "seed": 42,
  "fixed_hparams_source": null
}

  [seed 42]  hparams JSON saved → hparams_lstm_baseline.json
================================================================================
[variant A  seed 43]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish --output-prefix lstm_baseline_seed43 --seed 43 --fixed-hparams /content/repo/models/hparams_lstm_baseline.json
--------------------------------------------------------------------------------

22:42:23 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish']
22:42:23 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:42:24 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:42:24 | INFO    | train_LSTM_baseline | n_features=7 | rows — train=3691 val=1089 test=1481
22:42:24 | INFO    | train_LSTM_baseline | Skipping Optuna — using fixed hparams from /content/repo/models/hparams_lstm_baseline.json
22:42:24 | INFO    | train_LSTM_baseline | Fixed params: {'hidden_size': 128, 'n_layers': 3, 'dropout': 0.3883512544126061, 'lr': 0.003939313238054466, 'batch_size': 64, 'seq_len': 42}

22:42:28 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.429130 | val_mse_raw=0.00006633 | best=0.00006633

22:42:31 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.250404 | val_mse_raw=0.00006614 | best=0.00006614

22:42:34 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.247901 | val_mse_raw=0.00006701 | best=0.00006614

22:42:38 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.194090 | val_mse_raw=0.00004732 | best=0.00004732

22:42:41 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.128162 | val_mse_raw=0.00005652 | best=0.00004732

22:42:45 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.133901 | val_mse_raw=0.00004881 | best=0.00004732

22:42:48 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.105631 | val_mse_raw=0.00004204 | best=0.00004204

22:42:52 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.103069 | val_mse_raw=0.00004204 | best=0.00004204

22:42:55 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.099234 | val_mse_raw=0.00004335 | best=0.00004204

22:42:58 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.103304 | val_mse_raw=0.00004093 | best=0.00004093

22:43:02 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.099086 | val_mse_raw=0.00004494 | best=0.00004093

22:43:05 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.094060 | val_mse_raw=0.00004804 | best=0.00004093

22:43:09 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.096635 | val_mse_raw=0.00004615 | best=0.00004093

22:43:12 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.086803 | val_mse_raw=0.00005148 | best=0.00004093

22:43:16 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.094003 | val_mse_raw=0.00005042 | best=0.00004093

22:43:19 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.113592 | val_mse_raw=0.00004706 | best=0.00004093

22:43:22 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.090179 | val_mse_raw=0.00004383 | best=0.00004093

22:43:26 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.086642 | val_mse_raw=0.00005001 | best=0.00004093

22:43:29 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.099199 | val_mse_raw=0.00004475 | best=0.00004093

22:43:33 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.075838 | val_mse_raw=0.00005059 | best=0.00004093
22:43:33 | INFO    | train_LSTM_baseline | Early stopping at epoch 20
22:43:33 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00004093

22:43:33 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.4950110198697075e-05, 'RMSE': 0.0038665372412651777, 'MAE': 0.002659979509189725, 'n_test_windows': 1440}
22:43:33 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_seed43.pt
22:43:33 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_seed43_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 128,
    "n_layers": 3,
    "dropout": 0.3883512544126061,
    "lr": 0.003939313238054466,
    "batch_size": 64,
    "seq_len": 42
  },
  "best_val_mse_raw": NaN,
  "retrained_val_mse_raw": 4.093378083780408e-05,
  "test_metrics": {
    "MSE": 1.4950110198697075e-05,
    "RMSE": 0.0038665372412651777,
    "MAE": 0.002659979509189725,
    "n_test_windows": 1440
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish"
  ],
  "target": "realized_vol_21d",
  "n_trials": 0,
  "seed": 43,
  "fixed_hparams_source": "/content/repo/models/hparams_lstm_baseline.json"
}

================================================================================
[variant A  seed 44]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish --output-prefix lstm_baseline_seed44 --seed 44 --fixed-hparams /content/repo/models/hparams_lstm_baseline.json
--------------------------------------------------------------------------------

22:43:36 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish']
22:43:36 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:43:36 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:43:36 | INFO    | train_LSTM_baseline | n_features=7 | rows — train=3691 val=1089 test=1481
22:43:36 | INFO    | train_LSTM_baseline | Skipping Optuna — using fixed hparams from /content/repo/models/hparams_lstm_baseline.json
22:43:36 | INFO    | train_LSTM_baseline | Fixed params: {'hidden_size': 128, 'n_layers': 3, 'dropout': 0.3883512544126061, 'lr': 0.003939313238054466, 'batch_size': 64, 'seq_len': 42}

22:43:40 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.463522 | val_mse_raw=0.00006685 | best=0.00006685

22:43:43 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.311437 | val_mse_raw=0.00006624 | best=0.00006624

22:43:46 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.242426 | val_mse_raw=0.00006622 | best=0.00006622

22:43:49 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.237303 | val_mse_raw=0.00006690 | best=0.00006622

22:43:52 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.243387 | val_mse_raw=0.00006623 | best=0.00006622

22:43:55 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.249506 | val_mse_raw=0.00006760 | best=0.00006622

22:43:57 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.242345 | val_mse_raw=0.00006779 | best=0.00006622

22:44:00 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.250100 | val_mse_raw=0.00006634 | best=0.00006622

22:44:03 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.250724 | val_mse_raw=0.00006981 | best=0.00006622

22:44:06 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.252211 | val_mse_raw=0.00006653 | best=0.00006622

22:44:09 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.252122 | val_mse_raw=0.00006902 | best=0.00006622

22:44:12 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.254147 | val_mse_raw=0.00006613 | best=0.00006613

22:44:15 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.252227 | val_mse_raw=0.00006698 | best=0.00006613

22:44:18 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.249959 | val_mse_raw=0.00006690 | best=0.00006613

22:44:21 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.217100 | val_mse_raw=0.00004796 | best=0.00004796

22:44:23 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.131766 | val_mse_raw=0.00005500 | best=0.00004796

22:44:26 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.123569 | val_mse_raw=0.00004311 | best=0.00004311

22:44:29 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.112298 | val_mse_raw=0.00004449 | best=0.00004311

22:44:32 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.113028 | val_mse_raw=0.00004948 | best=0.00004311

22:44:35 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.099656 | val_mse_raw=0.00004773 | best=0.00004311

22:44:38 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.106770 | val_mse_raw=0.00004705 | best=0.00004311

22:44:41 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.096803 | val_mse_raw=0.00004174 | best=0.00004174

22:44:44 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.099843 | val_mse_raw=0.00004240 | best=0.00004174

22:44:47 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.091809 | val_mse_raw=0.00004974 | best=0.00004174

22:44:50 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.103122 | val_mse_raw=0.00004188 | best=0.00004174

22:44:53 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.090092 | val_mse_raw=0.00004327 | best=0.00004174

22:44:55 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.086884 | val_mse_raw=0.00004276 | best=0.00004174

22:44:58 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.086986 | val_mse_raw=0.00004447 | best=0.00004174

22:45:01 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.085214 | val_mse_raw=0.00004561 | best=0.00004174

22:45:04 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.082429 | val_mse_raw=0.00004411 | best=0.00004174

22:45:07 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.078650 | val_mse_raw=0.00004578 | best=0.00004174

22:45:10 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.077858 | val_mse_raw=0.00004363 | best=0.00004174
22:45:10 | INFO    | train_LSTM_baseline | Early stopping at epoch 32
22:45:10 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00004174

22:45:10 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.8640415873960592e-05, 'RMSE': 0.004317454993724823, 'MAE': 0.0028140402864664793, 'n_test_windows': 1440}
22:45:10 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_seed44.pt
22:45:10 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_seed44_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 128,
    "n_layers": 3,
    "dropout": 0.3883512544126061,
    "lr": 0.003939313238054466,
    "batch_size": 64,
    "seq_len": 42
  },
  "best_val_mse_raw": NaN,
  "retrained_val_mse_raw": 4.17395458498504e-05,
  "test_metrics": {
    "MSE": 1.8640415873960592e-05,
    "RMSE": 0.004317454993724823,
    "MAE": 0.0028140402864664793,
    "n_test_windows": 1440
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish"
  ],
  "target": "realized_vol_21d",
  "n_trials": 0,
  "seed": 44,
  "fixed_hparams_source": "/content/repo/models/hparams_lstm_baseline.json"
}

================================================================================
[variant H  seed 42]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish p_volatile --output-prefix lstm_baseline_H_seed42 --seed 42
--------------------------------------------------------------------------------

22:45:13 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish', 'p_volatile']
22:45:13 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:45:14 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:45:14 | INFO    | train_LSTM_baseline | n_features=8 | rows — train=3690 val=1089 test=1481
22:45:14 | INFO    | train_LSTM_baseline | Starting Optuna study with 20 trials…

22:45:15 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.806296 | val_mse_raw=0.00005264 | best=0.00005264

22:45:15 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.132065 | val_mse_raw=0.00004475 | best=0.00004475

22:45:15 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.115715 | val_mse_raw=0.00004097 | best=0.00004097

22:45:15 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.106741 | val_mse_raw=0.00004107 | best=0.00004097

22:45:16 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.102917 | val_mse_raw=0.00004270 | best=0.00004097

22:45:16 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.099614 | val_mse_raw=0.00004247 | best=0.00004097

22:45:16 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.098394 | val_mse_raw=0.00004293 | best=0.00004097

22:45:16 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.097528 | val_mse_raw=0.00004299 | best=0.00004097

22:45:17 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.097471 | val_mse_raw=0.00004369 | best=0.00004097

22:45:17 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.096924 | val_mse_raw=0.00004415 | best=0.00004097

22:45:17 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.097830 | val_mse_raw=0.00004306 | best=0.00004097

22:45:18 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.095031 | val_mse_raw=0.00004315 | best=0.00004097

22:45:18 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.094737 | val_mse_raw=0.00004192 | best=0.00004097
22:45:18 | INFO    | train_LSTM_baseline | Early stopping at epoch 13

22:45:18 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=17.471048 | val_mse_raw=0.01079077 | best=0.01079077

22:45:19 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=1.329259 | val_mse_raw=0.00006497 | best=0.00006497

22:45:19 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.255972 | val_mse_raw=0.00006165 | best=0.00006165

22:45:20 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.214803 | val_mse_raw=0.00005903 | best=0.00005903

22:45:20 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.199635 | val_mse_raw=0.00005584 | best=0.00005584

22:45:21 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.183060 | val_mse_raw=0.00005238 | best=0.00005238

22:45:21 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.162623 | val_mse_raw=0.00005009 | best=0.00005009

22:45:22 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.138551 | val_mse_raw=0.00004870 | best=0.00004870

22:45:22 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.122170 | val_mse_raw=0.00004729 | best=0.00004729

22:45:23 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.111794 | val_mse_raw=0.00004728 | best=0.00004728

22:45:23 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.106143 | val_mse_raw=0.00004780 | best=0.00004728

22:45:24 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.105111 | val_mse_raw=0.00004590 | best=0.00004590

22:45:25 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.101506 | val_mse_raw=0.00004542 | best=0.00004542

22:45:25 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.099557 | val_mse_raw=0.00004601 | best=0.00004542

22:45:26 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.097122 | val_mse_raw=0.00004628 | best=0.00004542

22:45:26 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.097645 | val_mse_raw=0.00004660 | best=0.00004542

22:45:27 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.096303 | val_mse_raw=0.00004696 | best=0.00004542

22:45:27 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.094517 | val_mse_raw=0.00004899 | best=0.00004542

22:45:28 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.092246 | val_mse_raw=0.00005051 | best=0.00004542

22:45:28 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.092406 | val_mse_raw=0.00004968 | best=0.00004542

22:45:29 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.090402 | val_mse_raw=0.00004975 | best=0.00004542

22:45:29 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.089374 | val_mse_raw=0.00005117 | best=0.00004542

22:45:30 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.088448 | val_mse_raw=0.00005073 | best=0.00004542
22:45:30 | INFO    | train_LSTM_baseline | Early stopping at epoch 23

22:45:32 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=0.732963 | val_mse_raw=0.00006498 | best=0.00006498

22:45:35 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.146412 | val_mse_raw=0.00004483 | best=0.00004483

22:45:37 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.111227 | val_mse_raw=0.00004883 | best=0.00004483

22:45:40 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.132459 | val_mse_raw=0.00004477 | best=0.00004477

22:45:43 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.098099 | val_mse_raw=0.00004989 | best=0.00004477

22:45:45 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.109157 | val_mse_raw=0.00004429 | best=0.00004429

22:45:48 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.094413 | val_mse_raw=0.00004639 | best=0.00004429

22:45:50 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.094050 | val_mse_raw=0.00004707 | best=0.00004429

22:45:53 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.104720 | val_mse_raw=0.00004995 | best=0.00004429

22:45:55 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.099583 | val_mse_raw=0.00005111 | best=0.00004429

22:45:58 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.095499 | val_mse_raw=0.00004562 | best=0.00004429

22:46:00 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.086840 | val_mse_raw=0.00005031 | best=0.00004429

22:46:03 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.088506 | val_mse_raw=0.00005029 | best=0.00004429

22:46:06 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.078441 | val_mse_raw=0.00005615 | best=0.00004429

22:46:08 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.078025 | val_mse_raw=0.00005114 | best=0.00004429

22:46:11 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.104797 | val_mse_raw=0.00005001 | best=0.00004429
22:46:11 | INFO    | train_LSTM_baseline | Early stopping at epoch 16

22:46:12 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=9.332189 | val_mse_raw=0.00006166 | best=0.00006166

22:46:13 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.204949 | val_mse_raw=0.00005572 | best=0.00005572

22:46:14 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.152455 | val_mse_raw=0.00004988 | best=0.00004988

22:46:15 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.121596 | val_mse_raw=0.00004814 | best=0.00004814

22:46:16 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.112501 | val_mse_raw=0.00004684 | best=0.00004684

22:46:17 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.107525 | val_mse_raw=0.00004594 | best=0.00004594

22:46:18 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.103835 | val_mse_raw=0.00004558 | best=0.00004558

22:46:19 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.101459 | val_mse_raw=0.00004536 | best=0.00004536

22:46:20 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.099743 | val_mse_raw=0.00004583 | best=0.00004536

22:46:21 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.098640 | val_mse_raw=0.00004427 | best=0.00004427

22:46:22 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098925 | val_mse_raw=0.00004540 | best=0.00004427

22:46:23 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.099804 | val_mse_raw=0.00004554 | best=0.00004427

22:46:24 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.096405 | val_mse_raw=0.00004427 | best=0.00004427

22:46:25 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.096944 | val_mse_raw=0.00004468 | best=0.00004427

22:46:26 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.095454 | val_mse_raw=0.00004434 | best=0.00004427

22:46:27 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.095493 | val_mse_raw=0.00004400 | best=0.00004400

22:46:28 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.095400 | val_mse_raw=0.00004382 | best=0.00004382

22:46:29 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.095166 | val_mse_raw=0.00004347 | best=0.00004347

22:46:30 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.095413 | val_mse_raw=0.00004382 | best=0.00004347

22:46:32 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.093760 | val_mse_raw=0.00004406 | best=0.00004347

22:46:33 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.094091 | val_mse_raw=0.00004364 | best=0.00004347

22:46:34 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.094172 | val_mse_raw=0.00004425 | best=0.00004347

22:46:35 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.093014 | val_mse_raw=0.00004394 | best=0.00004347

22:46:36 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.092407 | val_mse_raw=0.00004448 | best=0.00004347

22:46:37 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.093295 | val_mse_raw=0.00004427 | best=0.00004347

22:46:38 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.091376 | val_mse_raw=0.00004353 | best=0.00004347

22:46:39 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.091313 | val_mse_raw=0.00004349 | best=0.00004347

22:46:40 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.091702 | val_mse_raw=0.00004329 | best=0.00004329

22:46:41 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.091481 | val_mse_raw=0.00004443 | best=0.00004329

22:46:42 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.091344 | val_mse_raw=0.00004424 | best=0.00004329

22:46:43 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.088965 | val_mse_raw=0.00004393 | best=0.00004329

22:46:44 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.088332 | val_mse_raw=0.00004415 | best=0.00004329

22:46:45 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.088296 | val_mse_raw=0.00004432 | best=0.00004329

22:46:46 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.087528 | val_mse_raw=0.00004552 | best=0.00004329

22:46:47 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.088354 | val_mse_raw=0.00004578 | best=0.00004329

22:46:48 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.087002 | val_mse_raw=0.00004447 | best=0.00004329

22:46:49 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.085624 | val_mse_raw=0.00004540 | best=0.00004329

22:46:50 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.085333 | val_mse_raw=0.00004448 | best=0.00004329
22:46:50 | INFO    | train_LSTM_baseline | Early stopping at epoch 38
22:46:51 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=21.066098 | val_mse_raw=0.60134679 | best=0.60134679

22:46:51 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=19.735604 | val_mse_raw=0.34625983 | best=0.34625983
22:46:51 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=15.610563 | val_mse_raw=0.06195496 | best=0.06195496

22:46:51 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=7.664563 | val_mse_raw=0.00582609 | best=0.00582609
22:46:51 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=2.660198 | val_mse_raw=0.00048099 | best=0.00048099

22:46:51 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.930729 | val_mse_raw=0.00011741 | best=0.00011741
22:46:51 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.415248 | val_mse_raw=0.00006529 | best=0.00006529

22:46:52 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.254091 | val_mse_raw=0.00005394 | best=0.00005394
22:46:52 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.201513 | val_mse_raw=0.00005144 | best=0.00005144

22:46:52 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.181888 | val_mse_raw=0.00005162 | best=0.00005144
22:46:52 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.172253 | val_mse_raw=0.00005355 | best=0.00005144

22:46:52 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.166476 | val_mse_raw=0.00005354 | best=0.00005144
22:46:52 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.161761 | val_mse_raw=0.00005262 | best=0.00005144

22:46:52 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.157176 | val_mse_raw=0.00005143 | best=0.00005143
22:46:52 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.152048 | val_mse_raw=0.00004890 | best=0.00004890

22:46:53 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.146464 | val_mse_raw=0.00004757 | best=0.00004757
22:46:53 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.140871 | val_mse_raw=0.00004610 | best=0.00004610

22:46:53 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.135141 | val_mse_raw=0.00004496 | best=0.00004496
22:46:53 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.129491 | val_mse_raw=0.00004429 | best=0.00004429

22:46:53 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.123979 | val_mse_raw=0.00004331 | best=0.00004331
22:46:53 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.118806 | val_mse_raw=0.00004286 | best=0.00004286

22:46:53 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.114216 | val_mse_raw=0.00004242 | best=0.00004242
22:46:54 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.110731 | val_mse_raw=0.00004228 | best=0.00004228

22:46:54 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.108186 | val_mse_raw=0.00004237 | best=0.00004228
22:46:54 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.106656 | val_mse_raw=0.00004245 | best=0.00004228

22:46:54 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.105530 | val_mse_raw=0.00004263 | best=0.00004228
22:46:54 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.104649 | val_mse_raw=0.00004271 | best=0.00004228

22:46:54 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.103910 | val_mse_raw=0.00004283 | best=0.00004228
22:46:54 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.103266 | val_mse_raw=0.00004307 | best=0.00004228

22:46:54 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.102731 | val_mse_raw=0.00004306 | best=0.00004228
22:46:55 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.102327 | val_mse_raw=0.00004328 | best=0.00004228

22:46:55 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.101781 | val_mse_raw=0.00004302 | best=0.00004228
22:46:55 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.101448 | val_mse_raw=0.00004317 | best=0.00004228
22:46:55 | INFO    | train_LSTM_baseline | Early stopping at epoch 33

22:46:56 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=14.262641 | val_mse_raw=0.00005444 | best=0.00005444

22:46:57 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.144099 | val_mse_raw=0.00005051 | best=0.00005051

22:46:59 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.125695 | val_mse_raw=0.00004957 | best=0.00004957

22:47:00 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.118052 | val_mse_raw=0.00004858 | best=0.00004858

22:47:01 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.112372 | val_mse_raw=0.00004762 | best=0.00004762

22:47:03 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.107615 | val_mse_raw=0.00004705 | best=0.00004705

22:47:04 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.103541 | val_mse_raw=0.00004602 | best=0.00004602

22:47:05 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.101496 | val_mse_raw=0.00004647 | best=0.00004602

22:47:06 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.099855 | val_mse_raw=0.00004619 | best=0.00004602

22:47:08 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.098299 | val_mse_raw=0.00004498 | best=0.00004498

22:47:09 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.097570 | val_mse_raw=0.00004531 | best=0.00004498

22:47:10 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.097558 | val_mse_raw=0.00004575 | best=0.00004498

22:47:11 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.096189 | val_mse_raw=0.00004462 | best=0.00004462

22:47:13 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.095505 | val_mse_raw=0.00004489 | best=0.00004462

22:47:14 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.095239 | val_mse_raw=0.00004429 | best=0.00004429

22:47:15 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.094929 | val_mse_raw=0.00004437 | best=0.00004429

22:47:16 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.094720 | val_mse_raw=0.00004379 | best=0.00004379

22:47:18 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.095565 | val_mse_raw=0.00004347 | best=0.00004347

22:47:19 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.094373 | val_mse_raw=0.00004361 | best=0.00004347

22:47:20 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.094132 | val_mse_raw=0.00004483 | best=0.00004347

22:47:21 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.094471 | val_mse_raw=0.00004383 | best=0.00004347

22:47:23 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.094603 | val_mse_raw=0.00004469 | best=0.00004347

22:47:24 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.094299 | val_mse_raw=0.00004380 | best=0.00004347

22:47:25 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.092925 | val_mse_raw=0.00004426 | best=0.00004347

22:47:27 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.092862 | val_mse_raw=0.00004428 | best=0.00004347

22:47:28 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.092873 | val_mse_raw=0.00004291 | best=0.00004291

22:47:29 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.092773 | val_mse_raw=0.00004459 | best=0.00004291

22:47:30 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.092933 | val_mse_raw=0.00004337 | best=0.00004291

22:47:32 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.092925 | val_mse_raw=0.00004460 | best=0.00004291

22:47:33 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.093294 | val_mse_raw=0.00004441 | best=0.00004291

22:47:34 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.091981 | val_mse_raw=0.00004339 | best=0.00004291

22:47:35 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.092747 | val_mse_raw=0.00004423 | best=0.00004291

22:47:37 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.091915 | val_mse_raw=0.00004415 | best=0.00004291

22:47:38 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.091278 | val_mse_raw=0.00004431 | best=0.00004291

22:47:39 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.090992 | val_mse_raw=0.00004444 | best=0.00004291

22:47:41 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.092410 | val_mse_raw=0.00004446 | best=0.00004291
22:47:41 | INFO    | train_LSTM_baseline | Early stopping at epoch 36

22:47:41 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.961840 | val_mse_raw=0.19441193 | best=0.19441193

22:47:41 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=3.571292 | val_mse_raw=0.00006675 | best=0.00006675

22:47:42 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.236828 | val_mse_raw=0.00005419 | best=0.00005419

22:47:42 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.174189 | val_mse_raw=0.00004804 | best=0.00004804

22:47:42 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.141232 | val_mse_raw=0.00004498 | best=0.00004498

22:47:43 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.123554 | val_mse_raw=0.00004866 | best=0.00004498

22:47:43 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.117777 | val_mse_raw=0.00004932 | best=0.00004498

22:47:43 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.113861 | val_mse_raw=0.00004831 | best=0.00004498

22:47:44 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.108735 | val_mse_raw=0.00004700 | best=0.00004498

22:47:44 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.106542 | val_mse_raw=0.00004585 | best=0.00004498

22:47:44 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.104513 | val_mse_raw=0.00004508 | best=0.00004498

22:47:45 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.104169 | val_mse_raw=0.00004425 | best=0.00004425

22:47:45 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.102617 | val_mse_raw=0.00004363 | best=0.00004363

22:47:45 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.101314 | val_mse_raw=0.00004348 | best=0.00004348

22:47:46 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.101664 | val_mse_raw=0.00004270 | best=0.00004270

22:47:46 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.100059 | val_mse_raw=0.00004277 | best=0.00004270

22:47:47 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.099179 | val_mse_raw=0.00004235 | best=0.00004235

22:47:47 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.098924 | val_mse_raw=0.00004251 | best=0.00004235

22:47:47 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.098438 | val_mse_raw=0.00004246 | best=0.00004235

22:47:48 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.097378 | val_mse_raw=0.00004241 | best=0.00004235

22:47:48 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.096498 | val_mse_raw=0.00004253 | best=0.00004235

22:47:48 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.095849 | val_mse_raw=0.00004222 | best=0.00004222

22:47:49 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.095337 | val_mse_raw=0.00004196 | best=0.00004196

22:47:49 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.095914 | val_mse_raw=0.00004185 | best=0.00004185

22:47:50 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.095387 | val_mse_raw=0.00004184 | best=0.00004184

22:47:50 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.094279 | val_mse_raw=0.00004221 | best=0.00004184

22:47:50 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.093646 | val_mse_raw=0.00004185 | best=0.00004184

22:47:51 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.094437 | val_mse_raw=0.00004261 | best=0.00004184

22:47:51 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.094860 | val_mse_raw=0.00004243 | best=0.00004184

22:47:51 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.093601 | val_mse_raw=0.00004191 | best=0.00004184

22:47:52 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.092681 | val_mse_raw=0.00004212 | best=0.00004184

22:47:52 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.092276 | val_mse_raw=0.00004269 | best=0.00004184

22:47:53 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.092028 | val_mse_raw=0.00004207 | best=0.00004184

22:47:53 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.091509 | val_mse_raw=0.00004234 | best=0.00004184

22:47:53 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.090831 | val_mse_raw=0.00004275 | best=0.00004184
22:47:53 | INFO    | train_LSTM_baseline | Early stopping at epoch 35

22:47:54 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=22.689832 | val_mse_raw=0.92803663 | best=0.92803663

22:47:54 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=22.199801 | val_mse_raw=0.81321621 | best=0.81321621

22:47:54 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=21.597319 | val_mse_raw=0.67385000 | best=0.67385000

22:47:55 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=20.651632 | val_mse_raw=0.46419537 | best=0.46419537

22:47:55 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=17.929345 | val_mse_raw=0.10652896 | best=0.10652896

22:47:55 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=8.408419 | val_mse_raw=0.01768700 | best=0.01768700

22:47:56 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=2.732886 | val_mse_raw=0.00178336 | best=0.00178336

22:47:56 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=1.050936 | val_mse_raw=0.00029411 | best=0.00029411

22:47:56 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.474955 | val_mse_raw=0.00010736 | best=0.00010736

22:47:57 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.280109 | val_mse_raw=0.00007210 | best=0.00007210

22:47:57 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.214078 | val_mse_raw=0.00006391 | best=0.00006391

22:47:57 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.190817 | val_mse_raw=0.00006279 | best=0.00006279

22:47:58 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.180347 | val_mse_raw=0.00006358 | best=0.00006279

22:47:58 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.174378 | val_mse_raw=0.00006723 | best=0.00006279

22:47:58 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.169943 | val_mse_raw=0.00006972 | best=0.00006279

22:47:59 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.165882 | val_mse_raw=0.00007196 | best=0.00006279

22:47:59 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.162007 | val_mse_raw=0.00007449 | best=0.00006279

22:47:59 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.158163 | val_mse_raw=0.00007626 | best=0.00006279

22:47:59 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.154426 | val_mse_raw=0.00007705 | best=0.00006279

22:48:00 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.150735 | val_mse_raw=0.00007740 | best=0.00006279

22:48:00 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.147181 | val_mse_raw=0.00007698 | best=0.00006279

22:48:01 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.143786 | val_mse_raw=0.00007553 | best=0.00006279
22:48:01 | INFO    | train_LSTM_baseline | Early stopping at epoch 22

22:48:01 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.459897 | val_mse_raw=0.34590766 | best=0.34590766

22:48:01 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=10.724081 | val_mse_raw=0.00485214 | best=0.00485214

22:48:02 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=1.790106 | val_mse_raw=0.00016662 | best=0.00016662

22:48:02 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.452792 | val_mse_raw=0.00006388 | best=0.00006388

22:48:02 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.228037 | val_mse_raw=0.00005504 | best=0.00005504

22:48:02 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.182666 | val_mse_raw=0.00005613 | best=0.00005504

22:48:03 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.166478 | val_mse_raw=0.00005419 | best=0.00005419

22:48:03 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.151972 | val_mse_raw=0.00004874 | best=0.00004874

22:48:03 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.132938 | val_mse_raw=0.00004516 | best=0.00004516

22:48:04 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.116579 | val_mse_raw=0.00004300 | best=0.00004300

22:48:04 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.109506 | val_mse_raw=0.00004344 | best=0.00004300

22:48:04 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.107512 | val_mse_raw=0.00004326 | best=0.00004300

22:48:04 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.105859 | val_mse_raw=0.00004337 | best=0.00004300

22:48:05 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.104262 | val_mse_raw=0.00004325 | best=0.00004300

22:48:05 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.103372 | val_mse_raw=0.00004313 | best=0.00004300

22:48:05 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.102491 | val_mse_raw=0.00004327 | best=0.00004300

22:48:06 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.101690 | val_mse_raw=0.00004319 | best=0.00004300

22:48:06 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.101107 | val_mse_raw=0.00004356 | best=0.00004300

22:48:06 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.100567 | val_mse_raw=0.00004315 | best=0.00004300

22:48:06 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.099909 | val_mse_raw=0.00004349 | best=0.00004300
22:48:06 | INFO    | train_LSTM_baseline | Early stopping at epoch 20

22:48:07 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=19.933492 | val_mse_raw=0.37210432 | best=0.37210432

22:48:08 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=12.869560 | val_mse_raw=0.00247707 | best=0.00247707

22:48:09 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=1.368390 | val_mse_raw=0.00006430 | best=0.00006430

22:48:09 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.219724 | val_mse_raw=0.00005746 | best=0.00005746

22:48:10 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.191891 | val_mse_raw=0.00005443 | best=0.00005443

22:48:11 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.169893 | val_mse_raw=0.00005404 | best=0.00005404

22:48:12 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.157605 | val_mse_raw=0.00005187 | best=0.00005187

22:48:13 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.141327 | val_mse_raw=0.00004964 | best=0.00004964

22:48:14 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.126268 | val_mse_raw=0.00004820 | best=0.00004820

22:48:14 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.116429 | val_mse_raw=0.00004775 | best=0.00004775

22:48:15 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.110871 | val_mse_raw=0.00004737 | best=0.00004737

22:48:16 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.106531 | val_mse_raw=0.00004690 | best=0.00004690

22:48:17 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.104384 | val_mse_raw=0.00004730 | best=0.00004690

22:48:17 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.102543 | val_mse_raw=0.00004737 | best=0.00004690

22:48:18 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.099954 | val_mse_raw=0.00004762 | best=0.00004690

22:48:19 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.098574 | val_mse_raw=0.00004761 | best=0.00004690

22:48:20 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.096928 | val_mse_raw=0.00004796 | best=0.00004690

22:48:21 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.095568 | val_mse_raw=0.00004812 | best=0.00004690

22:48:21 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.094437 | val_mse_raw=0.00004844 | best=0.00004690

22:48:22 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.093308 | val_mse_raw=0.00004808 | best=0.00004690

22:48:23 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.092499 | val_mse_raw=0.00004844 | best=0.00004690

22:48:24 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.092037 | val_mse_raw=0.00004848 | best=0.00004690
22:48:24 | INFO    | train_LSTM_baseline | Early stopping at epoch 22

22:48:25 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.628631 | val_mse_raw=0.00006339 | best=0.00006339

22:48:26 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.225059 | val_mse_raw=0.00006172 | best=0.00006172

22:48:26 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.216289 | val_mse_raw=0.00006189 | best=0.00006172

22:48:27 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.237060 | val_mse_raw=0.00006494 | best=0.00006172

22:48:28 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.250565 | val_mse_raw=0.00006504 | best=0.00006172

22:48:29 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.250512 | val_mse_raw=0.00006556 | best=0.00006172

22:48:30 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.252663 | val_mse_raw=0.00006489 | best=0.00006172

22:48:31 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.251279 | val_mse_raw=0.00006653 | best=0.00006172

22:48:31 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.249280 | val_mse_raw=0.00006488 | best=0.00006172

22:48:32 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.258438 | val_mse_raw=0.00006489 | best=0.00006172

22:48:33 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.247577 | val_mse_raw=0.00006340 | best=0.00006172

22:48:34 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.212954 | val_mse_raw=0.00005881 | best=0.00005881

22:48:35 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.175944 | val_mse_raw=0.00005079 | best=0.00005079

22:48:36 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.143083 | val_mse_raw=0.00004904 | best=0.00004904

22:48:37 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.127804 | val_mse_raw=0.00004620 | best=0.00004620

22:48:38 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.127463 | val_mse_raw=0.00004507 | best=0.00004507

22:48:38 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.116459 | val_mse_raw=0.00004548 | best=0.00004507

22:48:39 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.113152 | val_mse_raw=0.00004657 | best=0.00004507

22:48:40 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.109176 | val_mse_raw=0.00004879 | best=0.00004507

22:48:41 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.108680 | val_mse_raw=0.00004796 | best=0.00004507

22:48:42 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.102748 | val_mse_raw=0.00004738 | best=0.00004507

22:48:43 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.097776 | val_mse_raw=0.00005227 | best=0.00004507

22:48:43 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.092335 | val_mse_raw=0.00005075 | best=0.00004507

22:48:44 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.096454 | val_mse_raw=0.00004914 | best=0.00004507

22:48:45 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.092019 | val_mse_raw=0.00004552 | best=0.00004507

22:48:46 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.090968 | val_mse_raw=0.00004581 | best=0.00004507
22:48:46 | INFO    | train_LSTM_baseline | Early stopping at epoch 26

22:48:46 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=6.772197 | val_mse_raw=0.00004996 | best=0.00004996

22:48:47 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.147619 | val_mse_raw=0.00005867 | best=0.00004996

22:48:47 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.114604 | val_mse_raw=0.00004625 | best=0.00004625

22:48:47 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.106630 | val_mse_raw=0.00004343 | best=0.00004343

22:48:47 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.102909 | val_mse_raw=0.00004145 | best=0.00004145

22:48:48 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.099946 | val_mse_raw=0.00004204 | best=0.00004145

22:48:48 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.098348 | val_mse_raw=0.00004198 | best=0.00004145

22:48:48 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.096090 | val_mse_raw=0.00004194 | best=0.00004145

22:48:49 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.095901 | val_mse_raw=0.00004252 | best=0.00004145

22:48:49 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.094961 | val_mse_raw=0.00004225 | best=0.00004145

22:48:49 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.094867 | val_mse_raw=0.00004275 | best=0.00004145

22:48:49 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.093157 | val_mse_raw=0.00004294 | best=0.00004145

22:48:50 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.092456 | val_mse_raw=0.00004320 | best=0.00004145

22:48:50 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.093821 | val_mse_raw=0.00004190 | best=0.00004145

22:48:50 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.091607 | val_mse_raw=0.00004225 | best=0.00004145
22:48:50 | INFO    | train_LSTM_baseline | Early stopping at epoch 15

22:48:51 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.783886 | val_mse_raw=0.00004463 | best=0.00004463

22:48:51 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.140802 | val_mse_raw=0.00004880 | best=0.00004463

22:48:51 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.116657 | val_mse_raw=0.00004288 | best=0.00004288

22:48:51 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.103007 | val_mse_raw=0.00004082 | best=0.00004082

22:48:52 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.100099 | val_mse_raw=0.00004105 | best=0.00004082

22:48:52 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.096966 | val_mse_raw=0.00004243 | best=0.00004082

22:48:52 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.096687 | val_mse_raw=0.00004261 | best=0.00004082

22:48:52 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.094822 | val_mse_raw=0.00004284 | best=0.00004082

22:48:53 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.094591 | val_mse_raw=0.00004412 | best=0.00004082

22:48:53 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.093394 | val_mse_raw=0.00004402 | best=0.00004082

22:48:53 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.093390 | val_mse_raw=0.00004334 | best=0.00004082

22:48:53 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.091218 | val_mse_raw=0.00004366 | best=0.00004082

22:48:54 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.092123 | val_mse_raw=0.00004304 | best=0.00004082

22:48:54 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.091523 | val_mse_raw=0.00004542 | best=0.00004082
22:48:54 | INFO    | train_LSTM_baseline | Early stopping at epoch 14

22:48:55 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.460754 | val_mse_raw=0.00006505 | best=0.00006505

22:48:55 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.247879 | val_mse_raw=0.00006496 | best=0.00006496

22:48:56 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.247667 | val_mse_raw=0.00006476 | best=0.00006476

22:48:57 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.244563 | val_mse_raw=0.00006371 | best=0.00006371

22:48:58 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.196754 | val_mse_raw=0.00005970 | best=0.00005970

22:48:59 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.154771 | val_mse_raw=0.00004956 | best=0.00004956

22:49:00 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.145330 | val_mse_raw=0.00004830 | best=0.00004830

22:49:01 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.134613 | val_mse_raw=0.00004856 | best=0.00004830

22:49:01 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.120254 | val_mse_raw=0.00004647 | best=0.00004647

22:49:02 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.122869 | val_mse_raw=0.00004725 | best=0.00004647

22:49:03 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.114307 | val_mse_raw=0.00005106 | best=0.00004647

22:49:04 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.131562 | val_mse_raw=0.00004963 | best=0.00004647

22:49:05 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.114014 | val_mse_raw=0.00004908 | best=0.00004647

22:49:06 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.108563 | val_mse_raw=0.00004831 | best=0.00004647

22:49:06 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.108146 | val_mse_raw=0.00004875 | best=0.00004647

22:49:07 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.101770 | val_mse_raw=0.00004757 | best=0.00004647

22:49:08 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.100669 | val_mse_raw=0.00004900 | best=0.00004647

22:49:09 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.099426 | val_mse_raw=0.00004890 | best=0.00004647

22:49:10 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.096509 | val_mse_raw=0.00004829 | best=0.00004647
22:49:10 | INFO    | train_LSTM_baseline | Early stopping at epoch 19

22:49:10 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.805378 | val_mse_raw=0.00004459 | best=0.00004459

22:49:10 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.140909 | val_mse_raw=0.00004890 | best=0.00004459

22:49:10 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.116645 | val_mse_raw=0.00004288 | best=0.00004288

22:49:11 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.102941 | val_mse_raw=0.00004079 | best=0.00004079

22:49:11 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.100046 | val_mse_raw=0.00004113 | best=0.00004079

22:49:11 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.096959 | val_mse_raw=0.00004250 | best=0.00004079

22:49:12 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.096582 | val_mse_raw=0.00004275 | best=0.00004079

22:49:12 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.094739 | val_mse_raw=0.00004292 | best=0.00004079

22:49:12 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.094426 | val_mse_raw=0.00004419 | best=0.00004079

22:49:12 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.093357 | val_mse_raw=0.00004408 | best=0.00004079

22:49:13 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.093203 | val_mse_raw=0.00004349 | best=0.00004079

22:49:13 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.090917 | val_mse_raw=0.00004427 | best=0.00004079

22:49:13 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.091820 | val_mse_raw=0.00004378 | best=0.00004079

22:49:14 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.091673 | val_mse_raw=0.00004578 | best=0.00004079
22:49:14 | INFO    | train_LSTM_baseline | Early stopping at epoch 14

22:49:14 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.864315 | val_mse_raw=0.00004448 | best=0.00004448

22:49:14 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.141087 | val_mse_raw=0.00004932 | best=0.00004448

22:49:14 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.116821 | val_mse_raw=0.00004263 | best=0.00004263

22:49:15 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.102773 | val_mse_raw=0.00004084 | best=0.00004084

22:49:15 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.099886 | val_mse_raw=0.00004126 | best=0.00004084

22:49:15 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.097037 | val_mse_raw=0.00004296 | best=0.00004084

22:49:15 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.096347 | val_mse_raw=0.00004312 | best=0.00004084

22:49:16 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.094497 | val_mse_raw=0.00004336 | best=0.00004084

22:49:16 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.094140 | val_mse_raw=0.00004444 | best=0.00004084

22:49:16 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.093405 | val_mse_raw=0.00004391 | best=0.00004084

22:49:16 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.093103 | val_mse_raw=0.00004444 | best=0.00004084

22:49:17 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.091222 | val_mse_raw=0.00004462 | best=0.00004084

22:49:17 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.092044 | val_mse_raw=0.00004471 | best=0.00004084

22:49:17 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.092626 | val_mse_raw=0.00004500 | best=0.00004084
22:49:17 | INFO    | train_LSTM_baseline | Early stopping at epoch 14

22:49:18 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=5.309693 | val_mse_raw=0.00006688 | best=0.00006688

22:49:19 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.248611 | val_mse_raw=0.00006442 | best=0.00006442

22:49:20 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.248376 | val_mse_raw=0.00006405 | best=0.00006405

22:49:21 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.224199 | val_mse_raw=0.00005995 | best=0.00005995

22:49:21 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.155665 | val_mse_raw=0.00005050 | best=0.00005050

22:49:22 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.124051 | val_mse_raw=0.00004768 | best=0.00004768

22:49:23 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.114558 | val_mse_raw=0.00004967 | best=0.00004768

22:49:24 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.106315 | val_mse_raw=0.00004793 | best=0.00004768

22:49:25 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.103860 | val_mse_raw=0.00004925 | best=0.00004768

22:49:26 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.103497 | val_mse_raw=0.00004748 | best=0.00004748

22:49:27 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098326 | val_mse_raw=0.00004779 | best=0.00004748

22:49:27 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.095515 | val_mse_raw=0.00004814 | best=0.00004748

22:49:28 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.094118 | val_mse_raw=0.00004805 | best=0.00004748

22:49:29 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.091377 | val_mse_raw=0.00004770 | best=0.00004748

22:49:30 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.089831 | val_mse_raw=0.00004796 | best=0.00004748

22:49:31 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.090689 | val_mse_raw=0.00004733 | best=0.00004733

22:49:32 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.090556 | val_mse_raw=0.00004766 | best=0.00004733

22:49:32 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.086123 | val_mse_raw=0.00004783 | best=0.00004733

22:49:33 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.084652 | val_mse_raw=0.00004638 | best=0.00004638

22:49:34 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.082738 | val_mse_raw=0.00004548 | best=0.00004548

22:49:35 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.081077 | val_mse_raw=0.00004656 | best=0.00004548

22:49:36 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.079940 | val_mse_raw=0.00004466 | best=0.00004466

22:49:37 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.077553 | val_mse_raw=0.00004573 | best=0.00004466

22:49:37 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.077404 | val_mse_raw=0.00004534 | best=0.00004466

22:49:38 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.073199 | val_mse_raw=0.00004584 | best=0.00004466

22:49:39 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.072369 | val_mse_raw=0.00004448 | best=0.00004448

22:49:40 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.068945 | val_mse_raw=0.00004923 | best=0.00004448

22:49:41 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.066205 | val_mse_raw=0.00005053 | best=0.00004448

22:49:42 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.061179 | val_mse_raw=0.00004721 | best=0.00004448

22:49:42 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.059359 | val_mse_raw=0.00005413 | best=0.00004448

22:49:43 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.055016 | val_mse_raw=0.00004866 | best=0.00004448

22:49:44 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.052498 | val_mse_raw=0.00005174 | best=0.00004448

22:49:45 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.050734 | val_mse_raw=0.00005223 | best=0.00004448

22:49:46 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.045162 | val_mse_raw=0.00005647 | best=0.00004448

22:49:47 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.046153 | val_mse_raw=0.00006035 | best=0.00004448

22:49:47 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.043437 | val_mse_raw=0.00005310 | best=0.00004448
22:49:47 | INFO    | train_LSTM_baseline | Early stopping at epoch 36

22:49:48 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=13.578643 | val_mse_raw=0.00007549 | best=0.00007549

22:49:48 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.202748 | val_mse_raw=0.00005677 | best=0.00005677

22:49:48 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.141072 | val_mse_raw=0.00007455 | best=0.00005677

22:49:49 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.123626 | val_mse_raw=0.00006839 | best=0.00005677

22:49:49 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.112816 | val_mse_raw=0.00005168 | best=0.00005168

22:49:49 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.104661 | val_mse_raw=0.00004741 | best=0.00004741

22:49:49 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.101434 | val_mse_raw=0.00004513 | best=0.00004513

22:49:50 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.100539 | val_mse_raw=0.00004381 | best=0.00004381

22:49:50 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.099623 | val_mse_raw=0.00004328 | best=0.00004328

22:49:50 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.098154 | val_mse_raw=0.00004255 | best=0.00004255

22:49:50 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.097781 | val_mse_raw=0.00004270 | best=0.00004255

22:49:51 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.096435 | val_mse_raw=0.00004299 | best=0.00004255

22:49:51 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.096333 | val_mse_raw=0.00004289 | best=0.00004255

22:49:51 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.095428 | val_mse_raw=0.00004279 | best=0.00004255

22:49:51 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.095413 | val_mse_raw=0.00004294 | best=0.00004255

22:49:52 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.094584 | val_mse_raw=0.00004340 | best=0.00004255

22:49:52 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.094500 | val_mse_raw=0.00004344 | best=0.00004255

22:49:52 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.094055 | val_mse_raw=0.00004339 | best=0.00004255

22:49:53 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.093114 | val_mse_raw=0.00004333 | best=0.00004255

22:49:53 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.092910 | val_mse_raw=0.00004378 | best=0.00004255
22:49:53 | INFO    | train_LSTM_baseline | Early stopping at epoch 20

22:49:53 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.617453 | val_mse_raw=0.00004488 | best=0.00004488

22:49:54 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.138982 | val_mse_raw=0.00004999 | best=0.00004488

22:49:54 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.119306 | val_mse_raw=0.00004342 | best=0.00004342

22:49:54 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.107565 | val_mse_raw=0.00004335 | best=0.00004335

22:49:55 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.103042 | val_mse_raw=0.00004516 | best=0.00004335

22:49:55 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.101296 | val_mse_raw=0.00004509 | best=0.00004335

22:49:56 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.102835 | val_mse_raw=0.00004658 | best=0.00004335

22:49:56 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.098049 | val_mse_raw=0.00004689 | best=0.00004335

22:49:56 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.097267 | val_mse_raw=0.00004572 | best=0.00004335

22:49:57 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.096400 | val_mse_raw=0.00004854 | best=0.00004335

22:49:57 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.113022 | val_mse_raw=0.00004399 | best=0.00004335

22:49:58 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.094827 | val_mse_raw=0.00004435 | best=0.00004335

22:49:58 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.094044 | val_mse_raw=0.00004589 | best=0.00004335

22:49:58 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.099937 | val_mse_raw=0.00004511 | best=0.00004335
22:49:58 | INFO    | train_LSTM_baseline | Early stopping at epoch 14
22:49:59 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=17.237642 | val_mse_raw=0.01940980 | best=0.01940980

22:49:59 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=1.666866 | val_mse_raw=0.00004863 | best=0.00004863
22:49:59 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.177546 | val_mse_raw=0.00004984 | best=0.00004863

22:49:59 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.159478 | val_mse_raw=0.00004771 | best=0.00004771

22:49:59 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.146203 | val_mse_raw=0.00004424 | best=0.00004424

22:50:00 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.133792 | val_mse_raw=0.00004216 | best=0.00004216
22:50:00 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.122131 | val_mse_raw=0.00004110 | best=0.00004110

22:50:00 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.111482 | val_mse_raw=0.00004112 | best=0.00004110
22:50:00 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.105423 | val_mse_raw=0.00004174 | best=0.00004110

22:50:00 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.103873 | val_mse_raw=0.00004170 | best=0.00004110

22:50:01 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.101728 | val_mse_raw=0.00004243 | best=0.00004110

22:50:01 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.101331 | val_mse_raw=0.00004223 | best=0.00004110

22:50:01 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.101191 | val_mse_raw=0.00004252 | best=0.00004110
22:50:01 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.099658 | val_mse_raw=0.00004236 | best=0.00004110

22:50:01 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.099480 | val_mse_raw=0.00004225 | best=0.00004110
22:50:02 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.098904 | val_mse_raw=0.00004273 | best=0.00004110

22:50:02 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.098237 | val_mse_raw=0.00004264 | best=0.00004110
22:50:02 | INFO    | train_LSTM_baseline | Early stopping at epoch 17
22:50:02 | INFO    | train_LSTM_baseline | Best val MSE (raw scale): 0.00004079
22:50:02 | INFO    | train_LSTM_baseline | Best params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.3963210549539139, 'lr': 0.002654334209893313, 'batch_size': 64, 'seq_len': 21}

22:50:02 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.805378 | val_mse_raw=0.00004459 | best=0.00004459

22:50:02 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.140909 | val_mse_raw=0.00004890 | best=0.00004459

22:50:03 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.116645 | val_mse_raw=0.00004288 | best=0.00004288

22:50:03 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.102941 | val_mse_raw=0.00004079 | best=0.00004079

22:50:03 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.100046 | val_mse_raw=0.00004113 | best=0.00004079

22:50:03 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.096959 | val_mse_raw=0.00004250 | best=0.00004079

22:50:04 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.096582 | val_mse_raw=0.00004275 | best=0.00004079

22:50:04 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.094739 | val_mse_raw=0.00004292 | best=0.00004079

22:50:04 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.094426 | val_mse_raw=0.00004419 | best=0.00004079

22:50:04 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.093357 | val_mse_raw=0.00004408 | best=0.00004079

22:50:05 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.093203 | val_mse_raw=0.00004349 | best=0.00004079

22:50:05 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.090917 | val_mse_raw=0.00004427 | best=0.00004079

22:50:05 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.091820 | val_mse_raw=0.00004378 | best=0.00004079

22:50:05 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.091673 | val_mse_raw=0.00004578 | best=0.00004079
22:50:05 | INFO    | train_LSTM_baseline | Early stopping at epoch 14
22:50:05 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00004079
22:50:05 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.5847237591515295e-05, 'RMSE': 0.003980858717113733, 'MAE': 0.0025749634951353073, 'n_test_windows': 1461}
22:50:05 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_H_seed42.pt
22:50:05 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_H_seed42_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 1,
    "dropout": 0.3963210549539139,
    "lr": 0.002654334209893313,
    "batch_size": 64,
    "seq_len": 21
  },
  "best_val_mse_raw": 4.079103746335022e-05,
  "retrained_val_mse_raw": 4.079103746335022e-05,
  "test_metrics": {
    "MSE": 1.5847237591515295e-05,
    "RMSE": 0.003980858717113733,
    "MAE": 0.0025749634951353073,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish",
    "p_volatile"
  ],
  "target": "realized_vol_21d",
  "n_trials": 20,
  "seed": 42,
  "fixed_hparams_source": null
}

  [seed 42]  hparams JSON saved → hparams_lstm_baseline_H.json
================================================================================
[variant H  seed 43]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish p_volatile --output-prefix lstm_baseline_H_seed43 --seed 43 --fixed-hparams /content/repo/models/hparams_lstm_baseline_H.json
--------------------------------------------------------------------------------

22:50:08 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish', 'p_volatile']
22:50:08 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:50:08 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:50:08 | INFO    | train_LSTM_baseline | n_features=8 | rows — train=3690 val=1089 test=1481
22:50:08 | INFO    | train_LSTM_baseline | Skipping Optuna — using fixed hparams from /content/repo/models/hparams_lstm_baseline_H.json
22:50:08 | INFO    | train_LSTM_baseline | Fixed params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.3963210549539139, 'lr': 0.002654334209893313, 'batch_size': 64, 'seq_len': 21}

22:50:09 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.724355 | val_mse_raw=0.00004712 | best=0.00004712

22:50:10 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.145474 | val_mse_raw=0.00004646 | best=0.00004646

22:50:10 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.129208 | val_mse_raw=0.00004301 | best=0.00004301

22:50:10 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.123024 | val_mse_raw=0.00004124 | best=0.00004124

22:50:11 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.113087 | val_mse_raw=0.00004114 | best=0.00004114

22:50:11 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.109537 | val_mse_raw=0.00004119 | best=0.00004114

22:50:11 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.105836 | val_mse_raw=0.00004138 | best=0.00004114

22:50:11 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.105612 | val_mse_raw=0.00004164 | best=0.00004114

22:50:12 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.100714 | val_mse_raw=0.00004250 | best=0.00004114

22:50:12 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.100678 | val_mse_raw=0.00004220 | best=0.00004114

22:50:12 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.098895 | val_mse_raw=0.00004245 | best=0.00004114

22:50:13 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.099308 | val_mse_raw=0.00004200 | best=0.00004114

22:50:13 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.096983 | val_mse_raw=0.00004292 | best=0.00004114

22:50:13 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.096698 | val_mse_raw=0.00004230 | best=0.00004114

22:50:13 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.098457 | val_mse_raw=0.00004214 | best=0.00004114
22:50:13 | INFO    | train_LSTM_baseline | Early stopping at epoch 15
22:50:13 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00004114
22:50:13 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.4683002518722787e-05, 'RMSE': 0.0038318405859172344, 'MAE': 0.002544621005654335, 'n_test_windows': 1461}
22:50:13 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_H_seed43.pt
22:50:13 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_H_seed43_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 1,
    "dropout": 0.3963210549539139,
    "lr": 0.002654334209893313,
    "batch_size": 64,
    "seq_len": 21
  },
  "best_val_mse_raw": NaN,
  "retrained_val_mse_raw": 4.114153125556186e-05,
  "test_metrics": {
    "MSE": 1.4683002518722787e-05,
    "RMSE": 0.0038318405859172344,
    "MAE": 0.002544621005654335,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish",
    "p_volatile"
  ],
  "target": "realized_vol_21d",
  "n_trials": 0,
  "seed": 43,
  "fixed_hparams_source": "/content/repo/models/hparams_lstm_baseline_H.json"
}

================================================================================
[variant H  seed 44]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish p_volatile --output-prefix lstm_baseline_H_seed44 --seed 44 --fixed-hparams /content/repo/models/hparams_lstm_baseline_H.json
--------------------------------------------------------------------------------

22:50:17 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish', 'p_volatile']
22:50:17 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:50:17 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:50:17 | INFO    | train_LSTM_baseline | n_features=8 | rows — train=3690 val=1089 test=1481
22:50:17 | INFO    | train_LSTM_baseline | Skipping Optuna — using fixed hparams from /content/repo/models/hparams_lstm_baseline_H.json
22:50:17 | INFO    | train_LSTM_baseline | Fixed params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.3963210549539139, 'lr': 0.002654334209893313, 'batch_size': 64, 'seq_len': 21}

22:50:18 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.963327 | val_mse_raw=0.00004639 | best=0.00004639

22:50:18 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.146987 | val_mse_raw=0.00006232 | best=0.00004639

22:50:18 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.134556 | val_mse_raw=0.00004877 | best=0.00004639

22:50:18 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.126955 | val_mse_raw=0.00004499 | best=0.00004499

22:50:19 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.121983 | val_mse_raw=0.00004312 | best=0.00004312

22:50:19 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.117195 | val_mse_raw=0.00004289 | best=0.00004289

22:50:19 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.115186 | val_mse_raw=0.00004309 | best=0.00004289

22:50:19 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.112359 | val_mse_raw=0.00004326 | best=0.00004289

22:50:20 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.112382 | val_mse_raw=0.00004294 | best=0.00004289

22:50:20 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.110225 | val_mse_raw=0.00004282 | best=0.00004282

22:50:20 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.107692 | val_mse_raw=0.00004293 | best=0.00004282

22:50:20 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.106182 | val_mse_raw=0.00004304 | best=0.00004282

22:50:21 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.104794 | val_mse_raw=0.00004307 | best=0.00004282

22:50:21 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.101901 | val_mse_raw=0.00004300 | best=0.00004282

22:50:21 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.100570 | val_mse_raw=0.00004366 | best=0.00004282

22:50:21 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.099206 | val_mse_raw=0.00004291 | best=0.00004282

22:50:22 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.097604 | val_mse_raw=0.00004335 | best=0.00004282

22:50:22 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.098729 | val_mse_raw=0.00004324 | best=0.00004282

22:50:22 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.096086 | val_mse_raw=0.00004315 | best=0.00004282

22:50:22 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.096215 | val_mse_raw=0.00004353 | best=0.00004282
22:50:22 | INFO    | train_LSTM_baseline | Early stopping at epoch 20
22:50:22 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00004282
22:50:23 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.3869064787286334e-05, 'RMSE': 0.0037241193931549788, 'MAE': 0.002469955012202263, 'n_test_windows': 1461}
22:50:23 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_H_seed44.pt
22:50:23 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_H_seed44_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 1,
    "dropout": 0.3963210549539139,
    "lr": 0.002654334209893313,
    "batch_size": 64,
    "seq_len": 21
  },
  "best_val_mse_raw": NaN,
  "retrained_val_mse_raw": 4.2821106035262346e-05,
  "test_metrics": {
    "MSE": 1.3869064787286334e-05,
    "RMSE": 0.0037241193931549788,
    "MAE": 0.002469955012202263,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish",
    "p_volatile"
  ],
  "target": "realized_vol_21d",
  "n_trials": 0,
  "seed": 44,
  "fixed_hparams_source": "/content/repo/models/hparams_lstm_baseline_H.json"
}

================================================================================
[variant B  seed 42]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish vix vix_log_change vix3m_minus_vix --output-prefix lstm_baseline_B_seed42 --seed 42
--------------------------------------------------------------------------------

22:50:26 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish', 'vix', 'vix_log_change', 'vix3m_minus_vix']
22:50:26 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:50:26 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:50:26 | INFO    | train_LSTM_baseline | n_features=10 | rows — train=2034 val=1089 test=1481
22:50:26 | INFO    | train_LSTM_baseline | Starting Optuna study with 20 trials…

22:50:27 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=5.155175 | val_mse_raw=0.00009738 | best=0.00009738
22:50:27 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.206899 | val_mse_raw=0.00008530 | best=0.00008530

22:50:27 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.141506 | val_mse_raw=0.00004843 | best=0.00004843
22:50:27 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.126491 | val_mse_raw=0.00004410 | best=0.00004410

22:50:27 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.119243 | val_mse_raw=0.00004144 | best=0.00004144
22:50:27 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.117196 | val_mse_raw=0.00004130 | best=0.00004130

22:50:27 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.115783 | val_mse_raw=0.00004084 | best=0.00004084
22:50:28 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.114799 | val_mse_raw=0.00004045 | best=0.00004045

22:50:28 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.115069 | val_mse_raw=0.00004034 | best=0.00004034
22:50:28 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.113514 | val_mse_raw=0.00004089 | best=0.00004034

22:50:28 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.115802 | val_mse_raw=0.00004054 | best=0.00004034
22:50:28 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.112830 | val_mse_raw=0.00003982 | best=0.00003982

22:50:28 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.113469 | val_mse_raw=0.00003989 | best=0.00003982
22:50:29 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.111598 | val_mse_raw=0.00003978 | best=0.00003978

22:50:29 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.113236 | val_mse_raw=0.00003955 | best=0.00003955
22:50:29 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.113789 | val_mse_raw=0.00003992 | best=0.00003955

22:50:29 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.114317 | val_mse_raw=0.00003918 | best=0.00003918
22:50:29 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.110793 | val_mse_raw=0.00003900 | best=0.00003900

22:50:29 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.109989 | val_mse_raw=0.00003982 | best=0.00003900
22:50:30 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.112590 | val_mse_raw=0.00003926 | best=0.00003900

22:50:30 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.111642 | val_mse_raw=0.00003888 | best=0.00003888
22:50:30 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.111315 | val_mse_raw=0.00003833 | best=0.00003833

22:50:30 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.109175 | val_mse_raw=0.00003907 | best=0.00003833
22:50:30 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.109353 | val_mse_raw=0.00003817 | best=0.00003817

22:50:30 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.109116 | val_mse_raw=0.00003921 | best=0.00003817
22:50:30 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.110068 | val_mse_raw=0.00003846 | best=0.00003817

22:50:31 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.110457 | val_mse_raw=0.00003864 | best=0.00003817
22:50:31 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.111522 | val_mse_raw=0.00003811 | best=0.00003811

22:50:31 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.106620 | val_mse_raw=0.00003860 | best=0.00003811
22:50:31 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.109770 | val_mse_raw=0.00003876 | best=0.00003811

22:50:31 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.106384 | val_mse_raw=0.00003867 | best=0.00003811
22:50:31 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.106130 | val_mse_raw=0.00003834 | best=0.00003811

22:50:32 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.104741 | val_mse_raw=0.00003847 | best=0.00003811
22:50:32 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.105995 | val_mse_raw=0.00003933 | best=0.00003811

22:50:32 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.110537 | val_mse_raw=0.00003986 | best=0.00003811
22:50:32 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.107667 | val_mse_raw=0.00003892 | best=0.00003811

22:50:32 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.100986 | val_mse_raw=0.00003961 | best=0.00003811
22:50:32 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.099261 | val_mse_raw=0.00003919 | best=0.00003811
22:50:32 | INFO    | train_LSTM_baseline | Early stopping at epoch 38

22:50:33 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.645561 | val_mse_raw=0.28049180 | best=0.28049180

22:50:33 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=10.670060 | val_mse_raw=0.00391763 | best=0.00391763

22:50:33 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=2.126940 | val_mse_raw=0.00013907 | best=0.00013907

22:50:34 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.363540 | val_mse_raw=0.00006442 | best=0.00006442

22:50:34 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.287934 | val_mse_raw=0.00006400 | best=0.00006400

22:50:34 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.271863 | val_mse_raw=0.00006291 | best=0.00006291

22:50:34 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.254036 | val_mse_raw=0.00006195 | best=0.00006195

22:50:35 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.236241 | val_mse_raw=0.00005894 | best=0.00005894

22:50:35 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.201990 | val_mse_raw=0.00005596 | best=0.00005596

22:50:35 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.174627 | val_mse_raw=0.00005438 | best=0.00005438

22:50:36 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.156097 | val_mse_raw=0.00005117 | best=0.00005117

22:50:36 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.141882 | val_mse_raw=0.00005022 | best=0.00005022

22:50:37 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.130285 | val_mse_raw=0.00004803 | best=0.00004803

22:50:37 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.126780 | val_mse_raw=0.00004676 | best=0.00004676

22:50:37 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.123403 | val_mse_raw=0.00004673 | best=0.00004673

22:50:37 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.122854 | val_mse_raw=0.00004622 | best=0.00004622

22:50:38 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.120866 | val_mse_raw=0.00004522 | best=0.00004522

22:50:38 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.118623 | val_mse_raw=0.00004560 | best=0.00004522

22:50:38 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.117051 | val_mse_raw=0.00004451 | best=0.00004451

22:50:39 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.115803 | val_mse_raw=0.00004433 | best=0.00004433

22:50:39 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.114726 | val_mse_raw=0.00004415 | best=0.00004415

22:50:39 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.114419 | val_mse_raw=0.00004345 | best=0.00004345

22:50:40 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.113783 | val_mse_raw=0.00004401 | best=0.00004345

22:50:40 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.110551 | val_mse_raw=0.00004276 | best=0.00004276

22:50:40 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.109803 | val_mse_raw=0.00004277 | best=0.00004276

22:50:40 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.108304 | val_mse_raw=0.00004331 | best=0.00004276

22:50:41 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.107710 | val_mse_raw=0.00004249 | best=0.00004249

22:50:41 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.106139 | val_mse_raw=0.00004220 | best=0.00004220

22:50:41 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.105829 | val_mse_raw=0.00004197 | best=0.00004197

22:50:42 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.107700 | val_mse_raw=0.00004203 | best=0.00004197

22:50:42 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.107250 | val_mse_raw=0.00004304 | best=0.00004197

22:50:42 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.105747 | val_mse_raw=0.00004269 | best=0.00004197

22:50:43 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.103707 | val_mse_raw=0.00004285 | best=0.00004197

22:50:43 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.101581 | val_mse_raw=0.00004241 | best=0.00004197

22:50:43 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.103014 | val_mse_raw=0.00004277 | best=0.00004197

22:50:43 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.102297 | val_mse_raw=0.00004265 | best=0.00004197

22:50:44 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.102280 | val_mse_raw=0.00004278 | best=0.00004197

22:50:44 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.101792 | val_mse_raw=0.00004262 | best=0.00004197

22:50:44 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.101070 | val_mse_raw=0.00004157 | best=0.00004157

22:50:45 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.100543 | val_mse_raw=0.00004241 | best=0.00004157

22:50:46 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.007906 | val_mse_raw=0.00004155 | best=0.00004155

22:50:48 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.129087 | val_mse_raw=0.00004132 | best=0.00004132

22:50:49 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.128374 | val_mse_raw=0.00004586 | best=0.00004132

22:50:51 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.126309 | val_mse_raw=0.00004105 | best=0.00004105

22:50:52 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.111772 | val_mse_raw=0.00003921 | best=0.00003921

22:50:54 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.107207 | val_mse_raw=0.00004072 | best=0.00003921

22:50:55 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.102104 | val_mse_raw=0.00004156 | best=0.00003921

22:50:57 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.101826 | val_mse_raw=0.00004821 | best=0.00003921

22:50:58 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.105805 | val_mse_raw=0.00004448 | best=0.00003921

22:51:00 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.107595 | val_mse_raw=0.00004368 | best=0.00003921

22:51:01 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.082146 | val_mse_raw=0.00004090 | best=0.00003921

22:51:03 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.086493 | val_mse_raw=0.00005225 | best=0.00003921

22:51:04 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.084058 | val_mse_raw=0.00004848 | best=0.00003921

22:51:06 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.064072 | val_mse_raw=0.00004908 | best=0.00003921

22:51:07 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.061941 | val_mse_raw=0.00005313 | best=0.00003921
22:51:07 | INFO    | train_LSTM_baseline | Early stopping at epoch 15

22:51:08 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=14.144184 | val_mse_raw=0.00006424 | best=0.00006424

22:51:08 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.354609 | val_mse_raw=0.00006113 | best=0.00006113

22:51:09 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.179298 | val_mse_raw=0.00005415 | best=0.00005415

22:51:09 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.144358 | val_mse_raw=0.00005051 | best=0.00005051

22:51:10 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.134494 | val_mse_raw=0.00004925 | best=0.00004925

22:51:11 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.127768 | val_mse_raw=0.00004896 | best=0.00004896

22:51:11 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.121777 | val_mse_raw=0.00004753 | best=0.00004753

22:51:12 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.118071 | val_mse_raw=0.00004593 | best=0.00004593

22:51:13 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.115911 | val_mse_raw=0.00004499 | best=0.00004499

22:51:13 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.113473 | val_mse_raw=0.00004463 | best=0.00004463

22:51:14 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.112104 | val_mse_raw=0.00004408 | best=0.00004408

22:51:15 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.109094 | val_mse_raw=0.00004413 | best=0.00004408

22:51:15 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.109804 | val_mse_raw=0.00004507 | best=0.00004408

22:51:16 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.105745 | val_mse_raw=0.00004311 | best=0.00004311

22:51:16 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.103058 | val_mse_raw=0.00004277 | best=0.00004277

22:51:17 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.106269 | val_mse_raw=0.00004255 | best=0.00004255

22:51:18 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.100774 | val_mse_raw=0.00004345 | best=0.00004255

22:51:18 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.100551 | val_mse_raw=0.00004261 | best=0.00004255

22:51:19 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.098520 | val_mse_raw=0.00004173 | best=0.00004173

22:51:19 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.099282 | val_mse_raw=0.00004264 | best=0.00004173

22:51:20 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.097741 | val_mse_raw=0.00004352 | best=0.00004173

22:51:21 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.098260 | val_mse_raw=0.00004430 | best=0.00004173

22:51:21 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.094325 | val_mse_raw=0.00004385 | best=0.00004173

22:51:22 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.093302 | val_mse_raw=0.00004442 | best=0.00004173

22:51:22 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.092856 | val_mse_raw=0.00004533 | best=0.00004173

22:51:23 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.090916 | val_mse_raw=0.00004404 | best=0.00004173

22:51:24 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.089679 | val_mse_raw=0.00004441 | best=0.00004173

22:51:24 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.089339 | val_mse_raw=0.00004481 | best=0.00004173

22:51:25 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.086537 | val_mse_raw=0.00004541 | best=0.00004173
22:51:25 | INFO    | train_LSTM_baseline | Early stopping at epoch 29
22:51:25 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=21.049362 | val_mse_raw=0.67741531 | best=0.67741531
22:51:25 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=20.174414 | val_mse_raw=0.52517921 | best=0.52517921

22:51:25 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=18.957475 | val_mse_raw=0.34219632 | best=0.34219632
22:51:25 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=16.707659 | val_mse_raw=0.15487610 | best=0.15487610
22:51:25 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=12.596846 | val_mse_raw=0.04575427 | best=0.04575427

22:51:26 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=7.616747 | val_mse_raw=0.01077170 | best=0.01077170
22:51:26 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=3.857936 | val_mse_raw=0.00249831 | best=0.00249831
22:51:26 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=1.867611 | val_mse_raw=0.00073493 | best=0.00073493

22:51:26 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.918588 | val_mse_raw=0.00027810 | best=0.00027810
22:51:26 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.476138 | val_mse_raw=0.00014349 | best=0.00014349
22:51:26 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.295105 | val_mse_raw=0.00009666 | best=0.00009666

22:51:26 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.228562 | val_mse_raw=0.00007877 | best=0.00007877
22:51:26 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.204288 | val_mse_raw=0.00007224 | best=0.00007224
22:51:26 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.193925 | val_mse_raw=0.00006849 | best=0.00006849

22:51:26 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.186031 | val_mse_raw=0.00006689 | best=0.00006689
22:51:26 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.179395 | val_mse_raw=0.00006641 | best=0.00006641
22:51:27 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.172552 | val_mse_raw=0.00006524 | best=0.00006524

22:51:27 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.166283 | val_mse_raw=0.00006407 | best=0.00006407
22:51:27 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.159704 | val_mse_raw=0.00006254 | best=0.00006254
22:51:27 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.153821 | val_mse_raw=0.00006079 | best=0.00006079

22:51:27 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.147886 | val_mse_raw=0.00005888 | best=0.00005888
22:51:27 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.142786 | val_mse_raw=0.00005697 | best=0.00005697
22:51:27 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.138218 | val_mse_raw=0.00005534 | best=0.00005534

22:51:27 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.134740 | val_mse_raw=0.00005341 | best=0.00005341
22:51:27 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.131426 | val_mse_raw=0.00005172 | best=0.00005172
22:51:27 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.128504 | val_mse_raw=0.00005056 | best=0.00005056

22:51:27 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.126267 | val_mse_raw=0.00004964 | best=0.00004964
22:51:27 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.124260 | val_mse_raw=0.00004865 | best=0.00004865
22:51:28 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.122674 | val_mse_raw=0.00004784 | best=0.00004784

22:51:28 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.121274 | val_mse_raw=0.00004724 | best=0.00004724
22:51:28 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.120150 | val_mse_raw=0.00004667 | best=0.00004667
22:51:28 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.119193 | val_mse_raw=0.00004627 | best=0.00004627

22:51:28 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.118367 | val_mse_raw=0.00004585 | best=0.00004585
22:51:28 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.117661 | val_mse_raw=0.00004547 | best=0.00004547
22:51:28 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.117012 | val_mse_raw=0.00004520 | best=0.00004520

22:51:28 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.116355 | val_mse_raw=0.00004489 | best=0.00004489
22:51:28 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.115838 | val_mse_raw=0.00004475 | best=0.00004475
22:51:28 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.115345 | val_mse_raw=0.00004455 | best=0.00004455

22:51:28 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.114859 | val_mse_raw=0.00004424 | best=0.00004424
22:51:28 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.114635 | val_mse_raw=0.00004408 | best=0.00004408

22:51:29 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=19.442005 | val_mse_raw=0.18045112 | best=0.18045112

22:51:30 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=2.815676 | val_mse_raw=0.00005717 | best=0.00005717

22:51:31 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.167917 | val_mse_raw=0.00005206 | best=0.00005206

22:51:31 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.139191 | val_mse_raw=0.00005285 | best=0.00005206

22:51:32 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.133395 | val_mse_raw=0.00005322 | best=0.00005206

22:51:33 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.130393 | val_mse_raw=0.00005174 | best=0.00005174

22:51:34 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.127040 | val_mse_raw=0.00005108 | best=0.00005108

22:51:34 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.125096 | val_mse_raw=0.00004996 | best=0.00004996

22:51:35 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.122846 | val_mse_raw=0.00004974 | best=0.00004974

22:51:36 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.120172 | val_mse_raw=0.00004885 | best=0.00004885

22:51:37 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.118581 | val_mse_raw=0.00004745 | best=0.00004745

22:51:38 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.116336 | val_mse_raw=0.00004713 | best=0.00004713

22:51:38 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.114761 | val_mse_raw=0.00004708 | best=0.00004708

22:51:39 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.111665 | val_mse_raw=0.00004602 | best=0.00004602

22:51:40 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.110079 | val_mse_raw=0.00004527 | best=0.00004527

22:51:41 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.109058 | val_mse_raw=0.00004538 | best=0.00004527

22:51:41 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.105812 | val_mse_raw=0.00004461 | best=0.00004461

22:51:42 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.103482 | val_mse_raw=0.00004366 | best=0.00004366

22:51:43 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.102901 | val_mse_raw=0.00004316 | best=0.00004316

22:51:44 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.101729 | val_mse_raw=0.00004422 | best=0.00004316

22:51:44 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.100836 | val_mse_raw=0.00004397 | best=0.00004316

22:51:45 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.100274 | val_mse_raw=0.00004313 | best=0.00004313

22:51:46 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.098823 | val_mse_raw=0.00004196 | best=0.00004196

22:51:47 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.097785 | val_mse_raw=0.00004343 | best=0.00004196

22:51:47 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.096338 | val_mse_raw=0.00004266 | best=0.00004196

22:51:48 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.096787 | val_mse_raw=0.00004206 | best=0.00004196

22:51:49 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.095091 | val_mse_raw=0.00004220 | best=0.00004196

22:51:50 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.095376 | val_mse_raw=0.00004278 | best=0.00004196

22:51:51 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.093376 | val_mse_raw=0.00004333 | best=0.00004196

22:51:51 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.093841 | val_mse_raw=0.00004287 | best=0.00004196

22:51:52 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.092782 | val_mse_raw=0.00004295 | best=0.00004196

22:51:53 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.091954 | val_mse_raw=0.00004321 | best=0.00004196

22:51:53 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.090949 | val_mse_raw=0.00004387 | best=0.00004196
22:51:53 | INFO    | train_LSTM_baseline | Early stopping at epoch 33

22:51:54 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=21.783346 | val_mse_raw=0.71253502 | best=0.71253502

22:51:54 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=17.851132 | val_mse_raw=0.04130505 | best=0.04130505

22:51:54 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=2.381849 | val_mse_raw=0.00006181 | best=0.00006181

22:51:54 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.410512 | val_mse_raw=0.00005527 | best=0.00005527

22:51:55 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.227293 | val_mse_raw=0.00005369 | best=0.00005369

22:51:55 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.199066 | val_mse_raw=0.00004848 | best=0.00004848

22:51:55 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.177871 | val_mse_raw=0.00004873 | best=0.00004848

22:51:55 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.159897 | val_mse_raw=0.00005145 | best=0.00004848

22:51:55 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.143926 | val_mse_raw=0.00005507 | best=0.00004848

22:51:56 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.133527 | val_mse_raw=0.00005537 | best=0.00004848

22:51:56 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.128130 | val_mse_raw=0.00005475 | best=0.00004848

22:51:56 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.123882 | val_mse_raw=0.00005147 | best=0.00004848

22:51:56 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.122475 | val_mse_raw=0.00005003 | best=0.00004848

22:51:57 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.118466 | val_mse_raw=0.00004917 | best=0.00004848

22:51:57 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.116803 | val_mse_raw=0.00004732 | best=0.00004732

22:51:57 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.113741 | val_mse_raw=0.00004614 | best=0.00004614

22:51:57 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.112268 | val_mse_raw=0.00004531 | best=0.00004531

22:51:57 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.111901 | val_mse_raw=0.00004364 | best=0.00004364

22:51:58 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.110114 | val_mse_raw=0.00004322 | best=0.00004322

22:51:58 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.109576 | val_mse_raw=0.00004294 | best=0.00004294

22:51:58 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.108249 | val_mse_raw=0.00004283 | best=0.00004283

22:51:58 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.107837 | val_mse_raw=0.00004228 | best=0.00004228

22:51:59 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.106343 | val_mse_raw=0.00004134 | best=0.00004134

22:51:59 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.107301 | val_mse_raw=0.00004163 | best=0.00004134

22:51:59 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.105457 | val_mse_raw=0.00004218 | best=0.00004134

22:51:59 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.104388 | val_mse_raw=0.00004194 | best=0.00004134

22:52:00 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.104343 | val_mse_raw=0.00004258 | best=0.00004134

22:52:00 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.103307 | val_mse_raw=0.00004197 | best=0.00004134

22:52:00 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.103166 | val_mse_raw=0.00004234 | best=0.00004134

22:52:00 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.103191 | val_mse_raw=0.00004217 | best=0.00004134

22:52:01 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.101883 | val_mse_raw=0.00003984 | best=0.00003984

22:52:01 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.102363 | val_mse_raw=0.00004004 | best=0.00003984

22:52:01 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.102500 | val_mse_raw=0.00004264 | best=0.00003984

22:52:01 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.102265 | val_mse_raw=0.00004163 | best=0.00003984

22:52:01 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.101038 | val_mse_raw=0.00004212 | best=0.00003984

22:52:02 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.100106 | val_mse_raw=0.00004058 | best=0.00003984

22:52:02 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.100485 | val_mse_raw=0.00003935 | best=0.00003935

22:52:02 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.099972 | val_mse_raw=0.00004136 | best=0.00003935

22:52:02 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.099659 | val_mse_raw=0.00004025 | best=0.00003935

22:52:03 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.098722 | val_mse_raw=0.00004068 | best=0.00003935

22:52:03 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=22.793812 | val_mse_raw=1.14277303 | best=1.14277303
22:52:03 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=22.545448 | val_mse_raw=1.07248092 | best=1.07248092

22:52:03 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=22.281391 | val_mse_raw=1.00017738 | best=1.00017738
22:52:03 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=21.982322 | val_mse_raw=0.91848350 | best=0.91848350

22:52:04 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=21.609575 | val_mse_raw=0.82297182 | best=0.82297182
22:52:04 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=21.102848 | val_mse_raw=0.69886279 | best=0.69886279

22:52:04 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=20.289154 | val_mse_raw=0.52303898 | best=0.52303898

22:52:04 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=18.629095 | val_mse_raw=0.27458003 | best=0.27458003
22:52:04 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=14.701124 | val_mse_raw=0.08114561 | best=0.08114561

22:52:05 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=9.208867 | val_mse_raw=0.02435635 | best=0.02435635
22:52:05 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=5.299652 | val_mse_raw=0.00783716 | best=0.00783716

22:52:05 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=3.335227 | val_mse_raw=0.00300525 | best=0.00300525

22:52:05 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=2.249935 | val_mse_raw=0.00132890 | best=0.00132890

22:52:05 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=1.547875 | val_mse_raw=0.00063341 | best=0.00063341

22:52:06 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=1.078311 | val_mse_raw=0.00032685 | best=0.00032685

22:52:06 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.758550 | val_mse_raw=0.00018843 | best=0.00018843
22:52:06 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.550293 | val_mse_raw=0.00012255 | best=0.00012255

22:52:06 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.416982 | val_mse_raw=0.00009128 | best=0.00009128

22:52:06 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.333391 | val_mse_raw=0.00007551 | best=0.00007551
22:52:07 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.281738 | val_mse_raw=0.00006671 | best=0.00006671

22:52:07 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.249250 | val_mse_raw=0.00006146 | best=0.00006146
22:52:07 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.228071 | val_mse_raw=0.00005846 | best=0.00005846

22:52:07 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.214924 | val_mse_raw=0.00005637 | best=0.00005637

22:52:07 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.205530 | val_mse_raw=0.00005506 | best=0.00005506
22:52:08 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.198665 | val_mse_raw=0.00005418 | best=0.00005418

22:52:08 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.193523 | val_mse_raw=0.00005364 | best=0.00005364
22:52:08 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.189199 | val_mse_raw=0.00005313 | best=0.00005313

22:52:08 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.185400 | val_mse_raw=0.00005287 | best=0.00005287
22:52:08 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.181711 | val_mse_raw=0.00005272 | best=0.00005272

22:52:09 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.178135 | val_mse_raw=0.00005255 | best=0.00005255
22:52:09 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.174697 | val_mse_raw=0.00005239 | best=0.00005239

22:52:09 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.171306 | val_mse_raw=0.00005223 | best=0.00005223
22:52:09 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.167899 | val_mse_raw=0.00005217 | best=0.00005217

22:52:09 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.164656 | val_mse_raw=0.00005215 | best=0.00005215

22:52:10 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.161448 | val_mse_raw=0.00005192 | best=0.00005192
22:52:10 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.158248 | val_mse_raw=0.00005184 | best=0.00005184

22:52:10 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.155378 | val_mse_raw=0.00005170 | best=0.00005170
22:52:10 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.152424 | val_mse_raw=0.00005145 | best=0.00005145

22:52:10 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.149722 | val_mse_raw=0.00005122 | best=0.00005122

22:52:11 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.147263 | val_mse_raw=0.00005110 | best=0.00005110
22:52:11 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.678766 | val_mse_raw=0.54952079 | best=0.54952079

22:52:11 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=17.894689 | val_mse_raw=0.14975163 | best=0.14975163
22:52:11 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=9.508504 | val_mse_raw=0.00912420 | best=0.00912420

22:52:11 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=2.725510 | val_mse_raw=0.00086079 | best=0.00086079

22:52:12 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.810551 | val_mse_raw=0.00017465 | best=0.00017465

22:52:12 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.333504 | val_mse_raw=0.00008625 | best=0.00008625

22:52:12 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.224639 | val_mse_raw=0.00007000 | best=0.00007000

22:52:12 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.193814 | val_mse_raw=0.00006458 | best=0.00006458
22:52:12 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.177900 | val_mse_raw=0.00006253 | best=0.00006253

22:52:13 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.164121 | val_mse_raw=0.00006071 | best=0.00006071
22:52:13 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.151616 | val_mse_raw=0.00005715 | best=0.00005715

22:52:13 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.141139 | val_mse_raw=0.00005354 | best=0.00005354
22:52:13 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.133597 | val_mse_raw=0.00005107 | best=0.00005107

22:52:13 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.127809 | val_mse_raw=0.00004905 | best=0.00004905
22:52:13 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.124029 | val_mse_raw=0.00004742 | best=0.00004742

22:52:14 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.121332 | val_mse_raw=0.00004648 | best=0.00004648
22:52:14 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.119482 | val_mse_raw=0.00004560 | best=0.00004560

22:52:14 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.118092 | val_mse_raw=0.00004503 | best=0.00004503
22:52:14 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.116851 | val_mse_raw=0.00004441 | best=0.00004441

22:52:14 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.115714 | val_mse_raw=0.00004410 | best=0.00004410
22:52:15 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.115091 | val_mse_raw=0.00004385 | best=0.00004385

22:52:15 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.113881 | val_mse_raw=0.00004345 | best=0.00004345
22:52:15 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.113421 | val_mse_raw=0.00004333 | best=0.00004333

22:52:15 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.112673 | val_mse_raw=0.00004315 | best=0.00004315
22:52:15 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.111888 | val_mse_raw=0.00004282 | best=0.00004282

22:52:15 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.111684 | val_mse_raw=0.00004262 | best=0.00004262
22:52:16 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.111010 | val_mse_raw=0.00004253 | best=0.00004253

22:52:16 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.110558 | val_mse_raw=0.00004237 | best=0.00004237
22:52:16 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.110049 | val_mse_raw=0.00004223 | best=0.00004223

22:52:16 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.109582 | val_mse_raw=0.00004210 | best=0.00004210
22:52:16 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.109788 | val_mse_raw=0.00004204 | best=0.00004204

22:52:16 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.108836 | val_mse_raw=0.00004188 | best=0.00004188
22:52:17 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.108512 | val_mse_raw=0.00004179 | best=0.00004179

22:52:17 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.107866 | val_mse_raw=0.00004181 | best=0.00004179
22:52:17 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.108066 | val_mse_raw=0.00004156 | best=0.00004156

22:52:17 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.107508 | val_mse_raw=0.00004135 | best=0.00004135
22:52:17 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.107162 | val_mse_raw=0.00004146 | best=0.00004135

22:52:17 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.106374 | val_mse_raw=0.00004119 | best=0.00004119
22:52:17 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.106302 | val_mse_raw=0.00004118 | best=0.00004118

22:52:18 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.105948 | val_mse_raw=0.00004101 | best=0.00004101

22:52:18 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=20.192255 | val_mse_raw=0.56449002 | best=0.56449002

22:52:19 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=19.005090 | val_mse_raw=0.36805469 | best=0.36805469

22:52:19 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=16.056133 | val_mse_raw=0.06532264 | best=0.06532264

22:52:20 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=6.866463 | val_mse_raw=0.00122435 | best=0.00122435

22:52:20 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=1.476766 | val_mse_raw=0.00013926 | best=0.00013926

22:52:21 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.420191 | val_mse_raw=0.00006767 | best=0.00006767

22:52:21 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.259462 | val_mse_raw=0.00006232 | best=0.00006232

22:52:22 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.246883 | val_mse_raw=0.00006077 | best=0.00006077

22:52:22 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.232526 | val_mse_raw=0.00005901 | best=0.00005901

22:52:23 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.215540 | val_mse_raw=0.00005669 | best=0.00005669

22:52:23 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.194142 | val_mse_raw=0.00005408 | best=0.00005408

22:52:24 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.169544 | val_mse_raw=0.00005274 | best=0.00005274

22:52:25 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.149198 | val_mse_raw=0.00005284 | best=0.00005274

22:52:25 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.137577 | val_mse_raw=0.00005147 | best=0.00005147

22:52:26 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.131032 | val_mse_raw=0.00005049 | best=0.00005049

22:52:26 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.127298 | val_mse_raw=0.00004974 | best=0.00004974

22:52:27 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.123879 | val_mse_raw=0.00004923 | best=0.00004923

22:52:27 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.121433 | val_mse_raw=0.00004856 | best=0.00004856

22:52:28 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.118233 | val_mse_raw=0.00004873 | best=0.00004856

22:52:28 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.115449 | val_mse_raw=0.00004883 | best=0.00004856

22:52:29 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.113653 | val_mse_raw=0.00004850 | best=0.00004850

22:52:29 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.111581 | val_mse_raw=0.00004906 | best=0.00004850

22:52:30 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.110349 | val_mse_raw=0.00004822 | best=0.00004822

22:52:30 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.109061 | val_mse_raw=0.00004789 | best=0.00004789

22:52:31 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.108115 | val_mse_raw=0.00004858 | best=0.00004789

22:52:31 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.106050 | val_mse_raw=0.00004809 | best=0.00004789

22:52:32 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.105352 | val_mse_raw=0.00004811 | best=0.00004789

22:52:32 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.103711 | val_mse_raw=0.00004842 | best=0.00004789

22:52:33 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.103015 | val_mse_raw=0.00004794 | best=0.00004789

22:52:33 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.101735 | val_mse_raw=0.00004802 | best=0.00004789

22:52:34 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.100880 | val_mse_raw=0.00004792 | best=0.00004789

22:52:34 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.099660 | val_mse_raw=0.00004796 | best=0.00004789

22:52:35 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.099302 | val_mse_raw=0.00004748 | best=0.00004748

22:52:36 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.098490 | val_mse_raw=0.00004870 | best=0.00004748

22:52:36 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.097062 | val_mse_raw=0.00004841 | best=0.00004748

22:52:37 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.096860 | val_mse_raw=0.00004877 | best=0.00004748

22:52:37 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.096642 | val_mse_raw=0.00004829 | best=0.00004748

22:52:38 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.095447 | val_mse_raw=0.00004931 | best=0.00004748

22:52:38 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.094273 | val_mse_raw=0.00004941 | best=0.00004748

22:52:39 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.095363 | val_mse_raw=0.00004950 | best=0.00004748

22:52:39 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.637819 | val_mse_raw=0.00006607 | best=0.00006607

22:52:40 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.302401 | val_mse_raw=0.00006632 | best=0.00006607

22:52:40 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.285453 | val_mse_raw=0.00006655 | best=0.00006607

22:52:41 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.285058 | val_mse_raw=0.00006493 | best=0.00006493

22:52:41 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.287362 | val_mse_raw=0.00006510 | best=0.00006493

22:52:42 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.291856 | val_mse_raw=0.00006588 | best=0.00006493

22:52:42 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.289339 | val_mse_raw=0.00006525 | best=0.00006493

22:52:43 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.284078 | val_mse_raw=0.00006502 | best=0.00006493

22:52:43 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.288669 | val_mse_raw=0.00006606 | best=0.00006493

22:52:44 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.269608 | val_mse_raw=0.00006271 | best=0.00006271

22:52:44 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.242649 | val_mse_raw=0.00005715 | best=0.00005715

22:52:45 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.174500 | val_mse_raw=0.00004839 | best=0.00004839

22:52:45 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.148281 | val_mse_raw=0.00004692 | best=0.00004692

22:52:46 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.147084 | val_mse_raw=0.00004454 | best=0.00004454

22:52:46 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.128875 | val_mse_raw=0.00004228 | best=0.00004228

22:52:47 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.119594 | val_mse_raw=0.00004383 | best=0.00004228

22:52:47 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.114471 | val_mse_raw=0.00004885 | best=0.00004228

22:52:48 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.114404 | val_mse_raw=0.00004713 | best=0.00004228

22:52:49 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.108205 | val_mse_raw=0.00004938 | best=0.00004228

22:52:49 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.104284 | val_mse_raw=0.00004519 | best=0.00004228

22:52:50 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.096970 | val_mse_raw=0.00005499 | best=0.00004228

22:52:50 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.094259 | val_mse_raw=0.00004944 | best=0.00004228

22:52:51 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.095497 | val_mse_raw=0.00005063 | best=0.00004228

22:52:51 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.094944 | val_mse_raw=0.00004256 | best=0.00004228

22:52:52 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.091152 | val_mse_raw=0.00004925 | best=0.00004228
22:52:52 | INFO    | train_LSTM_baseline | Early stopping at epoch 25

22:52:53 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.336518 | val_mse_raw=0.00006611 | best=0.00006611

22:52:54 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.299591 | val_mse_raw=0.00006610 | best=0.00006610

22:52:54 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.291894 | val_mse_raw=0.00006604 | best=0.00006604

22:52:55 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.282845 | val_mse_raw=0.00005944 | best=0.00005944

22:52:56 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.165293 | val_mse_raw=0.00004560 | best=0.00004560

22:52:57 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.132201 | val_mse_raw=0.00004222 | best=0.00004222

22:52:58 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.123319 | val_mse_raw=0.00004473 | best=0.00004222

22:53:00 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.120738 | val_mse_raw=0.00004125 | best=0.00004125

22:53:01 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.121302 | val_mse_raw=0.00004137 | best=0.00004125

22:53:02 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.110014 | val_mse_raw=0.00004009 | best=0.00004009

22:53:03 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.108906 | val_mse_raw=0.00003806 | best=0.00003806

22:53:04 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.104361 | val_mse_raw=0.00004033 | best=0.00003806

22:53:05 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.101074 | val_mse_raw=0.00004339 | best=0.00003806

22:53:06 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.087377 | val_mse_raw=0.00004123 | best=0.00003806

22:53:07 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.087669 | val_mse_raw=0.00004457 | best=0.00003806

22:53:08 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.073085 | val_mse_raw=0.00005467 | best=0.00003806

22:53:09 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.072982 | val_mse_raw=0.00004629 | best=0.00003806

22:53:10 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.065898 | val_mse_raw=0.00004779 | best=0.00003806

22:53:11 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.053331 | val_mse_raw=0.00005003 | best=0.00003806

22:53:12 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.042653 | val_mse_raw=0.00005313 | best=0.00003806

22:53:13 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.035723 | val_mse_raw=0.00004839 | best=0.00003806
22:53:13 | INFO    | train_LSTM_baseline | Early stopping at epoch 21

22:53:14 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.911326 | val_mse_raw=0.00007244 | best=0.00007244

22:53:14 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.312010 | val_mse_raw=0.00006806 | best=0.00006806

22:53:15 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.287366 | val_mse_raw=0.00006677 | best=0.00006677

22:53:16 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.286014 | val_mse_raw=0.00006668 | best=0.00006668

22:53:17 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.283384 | val_mse_raw=0.00006560 | best=0.00006560

22:53:17 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.257233 | val_mse_raw=0.00006212 | best=0.00006212

22:53:18 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.181847 | val_mse_raw=0.00005034 | best=0.00005034

22:53:19 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.136053 | val_mse_raw=0.00004584 | best=0.00004584

22:53:20 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.119964 | val_mse_raw=0.00004523 | best=0.00004523

22:53:20 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.113208 | val_mse_raw=0.00004407 | best=0.00004407

22:53:21 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.108585 | val_mse_raw=0.00004250 | best=0.00004250

22:53:22 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.103351 | val_mse_raw=0.00004176 | best=0.00004176

22:53:23 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.099545 | val_mse_raw=0.00004412 | best=0.00004176

22:53:24 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.093742 | val_mse_raw=0.00004497 | best=0.00004176

22:53:24 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.097667 | val_mse_raw=0.00004421 | best=0.00004176

22:53:25 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.085631 | val_mse_raw=0.00004913 | best=0.00004176

22:53:26 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.082725 | val_mse_raw=0.00004844 | best=0.00004176

22:53:27 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.083429 | val_mse_raw=0.00004431 | best=0.00004176

22:53:27 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.068866 | val_mse_raw=0.00004557 | best=0.00004176

22:53:28 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.062792 | val_mse_raw=0.00005305 | best=0.00004176

22:53:29 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.056802 | val_mse_raw=0.00005901 | best=0.00004176

22:53:30 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.054193 | val_mse_raw=0.00005486 | best=0.00004176
22:53:30 | INFO    | train_LSTM_baseline | Early stopping at epoch 22

22:53:30 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.225006 | val_mse_raw=0.00008829 | best=0.00008829

22:53:31 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.311127 | val_mse_raw=0.00006962 | best=0.00006962

22:53:32 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.288606 | val_mse_raw=0.00006638 | best=0.00006638

22:53:33 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.286498 | val_mse_raw=0.00006631 | best=0.00006631

22:53:34 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.284609 | val_mse_raw=0.00006597 | best=0.00006597

22:53:35 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.259706 | val_mse_raw=0.00006232 | best=0.00006232

22:53:36 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.189508 | val_mse_raw=0.00005052 | best=0.00005052

22:53:36 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.151407 | val_mse_raw=0.00004764 | best=0.00004764

22:53:37 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.134044 | val_mse_raw=0.00004728 | best=0.00004728

22:53:38 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.129929 | val_mse_raw=0.00004386 | best=0.00004386

22:53:39 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.117871 | val_mse_raw=0.00004338 | best=0.00004338

22:53:40 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.117282 | val_mse_raw=0.00004175 | best=0.00004175

22:53:40 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.125983 | val_mse_raw=0.00004192 | best=0.00004175

22:53:41 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.117732 | val_mse_raw=0.00004202 | best=0.00004175

22:53:42 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.111930 | val_mse_raw=0.00004215 | best=0.00004175

22:53:43 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.101979 | val_mse_raw=0.00004292 | best=0.00004175

22:53:44 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.104823 | val_mse_raw=0.00004444 | best=0.00004175

22:53:44 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.115602 | val_mse_raw=0.00004195 | best=0.00004175

22:53:45 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.095425 | val_mse_raw=0.00004223 | best=0.00004175

22:53:46 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.088062 | val_mse_raw=0.00004478 | best=0.00004175

22:53:47 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.080759 | val_mse_raw=0.00005205 | best=0.00004175

22:53:48 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.082551 | val_mse_raw=0.00004723 | best=0.00004175
22:53:48 | INFO    | train_LSTM_baseline | Early stopping at epoch 22

22:53:49 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.313994 | val_mse_raw=0.00006801 | best=0.00006801

22:53:49 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.293400 | val_mse_raw=0.00006468 | best=0.00006468

22:53:50 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.285522 | val_mse_raw=0.00005562 | best=0.00005562

22:53:51 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.201383 | val_mse_raw=0.00005687 | best=0.00005562

22:53:51 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.185206 | val_mse_raw=0.00004812 | best=0.00004812

22:53:52 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.164447 | val_mse_raw=0.00005894 | best=0.00004812

22:53:53 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.174146 | val_mse_raw=0.00005588 | best=0.00004812

22:53:53 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.152131 | val_mse_raw=0.00006054 | best=0.00004812

22:53:54 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.146051 | val_mse_raw=0.00006260 | best=0.00004812

22:53:55 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.151697 | val_mse_raw=0.00005836 | best=0.00004812

22:53:55 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.146003 | val_mse_raw=0.00005633 | best=0.00004812

22:53:56 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.139955 | val_mse_raw=0.00005823 | best=0.00004812

22:53:57 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.130997 | val_mse_raw=0.00004932 | best=0.00004812

22:53:57 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.136893 | val_mse_raw=0.00004711 | best=0.00004711

22:53:58 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.128588 | val_mse_raw=0.00005141 | best=0.00004711

22:53:59 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.123508 | val_mse_raw=0.00004647 | best=0.00004647

22:54:00 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.110328 | val_mse_raw=0.00004821 | best=0.00004647

22:54:00 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.111254 | val_mse_raw=0.00005030 | best=0.00004647

22:54:01 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.115486 | val_mse_raw=0.00004556 | best=0.00004556

22:54:02 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.114398 | val_mse_raw=0.00004821 | best=0.00004556

22:54:02 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.113358 | val_mse_raw=0.00004847 | best=0.00004556

22:54:03 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.113967 | val_mse_raw=0.00005061 | best=0.00004556

22:54:04 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.121894 | val_mse_raw=0.00004557 | best=0.00004556

22:54:04 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.106516 | val_mse_raw=0.00004631 | best=0.00004556

22:54:05 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.102225 | val_mse_raw=0.00005117 | best=0.00004556

22:54:06 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.116657 | val_mse_raw=0.00003766 | best=0.00003766

22:54:06 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.121229 | val_mse_raw=0.00004419 | best=0.00003766

22:54:07 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.109860 | val_mse_raw=0.00004460 | best=0.00003766

22:54:08 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.111996 | val_mse_raw=0.00004431 | best=0.00003766

22:54:08 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.107768 | val_mse_raw=0.00005209 | best=0.00003766

22:54:09 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.110592 | val_mse_raw=0.00004235 | best=0.00003766

22:54:10 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.101633 | val_mse_raw=0.00004450 | best=0.00003766

22:54:11 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.092809 | val_mse_raw=0.00004282 | best=0.00003766

22:54:11 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.086006 | val_mse_raw=0.00004969 | best=0.00003766

22:54:12 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.087424 | val_mse_raw=0.00004913 | best=0.00003766

22:54:13 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.090220 | val_mse_raw=0.00004598 | best=0.00003766
22:54:13 | INFO    | train_LSTM_baseline | Early stopping at epoch 36

22:54:14 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=4.485797 | val_mse_raw=0.00007083 | best=0.00007083

22:54:15 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.287727 | val_mse_raw=0.00006680 | best=0.00006680

22:54:16 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.274128 | val_mse_raw=0.00006413 | best=0.00006413

22:54:17 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.210245 | val_mse_raw=0.00005470 | best=0.00005470

22:54:18 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.137916 | val_mse_raw=0.00004899 | best=0.00004899

22:54:19 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.121960 | val_mse_raw=0.00004550 | best=0.00004550

22:54:20 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.116339 | val_mse_raw=0.00004379 | best=0.00004379

22:54:22 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.111838 | val_mse_raw=0.00004240 | best=0.00004240

22:54:23 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.101202 | val_mse_raw=0.00004327 | best=0.00004240

22:54:24 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.097143 | val_mse_raw=0.00004318 | best=0.00004240

22:54:25 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.089378 | val_mse_raw=0.00004698 | best=0.00004240

22:54:26 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.099241 | val_mse_raw=0.00005392 | best=0.00004240

22:54:27 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.081750 | val_mse_raw=0.00005308 | best=0.00004240

22:54:28 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.070024 | val_mse_raw=0.00006162 | best=0.00004240

22:54:29 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.059915 | val_mse_raw=0.00004885 | best=0.00004240

22:54:31 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.053115 | val_mse_raw=0.00005753 | best=0.00004240

22:54:32 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.049873 | val_mse_raw=0.00005362 | best=0.00004240

22:54:33 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.048192 | val_mse_raw=0.00004985 | best=0.00004240
22:54:33 | INFO    | train_LSTM_baseline | Early stopping at epoch 18

22:54:34 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.312785 | val_mse_raw=0.00006785 | best=0.00006785

22:54:34 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.320194 | val_mse_raw=0.01152318 | best=0.00006785

22:54:35 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.294912 | val_mse_raw=0.00005564 | best=0.00005564

22:54:36 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.158575 | val_mse_raw=0.00004532 | best=0.00004532

22:54:36 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.136064 | val_mse_raw=0.00004381 | best=0.00004381

22:54:37 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.122710 | val_mse_raw=0.00004236 | best=0.00004236

22:54:38 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.124308 | val_mse_raw=0.00003872 | best=0.00003872

22:54:39 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.108210 | val_mse_raw=0.00003779 | best=0.00003779

22:54:39 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.101256 | val_mse_raw=0.00003862 | best=0.00003779

22:54:40 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.109294 | val_mse_raw=0.00003623 | best=0.00003623

22:54:41 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.103362 | val_mse_raw=0.00004031 | best=0.00003623

22:54:41 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.103963 | val_mse_raw=0.00004435 | best=0.00003623

22:54:42 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.094744 | val_mse_raw=0.00004489 | best=0.00003623

22:54:43 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.088965 | val_mse_raw=0.00004552 | best=0.00003623

22:54:43 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.126073 | val_mse_raw=0.00004528 | best=0.00003623

22:54:44 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.099657 | val_mse_raw=0.00004460 | best=0.00003623

22:54:45 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.087192 | val_mse_raw=0.00004557 | best=0.00003623

22:54:45 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.082710 | val_mse_raw=0.00005016 | best=0.00003623

22:54:46 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.075291 | val_mse_raw=0.00004615 | best=0.00003623

22:54:47 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.076946 | val_mse_raw=0.00005200 | best=0.00003623
22:54:47 | INFO    | train_LSTM_baseline | Early stopping at epoch 20

22:54:48 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.871198 | val_mse_raw=0.00006486 | best=0.00006486

22:54:48 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.283956 | val_mse_raw=0.00006427 | best=0.00006427

22:54:49 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.232242 | val_mse_raw=0.00005338 | best=0.00005338

22:54:50 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.142951 | val_mse_raw=0.00004322 | best=0.00004322

22:54:50 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.121902 | val_mse_raw=0.00004081 | best=0.00004081

22:54:51 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.112168 | val_mse_raw=0.00004105 | best=0.00004081

22:54:52 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.106404 | val_mse_raw=0.00004361 | best=0.00004081

22:54:53 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.097935 | val_mse_raw=0.00004459 | best=0.00004081

22:54:53 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.097331 | val_mse_raw=0.00004044 | best=0.00004044

22:54:54 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.089652 | val_mse_raw=0.00003887 | best=0.00003887

22:54:55 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.085348 | val_mse_raw=0.00004306 | best=0.00003887

22:54:55 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.083294 | val_mse_raw=0.00003916 | best=0.00003887

22:54:56 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.072855 | val_mse_raw=0.00004601 | best=0.00003887

22:54:57 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.067267 | val_mse_raw=0.00004412 | best=0.00003887

22:54:57 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.061228 | val_mse_raw=0.00004601 | best=0.00003887

22:54:58 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.053012 | val_mse_raw=0.00004694 | best=0.00003887

22:54:59 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.046655 | val_mse_raw=0.00005346 | best=0.00003887

22:55:00 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.041919 | val_mse_raw=0.00005260 | best=0.00003887

22:55:00 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.055960 | val_mse_raw=0.00004413 | best=0.00003887

22:55:01 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.050240 | val_mse_raw=0.00004145 | best=0.00003887
22:55:01 | INFO    | train_LSTM_baseline | Early stopping at epoch 20

22:55:02 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=6.804749 | val_mse_raw=0.00006471 | best=0.00006471

22:55:02 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.284373 | val_mse_raw=0.00006514 | best=0.00006471

22:55:03 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.267751 | val_mse_raw=0.00006329 | best=0.00006329

22:55:04 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.199916 | val_mse_raw=0.00005438 | best=0.00005438

22:55:05 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.138881 | val_mse_raw=0.00005230 | best=0.00005230

22:55:05 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.125718 | val_mse_raw=0.00005123 | best=0.00005123

22:55:06 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.112746 | val_mse_raw=0.00004554 | best=0.00004554

22:55:07 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.103050 | val_mse_raw=0.00004855 | best=0.00004554

22:55:07 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.100677 | val_mse_raw=0.00004889 | best=0.00004554

22:55:08 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.092896 | val_mse_raw=0.00004769 | best=0.00004554

22:55:09 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.091185 | val_mse_raw=0.00004862 | best=0.00004554

22:55:09 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.084907 | val_mse_raw=0.00004849 | best=0.00004554

22:55:10 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.081968 | val_mse_raw=0.00005126 | best=0.00004554

22:55:11 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.077686 | val_mse_raw=0.00005605 | best=0.00004554

22:55:12 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.073439 | val_mse_raw=0.00005391 | best=0.00004554

22:55:12 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.065016 | val_mse_raw=0.00005432 | best=0.00004554

22:55:13 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.064072 | val_mse_raw=0.00005480 | best=0.00004554
22:55:13 | INFO    | train_LSTM_baseline | Early stopping at epoch 17

22:55:14 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=3.091478 | val_mse_raw=0.00006487 | best=0.00006487

22:55:14 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.284635 | val_mse_raw=0.00006513 | best=0.00006487

22:55:14 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.285768 | val_mse_raw=0.00006552 | best=0.00006487

22:55:15 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.283927 | val_mse_raw=0.00006479 | best=0.00006479

22:55:15 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.288980 | val_mse_raw=0.00006471 | best=0.00006471

22:55:16 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.276685 | val_mse_raw=0.00006399 | best=0.00006399

22:55:16 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.237794 | val_mse_raw=0.00005626 | best=0.00005626

22:55:17 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.166914 | val_mse_raw=0.00004901 | best=0.00004901

22:55:17 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.138955 | val_mse_raw=0.00004315 | best=0.00004315

22:55:18 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.125455 | val_mse_raw=0.00004135 | best=0.00004135

22:55:18 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.119439 | val_mse_raw=0.00004281 | best=0.00004135

22:55:19 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.112295 | val_mse_raw=0.00003951 | best=0.00003951

22:55:19 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.107777 | val_mse_raw=0.00004148 | best=0.00003951

22:55:19 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.104355 | val_mse_raw=0.00004063 | best=0.00003951

22:55:20 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.097886 | val_mse_raw=0.00004503 | best=0.00003951

22:55:20 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.093665 | val_mse_raw=0.00004675 | best=0.00003951

22:55:21 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.089890 | val_mse_raw=0.00005241 | best=0.00003951

22:55:21 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.087639 | val_mse_raw=0.00004944 | best=0.00003951

22:55:22 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.087728 | val_mse_raw=0.00005180 | best=0.00003951

22:55:22 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.081428 | val_mse_raw=0.00005185 | best=0.00003951

22:55:23 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.075753 | val_mse_raw=0.00004476 | best=0.00003951

22:55:23 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.085240 | val_mse_raw=0.00004490 | best=0.00003951
22:55:23 | INFO    | train_LSTM_baseline | Early stopping at epoch 22
22:55:23 | INFO    | train_LSTM_baseline | Best val MSE (raw scale): 0.00003623
22:55:23 | INFO    | train_LSTM_baseline | Best params: {'hidden_size': 64, 'n_layers': 3, 'dropout': 0.24485885415905723, 'lr': 0.009818247569037455, 'batch_size': 32, 'seq_len': 21}

22:55:24 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.312785 | val_mse_raw=0.00006785 | best=0.00006785

22:55:25 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.320194 | val_mse_raw=0.01152318 | best=0.00006785

22:55:26 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.294912 | val_mse_raw=0.00005564 | best=0.00005564

22:55:26 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.158575 | val_mse_raw=0.00004532 | best=0.00004532

22:55:27 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.136064 | val_mse_raw=0.00004381 | best=0.00004381

22:55:28 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.122710 | val_mse_raw=0.00004236 | best=0.00004236

22:55:28 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.124308 | val_mse_raw=0.00003872 | best=0.00003872

22:55:29 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.108210 | val_mse_raw=0.00003779 | best=0.00003779

22:55:30 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.101256 | val_mse_raw=0.00003862 | best=0.00003779

22:55:30 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.109294 | val_mse_raw=0.00003623 | best=0.00003623

22:55:31 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.103362 | val_mse_raw=0.00004031 | best=0.00003623

22:55:32 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.103963 | val_mse_raw=0.00004435 | best=0.00003623

22:55:33 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.094744 | val_mse_raw=0.00004489 | best=0.00003623

22:55:33 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.088965 | val_mse_raw=0.00004552 | best=0.00003623

22:55:34 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.126073 | val_mse_raw=0.00004528 | best=0.00003623

22:55:35 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.099657 | val_mse_raw=0.00004460 | best=0.00003623

22:55:36 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.087192 | val_mse_raw=0.00004557 | best=0.00003623

22:55:36 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.082710 | val_mse_raw=0.00005016 | best=0.00003623

22:55:37 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.075291 | val_mse_raw=0.00004615 | best=0.00003623

22:55:38 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.076946 | val_mse_raw=0.00005200 | best=0.00003623
22:55:38 | INFO    | train_LSTM_baseline | Early stopping at epoch 20
22:55:38 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00003623
22:55:38 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.8221169739263132e-05, 'RMSE': 0.004268626216799021, 'MAE': 0.002795534674078226, 'n_test_windows': 1461}
22:55:38 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_B_seed42.pt
22:55:38 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_B_seed42_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 3,
    "dropout": 0.24485885415905723,
    "lr": 0.009818247569037455,
    "batch_size": 32,
    "seq_len": 21
  },
  "best_val_mse_raw": 3.623278462328017e-05,
  "retrained_val_mse_raw": 3.623278462328017e-05,
  "test_metrics": {
    "MSE": 1.8221169739263132e-05,
    "RMSE": 0.004268626216799021,
    "MAE": 0.002795534674078226,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish",
    "vix",
    "vix_log_change",
    "vix3m_minus_vix"
  ],
  "target": "realized_vol_21d",
  "n_trials": 20,
  "seed": 42,
  "fixed_hparams_source": null
}

  [seed 42]  hparams JSON saved → hparams_lstm_baseline_B.json
================================================================================
[variant B  seed 43]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish vix vix_log_change vix3m_minus_vix --output-prefix lstm_baseline_B_seed43 --seed 43 --fixed-hparams /content/repo/models/hparams_lstm_baseline_B.json
--------------------------------------------------------------------------------

22:55:41 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish', 'vix', 'vix_log_change', 'vix3m_minus_vix']
22:55:41 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:55:41 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:55:41 | INFO    | train_LSTM_baseline | n_features=10 | rows — train=2034 val=1089 test=1481
22:55:41 | INFO    | train_LSTM_baseline | Skipping Optuna — using fixed hparams from /content/repo/models/hparams_lstm_baseline_B.json
22:55:41 | INFO    | train_LSTM_baseline | Fixed params: {'hidden_size': 64, 'n_layers': 3, 'dropout': 0.24485885415905723, 'lr': 0.009818247569037455, 'batch_size': 32, 'seq_len': 21}

22:55:43 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.479990 | val_mse_raw=0.00006838 | best=0.00006838

22:55:43 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.288415 | val_mse_raw=0.00006609 | best=0.00006609

22:55:44 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.290740 | val_mse_raw=0.00006502 | best=0.00006502

22:55:45 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.289950 | val_mse_raw=0.00006581 | best=0.00006502

22:55:46 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.292468 | val_mse_raw=0.00007014 | best=0.00006502

22:55:46 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.271523 | val_mse_raw=0.00005675 | best=0.00005675

22:55:47 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.284630 | val_mse_raw=0.00005218 | best=0.00005218

22:55:48 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.170534 | val_mse_raw=0.00004352 | best=0.00004352

22:55:49 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.129592 | val_mse_raw=0.00004554 | best=0.00004352

22:55:50 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.127372 | val_mse_raw=0.00003883 | best=0.00003883

22:55:51 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.118218 | val_mse_raw=0.00003956 | best=0.00003883

22:55:51 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.116526 | val_mse_raw=0.00003819 | best=0.00003819

22:55:52 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.112071 | val_mse_raw=0.00003926 | best=0.00003819

22:55:53 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.106383 | val_mse_raw=0.00004407 | best=0.00003819

22:55:54 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.126506 | val_mse_raw=0.00004390 | best=0.00003819

22:55:55 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.120241 | val_mse_raw=0.00004521 | best=0.00003819

22:55:55 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.111033 | val_mse_raw=0.00004159 | best=0.00003819

22:55:56 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.096685 | val_mse_raw=0.00004537 | best=0.00003819

22:55:57 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.094271 | val_mse_raw=0.00004325 | best=0.00003819

22:55:58 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.088485 | val_mse_raw=0.00004636 | best=0.00003819

22:55:59 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.086022 | val_mse_raw=0.00004601 | best=0.00003819

22:55:59 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.090896 | val_mse_raw=0.00004234 | best=0.00003819
22:55:59 | INFO    | train_LSTM_baseline | Early stopping at epoch 22
22:55:59 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00003819
22:56:00 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.645283555262722e-05, 'RMSE': 0.004056209698319435, 'MAE': 0.0026712054386734962, 'n_test_windows': 1461}
22:56:00 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_B_seed43.pt
22:56:00 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_B_seed43_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 3,
    "dropout": 0.24485885415905723,
    "lr": 0.009818247569037455,
    "batch_size": 32,
    "seq_len": 21
  },
  "best_val_mse_raw": NaN,
  "retrained_val_mse_raw": 3.8186470192158595e-05,
  "test_metrics": {
    "MSE": 1.645283555262722e-05,
    "RMSE": 0.004056209698319435,
    "MAE": 0.0026712054386734962,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish",
    "vix",
    "vix_log_change",
    "vix3m_minus_vix"
  ],
  "target": "realized_vol_21d",
  "n_trials": 0,
  "seed": 43,
  "fixed_hparams_source": "/content/repo/models/hparams_lstm_baseline_B.json"
}

================================================================================
[variant B  seed 44]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_baseline.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish vix vix_log_change vix3m_minus_vix --output-prefix lstm_baseline_B_seed44 --seed 44 --fixed-hparams /content/repo/models/hparams_lstm_baseline_B.json
--------------------------------------------------------------------------------

22:56:03 | INFO    | train_LSTM_baseline | Features: ['log_return', 'abs_return', 'oc_return', 'intraday_range', 'relative_volume_21d', 'bullish', 'bearish', 'vix', 'vix_log_change', 'vix3m_minus_vix']
22:56:03 | INFO    | train_LSTM_baseline | Target  : realized_vol_21d
22:56:03 | INFO    | train_LSTM_baseline | Split sizes — train=3710, val=1089, test=1481
22:56:03 | INFO    | train_LSTM_baseline | n_features=10 | rows — train=2034 val=1089 test=1481
22:56:03 | INFO    | train_LSTM_baseline | Skipping Optuna — using fixed hparams from /content/repo/models/hparams_lstm_baseline_B.json
22:56:03 | INFO    | train_LSTM_baseline | Fixed params: {'hidden_size': 64, 'n_layers': 3, 'dropout': 0.24485885415905723, 'lr': 0.009818247569037455, 'batch_size': 32, 'seq_len': 21}

22:56:04 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=1.223500 | val_mse_raw=0.00006684 | best=0.00006684

22:56:05 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.288782 | val_mse_raw=0.00006552 | best=0.00006552

22:56:06 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.291561 | val_mse_raw=0.00006637 | best=0.00006552

22:56:07 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.302688 | val_mse_raw=0.00006629 | best=0.00006552

22:56:08 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.292081 | val_mse_raw=0.00006767 | best=0.00006552

22:56:08 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.295302 | val_mse_raw=0.00006488 | best=0.00006488

22:56:09 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.290990 | val_mse_raw=0.00006311 | best=0.00006311

22:56:10 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.232286 | val_mse_raw=0.00005215 | best=0.00005215

22:56:11 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.152279 | val_mse_raw=0.00004473 | best=0.00004473

22:56:12 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.146321 | val_mse_raw=0.00004310 | best=0.00004310

22:56:12 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.127633 | val_mse_raw=0.00003787 | best=0.00003787

22:56:13 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.129638 | val_mse_raw=0.00003941 | best=0.00003787

22:56:14 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.117951 | val_mse_raw=0.00003852 | best=0.00003787

22:56:15 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.118819 | val_mse_raw=0.00004339 | best=0.00003787

22:56:16 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.116573 | val_mse_raw=0.00003995 | best=0.00003787

22:56:16 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.111000 | val_mse_raw=0.00003849 | best=0.00003787

22:56:17 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.100411 | val_mse_raw=0.00003951 | best=0.00003787

22:56:18 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.095782 | val_mse_raw=0.00003944 | best=0.00003787

22:56:19 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.102976 | val_mse_raw=0.00004135 | best=0.00003787

22:56:19 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.090046 | val_mse_raw=0.00003748 | best=0.00003748

22:56:20 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.090942 | val_mse_raw=0.00004397 | best=0.00003748

22:56:21 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.089935 | val_mse_raw=0.00003766 | best=0.00003748

22:56:22 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.088144 | val_mse_raw=0.00003722 | best=0.00003722

22:56:22 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.071331 | val_mse_raw=0.00003893 | best=0.00003722

22:56:23 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.062981 | val_mse_raw=0.00003970 | best=0.00003722

22:56:24 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.065612 | val_mse_raw=0.00004565 | best=0.00003722

22:56:25 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.057733 | val_mse_raw=0.00004105 | best=0.00003722

22:56:26 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.048230 | val_mse_raw=0.00004124 | best=0.00003722

22:56:26 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.039173 | val_mse_raw=0.00004837 | best=0.00003722

22:56:27 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.041733 | val_mse_raw=0.00005446 | best=0.00003722

22:56:28 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.036082 | val_mse_raw=0.00004736 | best=0.00003722

22:56:29 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.034059 | val_mse_raw=0.00005050 | best=0.00003722

22:56:29 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.029965 | val_mse_raw=0.00005267 | best=0.00003722
22:56:29 | INFO    | train_LSTM_baseline | Early stopping at epoch 33
22:56:29 | INFO    | train_LSTM_baseline | Final retrain — best val MSE (raw scale): 0.00003722
22:56:29 | INFO    | train_LSTM_baseline | Test metrics: {'MSE': 1.9314065866637975e-05, 'RMSE': 0.0043947771191596985, 'MAE': 0.0028576727490872145, 'n_test_windows': 1461}
22:56:29 | INFO    | train_LSTM_baseline | Saved model → /content/repo/models/lstm_baseline_B_seed44.pt
22:56:29 | INFO    | train_LSTM_baseline | Saved scaler → /content/repo/models/lstm_baseline_B_seed44_scaler.joblib

=== Baseline LSTM results ===
{
  "best_params": {
    "hidden_size": 64,
    "n_layers": 3,
    "dropout": 0.24485885415905723,
    "lr": 0.009818247569037455,
    "batch_size": 32,
    "seq_len": 21
  },
  "best_val_mse_raw": NaN,
  "retrained_val_mse_raw": 3.721631583175622e-05,
  "test_metrics": {
    "MSE": 1.9314065866637975e-05,
    "RMSE": 0.0043947771191596985,
    "MAE": 0.0028576727490872145,
    "n_test_windows": 1461
  },
  "features": [
    "log_return",
    "abs_return",
    "oc_return",
    "intraday_range",
    "relative_volume_21d",
    "bullish",
    "bearish",
    "vix",
    "vix_log_change",
    "vix3m_minus_vix"
  ],
  "target": "realized_vol_21d",
  "n_trials": 0,
  "seed": 44,
  "fixed_hparams_source": "/content/repo/models/hparams_lstm_baseline_B.json"
}

## Aggregate per-variant results: mean ± std across 3 seeds

In [5]:
import numpy as np

marker = "=== Baseline LSTM results ==="
per_seed_results = {}

for vname, vdata in variant_outputs.items():
    per_seed_results[vname] = {}
    for seed, info in vdata["seeds"].items():
        if info.get("status") != "ok":
            continue
        text = info["output"]
        idx = text.find(marker)
        if idx == -1: continue
        try:
            per_seed_results[vname][seed] = json.loads(text[idx + len(marker):].strip())
        except json.JSONDecodeError:
            continue

# Build a long-form table: one row per (variant, seed)
rows = []
for vname, seeds_dict in per_seed_results.items():
    for seed, r in seeds_dict.items():
        rows.append({
            "variant":  vname,
            "seed":     seed,
            "test_MSE": r["test_metrics"]["MSE"],
            "test_RMSE": r["test_metrics"]["RMSE"],
            "test_MAE": r["test_metrics"]["MAE"],
            "seq_len":  r["best_params"]["seq_len"],
            "hidden_size": r["best_params"]["hidden_size"],
        })
per_seed_df = pd.DataFrame(rows)
print("Per-(variant, seed) test metrics:")
display(per_seed_df)

# Aggregate: mean ± std per variant across seeds
agg_rows = []
for vname, seeds_dict in per_seed_results.items():
    if not seeds_dict:
        continue
    mses  = [r["test_metrics"]["MSE"]  for r in seeds_dict.values()]
    rmses = [r["test_metrics"]["RMSE"] for r in seeds_dict.values()]
    maes  = [r["test_metrics"]["MAE"]  for r in seeds_dict.values()]
    agg_rows.append({
        "variant":     vname,
        "n_seeds":     len(seeds_dict),
        "MSE_mean":    np.mean(mses),
        "MSE_std":     np.std(mses, ddof=1) if len(mses) > 1 else 0.0,
        "RMSE_mean":   np.mean(rmses),
        "RMSE_std":    np.std(rmses, ddof=1) if len(rmses) > 1 else 0.0,
        "MAE_mean":    np.mean(maes),
        "MAE_std":     np.std(maes, ddof=1) if len(maes) > 1 else 0.0,
    })
agg_df = pd.DataFrame(agg_rows).set_index("variant")
print("\nPer-variant aggregate (mean ± std across seeds):")
agg_df

Per-(variant, seed) test metrics:

   variant  seed  test_MSE  test_RMSE  test_MAE  seq_len  hidden_size
0        O    42  0.000015   0.003855  0.002461       21           64
1        O    43  0.000021   0.004564  0.003077       21           64
2        O    44  0.000017   0.004180  0.002664       21           64
3        A    42  0.000013   0.003655  0.002471       42          128
4        A    43  0.000015   0.003867  0.002660       42          128
5        A    44  0.000019   0.004317  0.002814       42          128
6        H    42  0.000016   0.003981  0.002575       21           64
7        H    43  0.000015   0.003832  0.002545       21           64
8        H    44  0.000014   0.003724  0.002470       21           64
9        B    42  0.000018   0.004269  0.002796       21           64
10       B    43  0.000016   0.004056  0.002671       21           64
11       B    44  0.000019   0.004395  0.002858       21           64

Per-variant aggregate (mean ± std across seeds):

,n_seeds,MSE_mean,MSE_std,RMSE_mean,RMSE_std,MAE_mean,MAE_std
variant,,,,,,,
O,3,0.000018,2.991382e-06,0.004200,0.000355,0.002734,0.000314
A,3,0.000016,2.710291e-06,0.003946,0.000338,0.002648,0.000172
H,3,0.000015,9.942422e-07,0.003846,0.000129,0.002530,0.000054
B,3,0.000018,1.443841e-06,0.004240,0.000171,0.002775,0.000095

## Summary (fill in after execution)

From the aggregate table above:

- **MSE_std / MSE_mean** is the relative standard error across seeds. If it's > 10 %, single-seed metrics are unreliable (justifies multi-seed reporting in the paper). Historical reference: ensemble MSE swung +53 % between single-seed reruns.
- Variants with **smaller MSE_std** are more stable under seed variation — they're candidates for the paper's "robust finding" column.

DM significance testing across variants happens in nb 06 (within-variant) and nb 07 (cross-variant), operating on the mean-of-seed-predictions.

## Saved artifacts

| File | Description |
|---|---|
| `models/lstm_baseline_{O,H,B}_seed{42,43,44}.pt` | 9 variant baselines (O, H, B × 3 seeds) |
| `models/lstm_baseline_seed{42,43,44}.pt` | 3 variant-A baselines (no variant suffix by convention) |
| `models/lstm_baseline*_scaler.joblib` | Matching StandardScaler for each `.pt` |
| `models/hparams_lstm_baseline*.json` | Seed 42's best_params — used by seeds 43/44 via `--fixed-hparams` |

Total: 12 checkpoints + 12 scalers + 4 hparams JSONs.

Each `.pt` contains `state_dict`, `hyperparameters`, `features`, `target`, `seed`, and (for seeds 43/44) `fixed_hparams_source`.