# 05 — Regime-Specific LSTM Training (3 variants × 3 seeds)

Trains **3 variants × 2 regimes × 3 seeds = 18 runs** by invoking `src/train_LSTM_regime.py` with `--regime both` (so each invocation covers calm + volatile sequentially). Seed 42 of each variant does full Optuna per regime; seeds 43 / 44 reuse seed 42's JSON via `--fixed-hparams`, skipping Optuna entirely.

**Variant H is intentionally not here** — H is a single-LSTM architectural variant, no regime-split ensemble.

| Variant | LSTM features | HMM source | Checkpoints |
|---|---|---|---|
| **O** | stationary (5) | `hmm_winner_O.joblib` + `regime_probabilities_O.parquet` | `lstm_{calm,volatile}_O_seed{N}.pt` |
| **A** | + sentiment (7) | `hmm_winner.joblib` + `regime_probabilities.parquet` | `lstm_{calm,volatile}_seed{N}.pt` |
| **B** | + VIX family (10) | `hmm_winner_B.joblib` + `regime_probabilities_B.parquet` | `lstm_{calm,volatile}_B_seed{N}.pt` |

Per Design 2: each variant uses its **own** HMM's Viterbi labels for window filtering. Variant B's regime LSTMs see the VIX-informed regime labels, not variant A's.

**Per-regime pipeline per seed** (handled inside `train_LSTM_regime.py`):

1. Load splits + variant-specific regime probs.
2. For each regime (calm, volatile):
   - Build `RegimeWindowDataset` filtering windows by majority Viterbi state.
   - Run Optuna (seed 42) or skip via `--fixed-hparams` (seeds 43/44).
   - Retrain with best params, early-stopping on regime-filtered val.
   - Evaluate on full test set (needed for ensemble blending in nb 06).
   - Save `lstm_{regime}{suffix}_seed{N}.pt` + `_scaler.joblib`.

In [1]:
import json
import subprocess
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path().resolve().parent
SCRIPT = REPO_ROOT / "src" / "train_LSTM_regime.py"
assert SCRIPT.exists(), f"Missing: {SCRIPT}"
sys.path.insert(0, str(REPO_ROOT))

import config

print(f"Script: {SCRIPT}")
print(f"Python: {sys.executable}")

Script: /content/repo/src/train_LSTM_regime.py
Python: /usr/bin/python3

## Prerequisite check

Verifies all 9 HMM artifacts from nb 03 exist before starting any training.

In [2]:
required_artifacts = {
    "Variant O HMM winner":      config.MODELS_DIR / "hmm_winner_O.joblib",
    "Variant O HMM meta":        config.MODELS_DIR / "hmm_meta_O.joblib",
    "Variant O regime probs":    config.DATA_PROCESSED / "regime_probabilities_O.parquet",
    "Variant A HMM winner":      config.MODELS_DIR / "hmm_winner.joblib",
    "Variant A HMM meta":        config.MODELS_DIR / "hmm_meta.joblib",
    "Variant A regime probs":    config.DATA_PROCESSED / "regime_probabilities.parquet",
    "Variant B HMM winner":      config.MODELS_DIR / "hmm_winner_B.joblib",
    "Variant B HMM meta":        config.MODELS_DIR / "hmm_meta_B.joblib",
    "Variant B regime probs":    config.DATA_PROCESSED / "regime_probabilities_B.parquet",
}
missing = {k: str(v) for k, v in required_artifacts.items() if not v.exists()}
if missing:
    raise RuntimeError(
        "Missing HMM artifacts:\n" +
        "\n".join(f"  {k}: {v}" for k, v in missing.items()) +
        "\n\nRun nb 03 (including cells 10b and 10c) first."
    )
print("All 9 HMM artifacts present (O / A / B × {winner, meta, regime_probs}).")

All 9 HMM artifacts present (O / A / B × {winner, meta, regime_probs}).

## Configure variants × seeds

In [3]:
VARIANTS = [
    {
        "name":           "O",
        "features":       config.LSTM_VARIANT_O_FEATURES,
        "output_suffix_base": "_O",
        "regime_probs":   config.DATA_PROCESSED / "regime_probabilities_O.parquet",
        "hmm_meta":       config.MODELS_DIR / "hmm_meta_O.joblib",
    },
    {
        "name":           "A",
        "features":       config.LSTM_VARIANT_A_FEATURES,
        "output_suffix_base": "",
        "regime_probs":   config.DATA_PROCESSED / "regime_probabilities.parquet",
        "hmm_meta":       config.MODELS_DIR / "hmm_meta.joblib",
    },
    {
        "name":           "B",
        "features":       config.LSTM_VARIANT_B_FEATURES,
        "output_suffix_base": "_B",
        "regime_probs":   config.DATA_PROCESSED / "regime_probabilities_B.parquet",
        "hmm_meta":       config.MODELS_DIR / "hmm_meta_B.joblib",
    },
]
SEEDS = [42, 43, 44]

for v in VARIANTS:
    base = v["output_suffix_base"] or "<default>"
    for s in SEEDS:
        sfx = v["output_suffix_base"] + f"_seed{s}"
        print(f"  variant {v['name']}  suffix_base={base:<10s}  seed {s} → lstm_{{calm,volatile}}{sfx}.pt")
print(f"\nTotal runs (one per (variant, seed), each covering calm+volatile): {len(VARIANTS) * len(SEEDS)}")

  variant O  suffix_base=_O          seed 42 → lstm_{calm,volatile}_O_seed42.pt
  variant O  suffix_base=_O          seed 43 → lstm_{calm,volatile}_O_seed43.pt
  variant O  suffix_base=_O          seed 44 → lstm_{calm,volatile}_O_seed44.pt
  variant A  suffix_base=<default>   seed 42 → lstm_{calm,volatile}_seed42.pt
  variant A  suffix_base=<default>   seed 43 → lstm_{calm,volatile}_seed43.pt
  variant A  suffix_base=<default>   seed 44 → lstm_{calm,volatile}_seed44.pt
  variant B  suffix_base=_B          seed 42 → lstm_{calm,volatile}_B_seed42.pt
  variant B  suffix_base=_B          seed 43 → lstm_{calm,volatile}_B_seed43.pt
  variant B  suffix_base=_B          seed 44 → lstm_{calm,volatile}_B_seed44.pt

Total runs (one per (variant, seed), each covering calm+volatile): 9

## Training sweep

Per variant × seed: one invocation of `train_LSTM_regime.py --regime both` (which trains both regimes back-to-back). Seed 42 does full Optuna per regime; seeds 43/44 load the seed-42 JSON via `--fixed-hparams`.

Expected wall time per *variant* (all 3 seeds combined): ~30 min Optuna (2 regimes × ~15 min each) + 4 × ~5 min retrain (2 regimes × seeds 43/44) ≈ 50 min on Colab GPU. Total for 3 variants: ~150 min.

In [4]:
variant_outputs = {}
MODELS_DIR = config.MODELS_DIR
MODELS_DIR.mkdir(parents=True, exist_ok=True)


def _run_one_seed(args_list, label):
    cmd = [sys.executable, "-u", str(SCRIPT), *args_list]
    print("=" * 80)
    print(f"[{label}]")
    print("Command:", " ".join(cmd))
    print("-" * 80)
    lines = []
    proc = subprocess.Popen(
        cmd, cwd=str(REPO_ROOT),
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, bufsize=1,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        print(line, end="")
        lines.append(line)
    rc = proc.wait()
    return rc, "".join(lines)


for v in VARIANTS:
    vname = v["name"]
    hparams_json_path = MODELS_DIR / f"hparams_lstm_regime{v['output_suffix_base'] or '_A'}.json"
    variant_outputs[vname] = {"seeds": {}}

    for seed_idx, seed in enumerate(SEEDS):
        suffix_for_seed = f"{v['output_suffix_base']}_seed{seed}"
        label = f"variant {vname}  seed {seed}"
        args_list = [
            "--features", *v["features"],
            "--regime", "both",
            "--output-suffix", suffix_for_seed,
            "--seed", str(seed),
            "--regime-probs-path", str(v["regime_probs"]),
            "--hmm-meta-path", str(v["hmm_meta"]),
        ]
        if seed_idx > 0:
            if not hparams_json_path.exists():
                print(f"  [{label}]  SKIPPED — seed 42 didn't produce {hparams_json_path}")
                variant_outputs[vname]["seeds"][seed] = {"status": "skipped"}
                continue
            args_list += ["--fixed-hparams", str(hparams_json_path)]

        try:
            rc, text = _run_one_seed(args_list, label)
        except Exception as exc:
            print(f"[{label}]  EXCEPTION: {exc}")
            variant_outputs[vname]["seeds"][seed] = {"status": "exception", "error": str(exc)}
            continue

        if rc != 0:
            print(f"[{label}]  FAILED (rc={rc})")
            variant_outputs[vname]["seeds"][seed] = {"status": "failed", "return_code": rc, "output": text}
            if seed_idx == 0:
                print(f"  Variant {vname}: seed 42 failed — skipping seeds {SEEDS[1:]}")
                break
            continue

        variant_outputs[vname]["seeds"][seed] = {"status": "ok", "output": text}

        # After seed 42 succeeds, persist its JSON for reuse
        if seed_idx == 0:
            marker = "=== Regime-Specific LSTM Results ==="
            idx = text.find(marker)
            if idx != -1:
                try:
                    blob = text[idx + len(marker):].strip()
                    results = json.loads(blob)
                    hparams_json_path.write_text(json.dumps(results, indent=2))
                    print(f"  [seed 42]  hparams JSON saved → {hparams_json_path.name}")
                except json.JSONDecodeError as exc:
                    print(f"  [seed 42]  JSON parse failed: {exc}")

================================================================================
[variant O  seed 42]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d --regime both --output-suffix _O_seed42 --seed 42 --regime-probs-path /content/repo/data/processed/regime_probabilities_O.parquet --hmm-meta-path /content/repo/models/hmm_meta_O.joblib
--------------------------------------------------------------------------------

22:56:57 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_O_seed42, regime_probs=/content/repo/data/processed/regime_probabilities_O.parquet, hmm_meta=/content/repo/models/hmm_meta_O.joblib
22:56:57 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
22:56:57 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
22:56:57 | INFO    | train_LSTM_regime | Regime calm: train=3691 rows (1196 in regime), val=1089 rows (323 in regime)
22:56:57 | INFO    | train_LSTM_regime | Starting Optuna study for 'calm' regime (20 trials)…
22:56:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:56:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:56:59 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 407 / 3650 windows kept
22:56:59 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 50 / 1048 windows kept

22:57:00 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 407 / 3650 windows kept
22:57:00 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 50 / 1048 windows kept

22:57:02 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:02 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:05 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:05 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:06 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:06 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:09 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:09 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:11 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 407 / 3650 windows kept
22:57:11 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 50 / 1048 windows kept

22:57:12 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:12 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:14 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 407 / 3650 windows kept
22:57:14 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 50 / 1048 windows kept

22:57:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:18 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:18 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:19 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:19 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:19 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:19 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:21 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:21 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:22 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:22 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:22 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:22 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:24 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:24 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 407 / 3650 windows kept
22:57:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 50 / 1048 windows kept

22:57:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept

22:57:26 | INFO    | train_LSTM_regime | [calm] Best val MSE (raw scale): 0.00014050 | params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.08335826517707517, 'lr': 0.003982116593618511, 'batch_size': 128, 'seq_len': 21}
22:57:26 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
22:57:26 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept
22:57:26 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (98 windows).
22:57:26 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=23.768170 | val_mse_raw=0.35480946 | best=0.35480946
22:57:26 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=15.498205 | val_mse_raw=0.00191120 | best=0.00191120
22:57:26 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=1.962526 | val_mse_raw=0.00014864 | best=0.00014864
22:57:26 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.446312 | val_mse_raw=0.00018902 | best=0.00014864

22:57:26 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.828340 | val_mse_raw=0.00017752 | best=0.00014864
22:57:26 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.310671 | val_mse_raw=0.00015057 | best=0.00014864
22:57:26 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.167805 | val_mse_raw=0.00014050 | best=0.00014050
22:57:26 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.246568 | val_mse_raw=0.00014107 | best=0.00014050
22:57:26 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.174110 | val_mse_raw=0.00014776 | best=0.00014050
22:57:26 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.142661 | val_mse_raw=0.00015479 | best=0.00014050

22:57:26 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.158091 | val_mse_raw=0.00015472 | best=0.00014050
22:57:26 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.146394 | val_mse_raw=0.00015008 | best=0.00014050
22:57:26 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.139780 | val_mse_raw=0.00014659 | best=0.00014050
22:57:26 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.141524 | val_mse_raw=0.00014676 | best=0.00014050
22:57:27 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.138151 | val_mse_raw=0.00014901 | best=0.00014050
22:57:27 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.135949 | val_mse_raw=0.00015038 | best=0.00014050

22:57:27 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.137135 | val_mse_raw=0.00015017 | best=0.00014050
22:57:27 | INFO    | train_LSTM_baseline | Early stopping at epoch 17
22:57:27 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00014050
22:57:27 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 0.0010621475521475077, 'RMSE': 0.032590605318546295, 'MAE': 0.0044180224649608135, 'n_test_windows': 1461}
22:57:27 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_O_seed42.pt
22:57:27 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_O_seed42_scaler.joblib
22:57:27 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
22:57:27 | INFO    | train_LSTM_regime | Regime volatile: train=3691 rows (2495 in regime), val=1089 rows (766 in regime)
22:57:27 | INFO    | train_LSTM_regime | Starting Optuna study for 'volatile' regime (20 trials)…
22:57:27 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
22:57:27 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

22:57:35 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
22:57:35 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

22:57:45 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
22:57:45 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

22:58:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
22:58:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

22:58:51 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
22:58:51 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

22:58:54 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
22:58:54 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

22:59:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
22:59:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

22:59:49 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
22:59:49 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

22:59:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
22:59:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

23:00:05 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:00:05 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

23:00:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:00:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

23:01:58 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:01:58 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

23:02:32 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
23:02:32 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

23:02:43 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:02:43 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

23:02:50 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
23:02:50 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

23:03:49 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:03:49 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

23:04:00 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
23:04:00 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

23:04:10 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:04:11 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

23:04:36 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:04:36 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept

23:04:43 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3051 / 3671 windows kept
23:04:43 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 971 / 1069 windows kept

23:05:20 | INFO    | train_LSTM_regime | [volatile] Best val MSE (raw scale): 0.00002759 | params: {'hidden_size': 128, 'n_layers': 2, 'dropout': 0.03252579649263976, 'lr': 0.007902619549708232, 'batch_size': 32, 'seq_len': 42}
23:05:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:05:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept
23:05:20 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (998 windows).

23:05:22 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=0.811179 | val_mse_raw=0.00005282 | best=0.00005282

23:05:24 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.131970 | val_mse_raw=0.00003031 | best=0.00003031

23:05:26 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.105405 | val_mse_raw=0.00003123 | best=0.00003031

23:05:28 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.098172 | val_mse_raw=0.00003286 | best=0.00003031

23:05:30 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.099883 | val_mse_raw=0.00003273 | best=0.00003031

23:05:32 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.107147 | val_mse_raw=0.00002759 | best=0.00002759

23:05:33 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.103517 | val_mse_raw=0.00003085 | best=0.00002759

23:05:35 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.103710 | val_mse_raw=0.00003058 | best=0.00002759

23:05:37 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.094366 | val_mse_raw=0.00003029 | best=0.00002759

23:05:39 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.137808 | val_mse_raw=0.00005622 | best=0.00002759

23:05:41 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.239005 | val_mse_raw=0.00006125 | best=0.00002759

23:05:43 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.212348 | val_mse_raw=0.00005757 | best=0.00002759

23:05:44 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.164751 | val_mse_raw=0.00004178 | best=0.00002759

23:05:46 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.121824 | val_mse_raw=0.00003328 | best=0.00002759

23:05:48 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.107164 | val_mse_raw=0.00003611 | best=0.00002759

23:05:50 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.107197 | val_mse_raw=0.00004189 | best=0.00002759
23:05:50 | INFO    | train_LSTM_baseline | Early stopping at epoch 16
23:05:50 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00002759

23:05:50 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 1.360844362352509e-05, 'RMSE': 0.0036889624316245317, 'MAE': 0.0023943143896758556, 'n_test_windows': 1440}
23:05:50 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_O_seed42.pt
23:05:50 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_O_seed42_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 64,
      "n_layers": 1,
      "dropout": 0.08335826517707517,
      "lr": 0.003982116593618511,
      "batch_size": 128,
      "seq_len": 21
    },
    "best_val_mse_raw": 0.0001405034272465855,
    "retrained_val_mse": 0.0001405034272465855,
    "test_metrics": {
      "MSE": 0.0010621475521475077,
      "RMSE": 0.032590605318546295,
      "MAE": 0.0044180224649608135,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d"
    ],
    "target": "realized_vol_21d",
    "n_trials": 20,
    "n_train_windows": 1196,
    "n_val_windows": 323,
    "seed": 42,
    "fixed_hparams": null
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 128,
      "n_layers": 2,
      "dropout": 0.03252579649263976,
      "lr": 0.007902619549708232,
      "batch_size": 32,
      "seq_len": 42
    },
    "best_val_mse_raw": 2.758503978839144e-05,
    "retrained_val_mse": 2.758503978839144e-05,
    "test_metrics": {
      "MSE": 1.360844362352509e-05,
      "RMSE": 0.0036889624316245317,
      "MAE": 0.0023943143896758556,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d"
    ],
    "target": "realized_vol_21d",
    "n_trials": 20,
    "n_train_windows": 2495,
    "n_val_windows": 766,
    "seed": 42,
    "fixed_hparams": null
  }
}

  [seed 42]  hparams JSON saved → hparams_lstm_regime_O.json
================================================================================
[variant O  seed 43]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d --regime both --output-suffix _O_seed43 --seed 43 --regime-probs-path /content/repo/data/processed/regime_probabilities_O.parquet --hmm-meta-path /content/repo/models/hmm_meta_O.joblib --fixed-hparams /content/repo/models/hparams_lstm_regime_O.json
--------------------------------------------------------------------------------

23:05:53 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_O_seed43, regime_probs=/content/repo/data/processed/regime_probabilities_O.parquet, hmm_meta=/content/repo/models/hmm_meta_O.joblib
23:05:53 | INFO    | train_LSTM_regime | Loaded fixed hparams for regimes: ['calm', 'volatile']
23:05:53 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
23:05:53 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
23:05:53 | INFO    | train_LSTM_regime | Regime calm: train=3691 rows (1196 in regime), val=1089 rows (323 in regime)
23:05:53 | INFO    | train_LSTM_regime | [calm] Skipping Optuna — using fixed hparams from JSON.
23:05:53 | INFO    | train_LSTM_regime | [calm] Fixed params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.08335826517707517, 'lr': 0.003982116593618511, 'batch_size': 128, 'seq_len': 21}
23:05:53 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
23:05:53 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept
23:05:53 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (98 windows).

23:05:54 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=24.715897 | val_mse_raw=0.49448699 | best=0.49448699
23:05:54 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=16.968120 | val_mse_raw=0.00200368 | best=0.00200368
23:05:54 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=1.976970 | val_mse_raw=0.00015217 | best=0.00015217
23:05:54 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.466418 | val_mse_raw=0.00018898 | best=0.00015217
23:05:54 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.776104 | val_mse_raw=0.00017411 | best=0.00015217
23:05:54 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.253613 | val_mse_raw=0.00014591 | best=0.00014591
23:05:54 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.207650 | val_mse_raw=0.00014043 | best=0.00014043

23:05:54 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.252719 | val_mse_raw=0.00014219 | best=0.00014043
23:05:54 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.156263 | val_mse_raw=0.00015153 | best=0.00014043
23:05:55 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.154946 | val_mse_raw=0.00015641 | best=0.00014043
23:05:55 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.159195 | val_mse_raw=0.00015243 | best=0.00014043
23:05:55 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.140649 | val_mse_raw=0.00014728 | best=0.00014043
23:05:55 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.143673 | val_mse_raw=0.00014604 | best=0.00014043
23:05:55 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.141163 | val_mse_raw=0.00014855 | best=0.00014043

23:05:55 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.137037 | val_mse_raw=0.00015065 | best=0.00014043
23:05:55 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.137910 | val_mse_raw=0.00015016 | best=0.00014043
23:05:55 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.136516 | val_mse_raw=0.00014936 | best=0.00014043
23:05:55 | INFO    | train_LSTM_baseline | Early stopping at epoch 17
23:05:55 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00014043
23:05:55 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 0.0030175247229635715, 'RMSE': 0.05493200197815895, 'MAE': 0.006521948147565126, 'n_test_windows': 1461}
23:05:55 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_O_seed43.pt
23:05:55 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_O_seed43_scaler.joblib
23:05:55 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
23:05:55 | INFO    | train_LSTM_regime | Regime volatile: train=3691 rows (2495 in regime), val=1089 rows (766 in regime)
23:05:55 | INFO    | train_LSTM_regime | [volatile] Skipping Optuna — using fixed hparams from JSON.
23:05:55 | INFO    | train_LSTM_regime | [volatile] Fixed params: {'hidden_size': 128, 'n_layers': 2, 'dropout': 0.03252579649263976, 'lr': 0.007902619549708232, 'batch_size': 32, 'seq_len': 42}
23:05:55 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:05:55 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept
23:05:55 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (998 windows).

23:05:57 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=0.798444 | val_mse_raw=0.00005563 | best=0.00005563

23:05:59 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.227753 | val_mse_raw=0.00004329 | best=0.00004329

23:06:02 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.124581 | val_mse_raw=0.00003190 | best=0.00003190

23:06:04 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.104687 | val_mse_raw=0.00003241 | best=0.00003190

23:06:06 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.100863 | val_mse_raw=0.00002835 | best=0.00002835

23:06:08 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.093879 | val_mse_raw=0.00002787 | best=0.00002787

23:06:11 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.090476 | val_mse_raw=0.00002714 | best=0.00002714

23:06:13 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.094126 | val_mse_raw=0.00003310 | best=0.00002714

23:06:15 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.092220 | val_mse_raw=0.00003290 | best=0.00002714

23:06:18 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.087448 | val_mse_raw=0.00003576 | best=0.00002714

23:06:20 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.079184 | val_mse_raw=0.00003734 | best=0.00002714

23:06:22 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.079552 | val_mse_raw=0.00004078 | best=0.00002714

23:06:24 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.072389 | val_mse_raw=0.00003837 | best=0.00002714

23:06:27 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.070372 | val_mse_raw=0.00003971 | best=0.00002714

23:06:29 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.069574 | val_mse_raw=0.00004038 | best=0.00002714

23:06:31 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.065745 | val_mse_raw=0.00004195 | best=0.00002714

23:06:33 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.172375 | val_mse_raw=0.00004773 | best=0.00002714
23:06:33 | INFO    | train_LSTM_baseline | Early stopping at epoch 17
23:06:33 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00002714

23:06:34 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 1.531566886114888e-05, 'RMSE': 0.003913523629307747, 'MAE': 0.0025531246792525053, 'n_test_windows': 1440}
23:06:34 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_O_seed43.pt
23:06:34 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_O_seed43_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 64,
      "n_layers": 1,
      "dropout": 0.08335826517707517,
      "lr": 0.003982116593618511,
      "batch_size": 128,
      "seq_len": 21
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 0.00014043485862202942,
    "test_metrics": {
      "MSE": 0.0030175247229635715,
      "RMSE": 0.05493200197815895,
      "MAE": 0.006521948147565126,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 1196,
    "n_val_windows": 323,
    "seed": 43,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_O.json"
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 128,
      "n_layers": 2,
      "dropout": 0.03252579649263976,
      "lr": 0.007902619549708232,
      "batch_size": 32,
      "seq_len": 42
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 2.7142456019646488e-05,
    "test_metrics": {
      "MSE": 1.531566886114888e-05,
      "RMSE": 0.003913523629307747,
      "MAE": 0.0025531246792525053,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 2495,
    "n_val_windows": 766,
    "seed": 43,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_O.json"
  }
}

================================================================================
[variant O  seed 44]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d --regime both --output-suffix _O_seed44 --seed 44 --regime-probs-path /content/repo/data/processed/regime_probabilities_O.parquet --hmm-meta-path /content/repo/models/hmm_meta_O.joblib --fixed-hparams /content/repo/models/hparams_lstm_regime_O.json
--------------------------------------------------------------------------------

23:06:37 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_O_seed44, regime_probs=/content/repo/data/processed/regime_probabilities_O.parquet, hmm_meta=/content/repo/models/hmm_meta_O.joblib
23:06:37 | INFO    | train_LSTM_regime | Loaded fixed hparams for regimes: ['calm', 'volatile']
23:06:37 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
23:06:37 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
23:06:37 | INFO    | train_LSTM_regime | Regime calm: train=3691 rows (1196 in regime), val=1089 rows (323 in regime)
23:06:37 | INFO    | train_LSTM_regime | [calm] Skipping Optuna — using fixed hparams from JSON.
23:06:37 | INFO    | train_LSTM_regime | [calm] Fixed params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.08335826517707517, 'lr': 0.003982116593618511, 'batch_size': 128, 'seq_len': 21}
23:06:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 620 / 3671 windows kept
23:06:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 98 / 1069 windows kept
23:06:37 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (98 windows).

23:06:38 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=24.393770 | val_mse_raw=0.48050830 | best=0.48050830
23:06:38 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=17.061674 | val_mse_raw=0.00507653 | best=0.00507653
23:06:38 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=3.278693 | val_mse_raw=0.00014137 | best=0.00014137
23:06:38 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.317709 | val_mse_raw=0.00018619 | best=0.00014137
23:06:38 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.918785 | val_mse_raw=0.00018629 | best=0.00014137
23:06:38 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.542068 | val_mse_raw=0.00016110 | best=0.00014137
23:06:38 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.166637 | val_mse_raw=0.00014169 | best=0.00014137

23:06:38 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.237000 | val_mse_raw=0.00014049 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.221625 | val_mse_raw=0.00014339 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.149575 | val_mse_raw=0.00015113 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.149190 | val_mse_raw=0.00015522 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.156747 | val_mse_raw=0.00015332 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.142209 | val_mse_raw=0.00014916 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.140388 | val_mse_raw=0.00014668 | best=0.00014049

23:06:38 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.142272 | val_mse_raw=0.00014723 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.139353 | val_mse_raw=0.00014910 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.137957 | val_mse_raw=0.00015034 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.138337 | val_mse_raw=0.00015016 | best=0.00014049
23:06:38 | INFO    | train_LSTM_baseline | Early stopping at epoch 18
23:06:38 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00014049
23:06:38 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 0.0034752427600324154, 'RMSE': 0.05895118787884712, 'MAE': 0.006952464580535889, 'n_test_windows': 1461}
23:06:38 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_O_seed44.pt
23:06:38 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_O_seed44_scaler.joblib
23:06:38 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
23:06:38 | INFO    | train_LSTM_regime | Regime volatile: train=3691 rows (2495 in regime), val=1089 rows (766 in regime)
23:06:38 | INFO    | train_LSTM_regime | [volatile] Skipping Optuna — using fixed hparams from JSON.
23:06:38 | INFO    | train_LSTM_regime | [volatile] Fixed params: {'hidden_size': 128, 'n_layers': 2, 'dropout': 0.03252579649263976, 'lr': 0.007902619549708232, 'batch_size': 32, 'seq_len': 42}
23:06:38 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 3243 / 3650 windows kept
23:06:38 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 998 / 1048 windows kept
23:06:38 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (998 windows).

23:06:40 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=0.823002 | val_mse_raw=0.00005542 | best=0.00005542

23:06:43 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.241596 | val_mse_raw=0.00005056 | best=0.00005056

23:06:45 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.155357 | val_mse_raw=0.00003780 | best=0.00003780

23:06:47 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.109000 | val_mse_raw=0.00003292 | best=0.00003292

23:06:49 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.112898 | val_mse_raw=0.00002778 | best=0.00002778

23:06:51 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.106121 | val_mse_raw=0.00002966 | best=0.00002778

23:06:54 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.101777 | val_mse_raw=0.00002974 | best=0.00002778

23:06:56 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.098176 | val_mse_raw=0.00003077 | best=0.00002778

23:06:58 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.101945 | val_mse_raw=0.00003126 | best=0.00002778

23:07:01 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.086757 | val_mse_raw=0.00004024 | best=0.00002778

23:07:03 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.090535 | val_mse_raw=0.00003446 | best=0.00002778

23:07:05 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.086480 | val_mse_raw=0.00003611 | best=0.00002778

23:07:07 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.088620 | val_mse_raw=0.00003551 | best=0.00002778

23:07:09 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.082659 | val_mse_raw=0.00003710 | best=0.00002778

23:07:12 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.086000 | val_mse_raw=0.00003626 | best=0.00002778
23:07:12 | INFO    | train_LSTM_baseline | Early stopping at epoch 15
23:07:12 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00002778

23:07:12 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 1.4350783203553874e-05, 'RMSE': 0.0037882428150624037, 'MAE': 0.0025373497046530247, 'n_test_windows': 1440}
23:07:12 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_O_seed44.pt
23:07:12 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_O_seed44_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 64,
      "n_layers": 1,
      "dropout": 0.08335826517707517,
      "lr": 0.003982116593618511,
      "batch_size": 128,
      "seq_len": 21
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 0.00014048611046746373,
    "test_metrics": {
      "MSE": 0.0034752427600324154,
      "RMSE": 0.05895118787884712,
      "MAE": 0.006952464580535889,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 1196,
    "n_val_windows": 323,
    "seed": 44,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_O.json"
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 128,
      "n_layers": 2,
      "dropout": 0.03252579649263976,
      "lr": 0.007902619549708232,
      "batch_size": 32,
      "seq_len": 42
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 2.7780331947724335e-05,
    "test_metrics": {
      "MSE": 1.4350783203553874e-05,
      "RMSE": 0.0037882428150624037,
      "MAE": 0.0025373497046530247,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 2495,
    "n_val_windows": 766,
    "seed": 44,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_O.json"
  }
}

================================================================================
[variant A  seed 42]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish --regime both --output-suffix _seed42 --seed 42 --regime-probs-path /content/repo/data/processed/regime_probabilities.parquet --hmm-meta-path /content/repo/models/hmm_meta.joblib
--------------------------------------------------------------------------------

23:07:15 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_seed42, regime_probs=/content/repo/data/processed/regime_probabilities.parquet, hmm_meta=/content/repo/models/hmm_meta.joblib
23:07:15 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
23:07:15 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
23:07:15 | INFO    | train_LSTM_regime | Regime calm: train=3691 rows (3485 in regime), val=1089 rows (1043 in regime)
23:07:15 | INFO    | train_LSTM_regime | Starting Optuna study for 'calm' regime (20 trials)…
23:07:15 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:07:15 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:07:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3484 / 3650 windows kept
23:07:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1025 / 1048 windows kept

23:07:42 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3484 / 3650 windows kept
23:07:42 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1025 / 1048 windows kept

23:08:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:08:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:08:47 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:08:47 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:08:51 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:08:51 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:09:36 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:09:36 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:09:45 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3484 / 3650 windows kept
23:09:45 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1025 / 1048 windows kept

23:09:52 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:09:52 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:10:03 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3484 / 3650 windows kept
23:10:03 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1025 / 1048 windows kept

23:10:30 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:10:30 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:11:03 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:11:03 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:11:19 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:11:19 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:11:46 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:11:46 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:12:08 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:12:08 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:12:32 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:12:32 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:12:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:12:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:12:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:12:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:13:23 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3484 / 3650 windows kept
23:13:23 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1025 / 1048 windows kept

23:13:40 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:13:40 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept

23:13:45 | INFO    | train_LSTM_regime | [calm] Best val MSE (raw scale): 0.00003777 | params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.02904180608409973, 'lr': 0.005399484409787433, 'batch_size': 64, 'seq_len': 21}
23:13:45 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:13:45 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept
23:13:45 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (1035 windows).

23:13:46 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.691132 | val_mse_raw=0.00004510 | best=0.00004510

23:13:46 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.136820 | val_mse_raw=0.00004348 | best=0.00004348

23:13:46 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.125005 | val_mse_raw=0.00004363 | best=0.00004348

23:13:46 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.119175 | val_mse_raw=0.00004336 | best=0.00004336

23:13:47 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.114536 | val_mse_raw=0.00004295 | best=0.00004295

23:13:47 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.111104 | val_mse_raw=0.00004281 | best=0.00004281

23:13:47 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.109259 | val_mse_raw=0.00004299 | best=0.00004281

23:13:47 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.106949 | val_mse_raw=0.00004253 | best=0.00004253

23:13:48 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.108568 | val_mse_raw=0.00004232 | best=0.00004232

23:13:48 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.104333 | val_mse_raw=0.00004199 | best=0.00004199

23:13:48 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.106800 | val_mse_raw=0.00004385 | best=0.00004199

23:13:49 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.101407 | val_mse_raw=0.00004227 | best=0.00004199

23:13:49 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.099986 | val_mse_raw=0.00004186 | best=0.00004186

23:13:49 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.100278 | val_mse_raw=0.00004150 | best=0.00004150

23:13:49 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.099917 | val_mse_raw=0.00004267 | best=0.00004150

23:13:50 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.100295 | val_mse_raw=0.00004209 | best=0.00004150

23:13:50 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.099187 | val_mse_raw=0.00004171 | best=0.00004150

23:13:50 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.098636 | val_mse_raw=0.00004185 | best=0.00004150

23:13:50 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.097797 | val_mse_raw=0.00004114 | best=0.00004114

23:13:51 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.092294 | val_mse_raw=0.00004034 | best=0.00004034

23:13:51 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.095488 | val_mse_raw=0.00004238 | best=0.00004034

23:13:51 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.093356 | val_mse_raw=0.00004129 | best=0.00004034

23:13:51 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.090001 | val_mse_raw=0.00004244 | best=0.00004034

23:13:52 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.092505 | val_mse_raw=0.00004061 | best=0.00004034

23:13:52 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.092911 | val_mse_raw=0.00003777 | best=0.00003777

23:13:52 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.090051 | val_mse_raw=0.00003968 | best=0.00003777

23:13:52 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.087478 | val_mse_raw=0.00003852 | best=0.00003777

23:13:53 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.087340 | val_mse_raw=0.00003917 | best=0.00003777

23:13:53 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.089252 | val_mse_raw=0.00004250 | best=0.00003777

23:13:53 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.084430 | val_mse_raw=0.00003995 | best=0.00003777

23:13:53 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.082916 | val_mse_raw=0.00003937 | best=0.00003777

23:13:54 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.081438 | val_mse_raw=0.00003944 | best=0.00003777

23:13:54 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.083555 | val_mse_raw=0.00004024 | best=0.00003777

23:13:54 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.083239 | val_mse_raw=0.00004177 | best=0.00003777

23:13:54 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.080201 | val_mse_raw=0.00003923 | best=0.00003777
23:13:54 | INFO    | train_LSTM_baseline | Early stopping at epoch 35
23:13:54 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00003777
23:13:54 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 1.5362436897703446e-05, 'RMSE': 0.003919494338333607, 'MAE': 0.002531885402277112, 'n_test_windows': 1461}
23:13:54 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_seed42.pt
23:13:54 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_seed42_scaler.joblib
23:13:54 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
23:13:54 | INFO    | train_LSTM_regime | Regime volatile: train=3691 rows (206 in regime), val=1089 rows (46 in regime)
23:13:54 | INFO    | train_LSTM_regime | Starting Optuna study for 'volatile' regime (20 trials)…
23:13:55 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 190 / 3671 windows kept
23:13:55 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 34 / 1069 windows kept

23:13:55 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:13:55 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:13:56 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:13:56 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:13:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 190 / 3671 windows kept
23:13:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 34 / 1069 windows kept

23:13:58 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 190 / 3671 windows kept
23:13:58 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 34 / 1069 windows kept

23:13:58 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 190 / 3671 windows kept
23:13:59 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 34 / 1069 windows kept

23:14:00 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 190 / 3671 windows kept
23:14:00 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 34 / 1069 windows kept

23:14:01 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:01 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:02 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 190 / 3671 windows kept
23:14:02 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 34 / 1069 windows kept

23:14:02 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:02 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:04 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:04 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:06 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:06 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:08 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:08 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:10 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:10 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:12 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:12 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:14 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:14 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:18 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:18 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept

23:14:21 | INFO    | train_LSTM_regime | [volatile] Best val MSE (raw scale): 0.00001170 | params: {'hidden_size': 128, 'n_layers': 2, 'dropout': 0.41023612659334596, 'lr': 0.0051853999602662695, 'batch_size': 64, 'seq_len': 42}
23:14:21 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:21 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept
23:14:21 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (23 windows).
23:14:21 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=12.483537 | val_mse_raw=0.00085973 | best=0.00085973

23:14:21 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.568223 | val_mse_raw=0.00003672 | best=0.00003672
23:14:21 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.253065 | val_mse_raw=0.00014350 | best=0.00003672
23:14:21 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.206960 | val_mse_raw=0.00010774 | best=0.00003672

23:14:21 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.129999 | val_mse_raw=0.00001466 | best=0.00001466
23:14:21 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.154557 | val_mse_raw=0.00001170 | best=0.00001170
23:14:21 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.145432 | val_mse_raw=0.00003125 | best=0.00001170

23:14:22 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.110785 | val_mse_raw=0.00006639 | best=0.00001170
23:14:22 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.131499 | val_mse_raw=0.00005992 | best=0.00001170

23:14:22 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.121657 | val_mse_raw=0.00002716 | best=0.00001170
23:14:22 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.114517 | val_mse_raw=0.00001927 | best=0.00001170
23:14:22 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.117958 | val_mse_raw=0.00002393 | best=0.00001170

23:14:22 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.114369 | val_mse_raw=0.00003898 | best=0.00001170
23:14:22 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.114333 | val_mse_raw=0.00004191 | best=0.00001170
23:14:22 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.114861 | val_mse_raw=0.00003286 | best=0.00001170

23:14:22 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.113047 | val_mse_raw=0.00002653 | best=0.00001170
23:14:22 | INFO    | train_LSTM_baseline | Early stopping at epoch 16
23:14:22 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00001170

23:14:23 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 0.5898457169532776, 'RMSE': 0.768014132976532, 'MAE': 0.23149514198303223, 'n_test_windows': 1440}
23:14:23 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_seed42.pt
23:14:23 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_seed42_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 64,
      "n_layers": 1,
      "dropout": 0.02904180608409973,
      "lr": 0.005399484409787433,
      "batch_size": 64,
      "seq_len": 21
    },
    "best_val_mse_raw": 3.777417077799328e-05,
    "retrained_val_mse": 3.777417077799328e-05,
    "test_metrics": {
      "MSE": 1.5362436897703446e-05,
      "RMSE": 0.003919494338333607,
      "MAE": 0.002531885402277112,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish"
    ],
    "target": "realized_vol_21d",
    "n_trials": 20,
    "n_train_windows": 3485,
    "n_val_windows": 1043,
    "seed": 42,
    "fixed_hparams": null
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 128,
      "n_layers": 2,
      "dropout": 0.41023612659334596,
      "lr": 0.0051853999602662695,
      "batch_size": 64,
      "seq_len": 42
    },
    "best_val_mse_raw": 1.170140785689e-05,
    "retrained_val_mse": 1.170140785689e-05,
    "test_metrics": {
      "MSE": 0.5898457169532776,
      "RMSE": 0.768014132976532,
      "MAE": 0.23149514198303223,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish"
    ],
    "target": "realized_vol_21d",
    "n_trials": 20,
    "n_train_windows": 206,
    "n_val_windows": 46,
    "seed": 42,
    "fixed_hparams": null
  }
}

  [seed 42]  hparams JSON saved → hparams_lstm_regime_A.json
================================================================================
[variant A  seed 43]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish --regime both --output-suffix _seed43 --seed 43 --regime-probs-path /content/repo/data/processed/regime_probabilities.parquet --hmm-meta-path /content/repo/models/hmm_meta.joblib --fixed-hparams /content/repo/models/hparams_lstm_regime_A.json
--------------------------------------------------------------------------------

23:14:26 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_seed43, regime_probs=/content/repo/data/processed/regime_probabilities.parquet, hmm_meta=/content/repo/models/hmm_meta.joblib
23:14:26 | INFO    | train_LSTM_regime | Loaded fixed hparams for regimes: ['calm', 'volatile']
23:14:26 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
23:14:26 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
23:14:26 | INFO    | train_LSTM_regime | Regime calm: train=3691 rows (3485 in regime), val=1089 rows (1043 in regime)
23:14:26 | INFO    | train_LSTM_regime | [calm] Skipping Optuna — using fixed hparams from JSON.
23:14:26 | INFO    | train_LSTM_regime | [calm] Fixed params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.02904180608409973, 'lr': 0.005399484409787433, 'batch_size': 64, 'seq_len': 21}
23:14:26 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:14:26 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept
23:14:26 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (1035 windows).

23:14:27 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.882882 | val_mse_raw=0.00004739 | best=0.00004739

23:14:27 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.144030 | val_mse_raw=0.00004397 | best=0.00004397

23:14:27 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.129289 | val_mse_raw=0.00004319 | best=0.00004319

23:14:28 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.121649 | val_mse_raw=0.00004226 | best=0.00004226

23:14:28 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.116281 | val_mse_raw=0.00004313 | best=0.00004226

23:14:28 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.114226 | val_mse_raw=0.00004225 | best=0.00004225

23:14:28 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.109764 | val_mse_raw=0.00004235 | best=0.00004225

23:14:29 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.108025 | val_mse_raw=0.00004389 | best=0.00004225

23:14:29 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.105843 | val_mse_raw=0.00004234 | best=0.00004225

23:14:29 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.104116 | val_mse_raw=0.00004186 | best=0.00004186

23:14:29 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.102574 | val_mse_raw=0.00004416 | best=0.00004186

23:14:30 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.100768 | val_mse_raw=0.00004376 | best=0.00004186

23:14:30 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.099364 | val_mse_raw=0.00004200 | best=0.00004186

23:14:30 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.098826 | val_mse_raw=0.00004217 | best=0.00004186

23:14:30 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.096717 | val_mse_raw=0.00004407 | best=0.00004186

23:14:31 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.099908 | val_mse_raw=0.00004474 | best=0.00004186

23:14:31 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.094909 | val_mse_raw=0.00004379 | best=0.00004186

23:14:31 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.098196 | val_mse_raw=0.00004421 | best=0.00004186

23:14:31 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.096810 | val_mse_raw=0.00004363 | best=0.00004186

23:14:32 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.097632 | val_mse_raw=0.00004135 | best=0.00004135

23:14:32 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.093337 | val_mse_raw=0.00004127 | best=0.00004127

23:14:32 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.096666 | val_mse_raw=0.00004050 | best=0.00004050

23:14:32 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.091260 | val_mse_raw=0.00004124 | best=0.00004050

23:14:33 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.094540 | val_mse_raw=0.00004060 | best=0.00004050

23:14:33 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.091274 | val_mse_raw=0.00004268 | best=0.00004050

23:14:33 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.090094 | val_mse_raw=0.00004240 | best=0.00004050

23:14:33 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.087997 | val_mse_raw=0.00004301 | best=0.00004050

23:14:34 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.088433 | val_mse_raw=0.00004118 | best=0.00004050

23:14:34 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.087400 | val_mse_raw=0.00004139 | best=0.00004050

23:14:34 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.127383 | val_mse_raw=0.00004096 | best=0.00004050

23:14:34 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.093774 | val_mse_raw=0.00004245 | best=0.00004050

23:14:35 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.087610 | val_mse_raw=0.00004412 | best=0.00004050
23:14:35 | INFO    | train_LSTM_baseline | Early stopping at epoch 32
23:14:35 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00004050
23:14:35 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 1.4067766642256174e-05, 'RMSE': 0.0037507021334022284, 'MAE': 0.0025155467446893454, 'n_test_windows': 1461}
23:14:35 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_seed43.pt
23:14:35 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_seed43_scaler.joblib
23:14:35 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
23:14:35 | INFO    | train_LSTM_regime | Regime volatile: train=3691 rows (206 in regime), val=1089 rows (46 in regime)
23:14:35 | INFO    | train_LSTM_regime | [volatile] Skipping Optuna — using fixed hparams from JSON.
23:14:35 | INFO    | train_LSTM_regime | [volatile] Fixed params: {'hidden_size': 128, 'n_layers': 2, 'dropout': 0.41023612659334596, 'lr': 0.0051853999602662695, 'batch_size': 64, 'seq_len': 42}
23:14:35 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:35 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept
23:14:35 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (23 windows).
23:14:35 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=11.018698 | val_mse_raw=0.00002317 | best=0.00002317

23:14:35 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.676832 | val_mse_raw=0.00001273 | best=0.00001273
23:14:35 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.235141 | val_mse_raw=0.00040182 | best=0.00001273

23:14:35 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.300789 | val_mse_raw=0.00003033 | best=0.00001273
23:14:35 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.165456 | val_mse_raw=0.00001753 | best=0.00001273

23:14:35 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.225695 | val_mse_raw=0.00001323 | best=0.00001273
23:14:35 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.127422 | val_mse_raw=0.00006682 | best=0.00001273

23:14:36 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.143105 | val_mse_raw=0.00009656 | best=0.00001273
23:14:36 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.141990 | val_mse_raw=0.00004278 | best=0.00001273
23:14:36 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.120433 | val_mse_raw=0.00001584 | best=0.00001273

23:14:36 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.127603 | val_mse_raw=0.00001566 | best=0.00001273
23:14:36 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.120248 | val_mse_raw=0.00002892 | best=0.00001273
23:14:36 | INFO    | train_LSTM_baseline | Early stopping at epoch 12
23:14:36 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00001273

23:14:36 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 0.07022066414356232, 'RMSE': 0.264991819858551, 'MAE': 0.05501312017440796, 'n_test_windows': 1440}
23:14:36 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_seed43.pt
23:14:36 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_seed43_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 64,
      "n_layers": 1,
      "dropout": 0.02904180608409973,
      "lr": 0.005399484409787433,
      "batch_size": 64,
      "seq_len": 21
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 4.050040661240928e-05,
    "test_metrics": {
      "MSE": 1.4067766642256174e-05,
      "RMSE": 0.0037507021334022284,
      "MAE": 0.0025155467446893454,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 3485,
    "n_val_windows": 1043,
    "seed": 43,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_A.json"
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 128,
      "n_layers": 2,
      "dropout": 0.41023612659334596,
      "lr": 0.0051853999602662695,
      "batch_size": 64,
      "seq_len": 42
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 1.2733081348414999e-05,
    "test_metrics": {
      "MSE": 0.07022066414356232,
      "RMSE": 0.264991819858551,
      "MAE": 0.05501312017440796,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 206,
    "n_val_windows": 46,
    "seed": 43,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_A.json"
  }
}

================================================================================
[variant A  seed 44]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish --regime both --output-suffix _seed44 --seed 44 --regime-probs-path /content/repo/data/processed/regime_probabilities.parquet --hmm-meta-path /content/repo/models/hmm_meta.joblib --fixed-hparams /content/repo/models/hparams_lstm_regime_A.json
--------------------------------------------------------------------------------

23:14:39 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_seed44, regime_probs=/content/repo/data/processed/regime_probabilities.parquet, hmm_meta=/content/repo/models/hmm_meta.joblib
23:14:39 | INFO    | train_LSTM_regime | Loaded fixed hparams for regimes: ['calm', 'volatile']
23:14:39 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
23:14:39 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
23:14:39 | INFO    | train_LSTM_regime | Regime calm: train=3691 rows (3485 in regime), val=1089 rows (1043 in regime)
23:14:39 | INFO    | train_LSTM_regime | [calm] Skipping Optuna — using fixed hparams from JSON.
23:14:39 | INFO    | train_LSTM_regime | [calm] Fixed params: {'hidden_size': 64, 'n_layers': 1, 'dropout': 0.02904180608409973, 'lr': 0.005399484409787433, 'batch_size': 64, 'seq_len': 21}
23:14:39 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 3481 / 3671 windows kept
23:14:39 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1035 / 1069 windows kept
23:14:39 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (1035 windows).

23:14:40 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=2.980025 | val_mse_raw=0.00004325 | best=0.00004325

23:14:41 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.132862 | val_mse_raw=0.00004246 | best=0.00004246

23:14:41 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.123409 | val_mse_raw=0.00004297 | best=0.00004246

23:14:41 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.115887 | val_mse_raw=0.00004305 | best=0.00004246

23:14:42 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.113510 | val_mse_raw=0.00004215 | best=0.00004215

23:14:42 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.111354 | val_mse_raw=0.00004239 | best=0.00004215

23:14:42 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.107806 | val_mse_raw=0.00004294 | best=0.00004215

23:14:42 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.107546 | val_mse_raw=0.00004222 | best=0.00004215

23:14:43 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.106629 | val_mse_raw=0.00004272 | best=0.00004215

23:14:43 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.104943 | val_mse_raw=0.00004235 | best=0.00004215

23:14:43 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.106061 | val_mse_raw=0.00004429 | best=0.00004215

23:14:43 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.102716 | val_mse_raw=0.00004222 | best=0.00004215

23:14:44 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.100518 | val_mse_raw=0.00004205 | best=0.00004205

23:14:44 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.097490 | val_mse_raw=0.00004361 | best=0.00004205

23:14:44 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.097119 | val_mse_raw=0.00004284 | best=0.00004205

23:14:44 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.096517 | val_mse_raw=0.00004438 | best=0.00004205

23:14:45 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.097308 | val_mse_raw=0.00004401 | best=0.00004205

23:14:45 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.097792 | val_mse_raw=0.00004423 | best=0.00004205

23:14:45 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.096660 | val_mse_raw=0.00004244 | best=0.00004205

23:14:45 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.096955 | val_mse_raw=0.00004279 | best=0.00004205

23:14:46 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.094767 | val_mse_raw=0.00004270 | best=0.00004205

23:14:46 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.092084 | val_mse_raw=0.00004408 | best=0.00004205

23:14:46 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.093520 | val_mse_raw=0.00004139 | best=0.00004139

23:14:46 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.092498 | val_mse_raw=0.00004416 | best=0.00004139

23:14:47 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.089913 | val_mse_raw=0.00004139 | best=0.00004139

23:14:47 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.089110 | val_mse_raw=0.00004251 | best=0.00004139

23:14:47 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.088531 | val_mse_raw=0.00004297 | best=0.00004139

23:14:47 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.088573 | val_mse_raw=0.00004332 | best=0.00004139

23:14:48 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.087372 | val_mse_raw=0.00004343 | best=0.00004139

23:14:48 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.086529 | val_mse_raw=0.00004368 | best=0.00004139

23:14:48 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.086571 | val_mse_raw=0.00004379 | best=0.00004139

23:14:48 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.086899 | val_mse_raw=0.00004490 | best=0.00004139

23:14:49 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.084833 | val_mse_raw=0.00004521 | best=0.00004139

23:14:49 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.084075 | val_mse_raw=0.00004385 | best=0.00004139

23:14:49 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.078049 | val_mse_raw=0.00004388 | best=0.00004139
23:14:49 | INFO    | train_LSTM_baseline | Early stopping at epoch 35
23:14:49 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00004139
23:14:49 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 1.368224184261635e-05, 'RMSE': 0.0036989515647292137, 'MAE': 0.002425546059384942, 'n_test_windows': 1461}
23:14:49 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_seed44.pt
23:14:49 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_seed44_scaler.joblib
23:14:49 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
23:14:49 | INFO    | train_LSTM_regime | Regime volatile: train=3691 rows (206 in regime), val=1089 rows (46 in regime)
23:14:49 | INFO    | train_LSTM_regime | [volatile] Skipping Optuna — using fixed hparams from JSON.
23:14:49 | INFO    | train_LSTM_regime | [volatile] Fixed params: {'hidden_size': 128, 'n_layers': 2, 'dropout': 0.41023612659334596, 'lr': 0.0051853999602662695, 'batch_size': 64, 'seq_len': 42}
23:14:49 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 166 / 3650 windows kept
23:14:49 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 23 / 1048 windows kept
23:14:49 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (23 windows).
23:14:49 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=12.441547 | val_mse_raw=0.00073243 | best=0.00073243

23:14:50 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=0.514503 | val_mse_raw=0.00004983 | best=0.00004983
23:14:50 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.315046 | val_mse_raw=0.00011216 | best=0.00004983

23:14:50 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.241604 | val_mse_raw=0.00019337 | best=0.00004983
23:14:50 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.179311 | val_mse_raw=0.00002055 | best=0.00002055
23:14:50 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.135681 | val_mse_raw=0.00001255 | best=0.00001255

23:14:50 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.176071 | val_mse_raw=0.00001495 | best=0.00001255
23:14:50 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.119088 | val_mse_raw=0.00005924 | best=0.00001255

23:14:50 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.131023 | val_mse_raw=0.00008320 | best=0.00001255
23:14:50 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.131655 | val_mse_raw=0.00004067 | best=0.00001255
23:14:50 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.113162 | val_mse_raw=0.00001764 | best=0.00001255

23:14:51 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.123053 | val_mse_raw=0.00001714 | best=0.00001255
23:14:51 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.120102 | val_mse_raw=0.00003047 | best=0.00001255
23:14:51 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.119020 | val_mse_raw=0.00004738 | best=0.00001255

23:14:51 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.116243 | val_mse_raw=0.00003642 | best=0.00001255
23:14:51 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.112231 | val_mse_raw=0.00002459 | best=0.00001255
23:14:51 | INFO    | train_LSTM_baseline | Early stopping at epoch 16
23:14:51 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00001255

23:14:51 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 0.8402358889579773, 'RMSE': 0.9166437983512878, 'MAE': 0.3192793130874634, 'n_test_windows': 1440}
23:14:51 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_seed44.pt
23:14:51 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_seed44_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 64,
      "n_layers": 1,
      "dropout": 0.02904180608409973,
      "lr": 0.005399484409787433,
      "batch_size": 64,
      "seq_len": 21
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 4.139116936130449e-05,
    "test_metrics": {
      "MSE": 1.368224184261635e-05,
      "RMSE": 0.0036989515647292137,
      "MAE": 0.002425546059384942,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 3485,
    "n_val_windows": 1043,
    "seed": 44,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_A.json"
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 128,
      "n_layers": 2,
      "dropout": 0.41023612659334596,
      "lr": 0.0051853999602662695,
      "batch_size": 64,
      "seq_len": 42
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 1.254642575077014e-05,
    "test_metrics": {
      "MSE": 0.8402358889579773,
      "RMSE": 0.9166437983512878,
      "MAE": 0.3192793130874634,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 206,
    "n_val_windows": 46,
    "seed": 44,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_A.json"
  }
}

================================================================================
[variant B  seed 42]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish vix vix_log_change vix3m_minus_vix --regime both --output-suffix _B_seed42 --seed 42 --regime-probs-path /content/repo/data/processed/regime_probabilities_B.parquet --hmm-meta-path /content/repo/models/hmm_meta_B.joblib
--------------------------------------------------------------------------------

23:14:54 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_B_seed42, regime_probs=/content/repo/data/processed/regime_probabilities_B.parquet, hmm_meta=/content/repo/models/hmm_meta_B.joblib
23:14:54 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
23:14:54 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
23:14:54 | INFO    | train_LSTM_regime | Regime calm: train=2034 rows (1844 in regime), val=1089 rows (1037 in regime)
23:14:54 | INFO    | train_LSTM_regime | Starting Optuna study for 'calm' regime (20 trials)…
23:14:54 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:14:54 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:14:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1830 / 1993 windows kept
23:14:57 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1024 / 1048 windows kept

23:15:09 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1830 / 1993 windows kept
23:15:09 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1024 / 1048 windows kept

23:15:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:15:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:15:41 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:15:41 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:15:44 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:15:44 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:16:09 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:16:09 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:16:18 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1830 / 1993 windows kept
23:16:18 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1024 / 1048 windows kept

23:16:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:16:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:16:31 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1830 / 1993 windows kept
23:16:31 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1024 / 1048 windows kept

23:16:51 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:16:51 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:17:01 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:17:01 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:17:06 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:17:06 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:17:13 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:17:13 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:17:30 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:17:30 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:17:36 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:17:36 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:17:40 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:17:40 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:17:52 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:17:52 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:17:55 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1830 / 1993 windows kept
23:17:55 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1024 / 1048 windows kept

23:18:01 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:18:01 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept

23:18:05 | INFO    | train_LSTM_regime | [calm] Best val MSE (raw scale): 0.00003537 | params: {'hidden_size': 32, 'n_layers': 1, 'dropout': 0.31566834032054875, 'lr': 0.000821087758542746, 'batch_size': 32, 'seq_len': 21}
23:18:05 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:18:05 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept
23:18:05 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (1034 windows).
23:18:05 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=16.566298 | val_mse_raw=0.00829234 | best=0.00829234

23:18:05 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=1.411266 | val_mse_raw=0.00004947 | best=0.00004947
23:18:05 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.166726 | val_mse_raw=0.00004418 | best=0.00004418

23:18:05 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.154693 | val_mse_raw=0.00003995 | best=0.00003995
23:18:05 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.144432 | val_mse_raw=0.00003981 | best=0.00003981

23:18:06 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.138568 | val_mse_raw=0.00004127 | best=0.00003981
23:18:06 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.135088 | val_mse_raw=0.00004013 | best=0.00003981

23:18:06 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.130290 | val_mse_raw=0.00003848 | best=0.00003848
23:18:06 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.124727 | val_mse_raw=0.00003721 | best=0.00003721

23:18:06 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.120754 | val_mse_raw=0.00003714 | best=0.00003714
23:18:06 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.117450 | val_mse_raw=0.00003762 | best=0.00003714

23:18:07 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.116136 | val_mse_raw=0.00003745 | best=0.00003714
23:18:07 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.116340 | val_mse_raw=0.00003772 | best=0.00003714

23:18:07 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.115113 | val_mse_raw=0.00003726 | best=0.00003714
23:18:07 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.114113 | val_mse_raw=0.00003742 | best=0.00003714

23:18:07 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.112913 | val_mse_raw=0.00003738 | best=0.00003714
23:18:07 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.113051 | val_mse_raw=0.00003727 | best=0.00003714

23:18:08 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.111741 | val_mse_raw=0.00003707 | best=0.00003707
23:18:08 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.111564 | val_mse_raw=0.00003740 | best=0.00003707

23:18:08 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.111148 | val_mse_raw=0.00003757 | best=0.00003707
23:18:08 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.110363 | val_mse_raw=0.00003665 | best=0.00003665

23:18:08 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.109836 | val_mse_raw=0.00003701 | best=0.00003665
23:18:08 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.108782 | val_mse_raw=0.00003741 | best=0.00003665

23:18:08 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.109583 | val_mse_raw=0.00003828 | best=0.00003665
23:18:09 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.108492 | val_mse_raw=0.00003692 | best=0.00003665

23:18:09 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.107324 | val_mse_raw=0.00003634 | best=0.00003634
23:18:09 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.107188 | val_mse_raw=0.00003722 | best=0.00003634

23:18:09 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.106058 | val_mse_raw=0.00003707 | best=0.00003634
23:18:09 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.105859 | val_mse_raw=0.00003715 | best=0.00003634

23:18:09 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.104276 | val_mse_raw=0.00003628 | best=0.00003628
23:18:10 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.102972 | val_mse_raw=0.00003607 | best=0.00003607

23:18:10 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.102845 | val_mse_raw=0.00003642 | best=0.00003607
23:18:10 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.100897 | val_mse_raw=0.00003738 | best=0.00003607

23:18:10 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.101205 | val_mse_raw=0.00003649 | best=0.00003607
23:18:10 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.100236 | val_mse_raw=0.00003537 | best=0.00003537

23:18:10 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.099437 | val_mse_raw=0.00003547 | best=0.00003537
23:18:11 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.098752 | val_mse_raw=0.00003618 | best=0.00003537

23:18:11 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.098519 | val_mse_raw=0.00003567 | best=0.00003537
23:18:11 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.097653 | val_mse_raw=0.00003610 | best=0.00003537

23:18:11 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.097662 | val_mse_raw=0.00003593 | best=0.00003537
23:18:11 | INFO    | train_LSTM_baseline | epoch  41 | train_log_mse=0.096148 | val_mse_raw=0.00003514 | best=0.00003514

23:18:12 | INFO    | train_LSTM_baseline | epoch  42 | train_log_mse=0.095000 | val_mse_raw=0.00003505 | best=0.00003505
23:18:12 | INFO    | train_LSTM_baseline | epoch  43 | train_log_mse=0.096194 | val_mse_raw=0.00003486 | best=0.00003486

23:18:12 | INFO    | train_LSTM_baseline | epoch  44 | train_log_mse=0.095468 | val_mse_raw=0.00003478 | best=0.00003478
23:18:12 | INFO    | train_LSTM_baseline | epoch  45 | train_log_mse=0.093957 | val_mse_raw=0.00003553 | best=0.00003478

23:18:12 | INFO    | train_LSTM_baseline | epoch  46 | train_log_mse=0.096007 | val_mse_raw=0.00003599 | best=0.00003478
23:18:12 | INFO    | train_LSTM_baseline | epoch  47 | train_log_mse=0.092687 | val_mse_raw=0.00003513 | best=0.00003478

23:18:13 | INFO    | train_LSTM_baseline | epoch  48 | train_log_mse=0.092382 | val_mse_raw=0.00003582 | best=0.00003478
23:18:13 | INFO    | train_LSTM_baseline | epoch  49 | train_log_mse=0.091785 | val_mse_raw=0.00003588 | best=0.00003478

23:18:13 | INFO    | train_LSTM_baseline | epoch  50 | train_log_mse=0.090269 | val_mse_raw=0.00003519 | best=0.00003478
23:18:13 | INFO    | train_LSTM_baseline | epoch  51 | train_log_mse=0.092220 | val_mse_raw=0.00003580 | best=0.00003478

23:18:13 | INFO    | train_LSTM_baseline | epoch  52 | train_log_mse=0.089578 | val_mse_raw=0.00003547 | best=0.00003478
23:18:13 | INFO    | train_LSTM_baseline | epoch  53 | train_log_mse=0.087555 | val_mse_raw=0.00003690 | best=0.00003478

23:18:14 | INFO    | train_LSTM_baseline | epoch  54 | train_log_mse=0.087778 | val_mse_raw=0.00003458 | best=0.00003458
23:18:14 | INFO    | train_LSTM_baseline | epoch  55 | train_log_mse=0.084854 | val_mse_raw=0.00003441 | best=0.00003441

23:18:14 | INFO    | train_LSTM_baseline | epoch  56 | train_log_mse=0.081941 | val_mse_raw=0.00003414 | best=0.00003414
23:18:14 | INFO    | train_LSTM_baseline | epoch  57 | train_log_mse=0.079311 | val_mse_raw=0.00003420 | best=0.00003414

23:18:14 | INFO    | train_LSTM_baseline | epoch  58 | train_log_mse=0.077393 | val_mse_raw=0.00003630 | best=0.00003414
23:18:14 | INFO    | train_LSTM_baseline | epoch  59 | train_log_mse=0.073644 | val_mse_raw=0.00003898 | best=0.00003414

23:18:15 | INFO    | train_LSTM_baseline | epoch  60 | train_log_mse=0.069014 | val_mse_raw=0.00003576 | best=0.00003414
23:18:15 | INFO    | train_LSTM_baseline | epoch  61 | train_log_mse=0.070156 | val_mse_raw=0.00003876 | best=0.00003414

23:18:15 | INFO    | train_LSTM_baseline | epoch  62 | train_log_mse=0.065536 | val_mse_raw=0.00004176 | best=0.00003414
23:18:15 | INFO    | train_LSTM_baseline | epoch  63 | train_log_mse=0.063009 | val_mse_raw=0.00003988 | best=0.00003414

23:18:15 | INFO    | train_LSTM_baseline | epoch  64 | train_log_mse=0.064929 | val_mse_raw=0.00004239 | best=0.00003414
23:18:15 | INFO    | train_LSTM_baseline | epoch  65 | train_log_mse=0.060528 | val_mse_raw=0.00004245 | best=0.00003414

23:18:15 | INFO    | train_LSTM_baseline | epoch  66 | train_log_mse=0.059557 | val_mse_raw=0.00004216 | best=0.00003414
23:18:15 | INFO    | train_LSTM_baseline | Early stopping at epoch 66
23:18:15 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00003414
23:18:15 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 1.7942966223927215e-05, 'RMSE': 0.004235913977026939, 'MAE': 0.0027568163350224495, 'n_test_windows': 1461}
23:18:15 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_B_seed42.pt
23:18:15 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_B_seed42_scaler.joblib
23:18:15 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
23:18:15 | INFO    | train_LSTM_regime | Regime volatile: train=2034 rows (190 in regime), val=1089 rows (52 in regime)
23:18:15 | INFO    | train_LSTM_regime | Starting Optuna study for 'volatile' regime (20 trials)…
23:18:15 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 170 / 2014 windows kept
23:18:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 35 / 1069 windows kept

23:18:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:16 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:17 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:17 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:18 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 170 / 2014 windows kept
23:18:18 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 35 / 1069 windows kept

23:18:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 170 / 2014 windows kept
23:18:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 35 / 1069 windows kept

23:18:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 170 / 2014 windows kept
23:18:20 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 35 / 1069 windows kept

23:18:23 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 170 / 2014 windows kept
23:18:23 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 35 / 1069 windows kept

23:18:24 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:24 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 170 / 2014 windows kept
23:18:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 35 / 1069 windows kept

23:18:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:25 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:27 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:27 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:28 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:28 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:29 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:29 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:31 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:31 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:31 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:31 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:33 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:33 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:34 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:34 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:35 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:35 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:36 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:36 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:37 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept

23:18:38 | INFO    | train_LSTM_regime | [volatile] Best val MSE (raw scale): 0.00001349 | params: {'hidden_size': 32, 'n_layers': 3, 'dropout': 0.49826330933920426, 'lr': 0.0019110922048796155, 'batch_size': 128, 'seq_len': 42}
23:18:38 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:38 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept
23:18:38 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (24 windows).
23:18:38 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=13.566170 | val_mse_raw=0.72556019 | best=0.72556019
23:18:38 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=13.049686 | val_mse_raw=0.62322283 | best=0.62322283
23:18:38 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=12.560259 | val_mse_raw=0.52375001 | best=0.52375001
23:18:38 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=11.992243 | val_mse_raw=0.41823873 | best=0.41823873
23:18:38 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=11.266276 | val_mse_raw=0.30336675 | best=0.30336675

23:18:38 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=10.369324 | val_mse_raw=0.18898459 | best=0.18898459
23:18:38 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=8.976312 | val_mse_raw=0.09950187 | best=0.09950187
23:18:38 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=7.291402 | val_mse_raw=0.04781116 | best=0.04781116
23:18:38 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=5.631829 | val_mse_raw=0.02300195 | best=0.02300195
23:18:38 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=4.145615 | val_mse_raw=0.01119372 | best=0.01119372
23:18:39 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=2.939571 | val_mse_raw=0.00531243 | best=0.00531243

23:18:39 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=1.993292 | val_mse_raw=0.00236997 | best=0.00236997
23:18:39 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=1.221259 | val_mse_raw=0.00096573 | best=0.00096573
23:18:39 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.657142 | val_mse_raw=0.00035364 | best=0.00035364
23:18:39 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.324591 | val_mse_raw=0.00011460 | best=0.00011460
23:18:39 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.161994 | val_mse_raw=0.00003399 | best=0.00003399
23:18:39 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.125260 | val_mse_raw=0.00001452 | best=0.00001452
23:18:39 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.166320 | val_mse_raw=0.00001475 | best=0.00001452

23:18:39 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.214337 | val_mse_raw=0.00001815 | best=0.00001452
23:18:39 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.258969 | val_mse_raw=0.00001975 | best=0.00001452
23:18:39 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.276541 | val_mse_raw=0.00001894 | best=0.00001452
23:18:39 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.259982 | val_mse_raw=0.00001676 | best=0.00001452
23:18:39 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.248477 | val_mse_raw=0.00001448 | best=0.00001448
23:18:39 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.211351 | val_mse_raw=0.00001349 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.180516 | val_mse_raw=0.00001493 | best=0.00001349

23:18:39 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.151132 | val_mse_raw=0.00001945 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.135750 | val_mse_raw=0.00002691 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.127009 | val_mse_raw=0.00003641 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.121932 | val_mse_raw=0.00004665 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.117882 | val_mse_raw=0.00005687 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.125954 | val_mse_raw=0.00006548 | best=0.00001349

23:18:39 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.133679 | val_mse_raw=0.00007090 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.131310 | val_mse_raw=0.00007304 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.131927 | val_mse_raw=0.00007249 | best=0.00001349
23:18:39 | INFO    | train_LSTM_baseline | Early stopping at epoch 34
23:18:39 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00001349
23:18:39 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 0.004001517314463854, 'RMSE': 0.06325754523277283, 'MAE': 0.029103755950927734, 'n_test_windows': 1440}
23:18:39 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_B_seed42.pt
23:18:39 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_B_seed42_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 32,
      "n_layers": 1,
      "dropout": 0.31566834032054875,
      "lr": 0.000821087758542746,
      "batch_size": 32,
      "seq_len": 21
    },
    "best_val_mse_raw": 3.536617077770643e-05,
    "retrained_val_mse": 3.413817466935143e-05,
    "test_metrics": {
      "MSE": 1.7942966223927215e-05,
      "RMSE": 0.004235913977026939,
      "MAE": 0.0027568163350224495,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish",
      "vix",
      "vix_log_change",
      "vix3m_minus_vix"
    ],
    "target": "realized_vol_21d",
    "n_trials": 20,
    "n_train_windows": 1844,
    "n_val_windows": 1037,
    "seed": 42,
    "fixed_hparams": null
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 32,
      "n_layers": 3,
      "dropout": 0.49826330933920426,
      "lr": 0.0019110922048796155,
      "batch_size": 128,
      "seq_len": 42
    },
    "best_val_mse_raw": 1.3494613995135296e-05,
    "retrained_val_mse": 1.3494613995135296e-05,
    "test_metrics": {
      "MSE": 0.004001517314463854,
      "RMSE": 0.06325754523277283,
      "MAE": 0.029103755950927734,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish",
      "vix",
      "vix_log_change",
      "vix3m_minus_vix"
    ],
    "target": "realized_vol_21d",
    "n_trials": 20,
    "n_train_windows": 190,
    "n_val_windows": 52,
    "seed": 42,
    "fixed_hparams": null
  }
}

  [seed 42]  hparams JSON saved → hparams_lstm_regime_B.json
================================================================================
[variant B  seed 43]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish vix vix_log_change vix3m_minus_vix --regime both --output-suffix _B_seed43 --seed 43 --regime-probs-path /content/repo/data/processed/regime_probabilities_B.parquet --hmm-meta-path /content/repo/models/hmm_meta_B.joblib --fixed-hparams /content/repo/models/hparams_lstm_regime_B.json
--------------------------------------------------------------------------------

23:18:42 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_B_seed43, regime_probs=/content/repo/data/processed/regime_probabilities_B.parquet, hmm_meta=/content/repo/models/hmm_meta_B.joblib
23:18:42 | INFO    | train_LSTM_regime | Loaded fixed hparams for regimes: ['calm', 'volatile']
23:18:42 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
23:18:42 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
23:18:43 | INFO    | train_LSTM_regime | Regime calm: train=2034 rows (1844 in regime), val=1089 rows (1037 in regime)
23:18:43 | INFO    | train_LSTM_regime | [calm] Skipping Optuna — using fixed hparams from JSON.
23:18:43 | INFO    | train_LSTM_regime | [calm] Fixed params: {'hidden_size': 32, 'n_layers': 1, 'dropout': 0.31566834032054875, 'lr': 0.000821087758542746, 'batch_size': 32, 'seq_len': 21}
23:18:43 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:18:43 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept
23:18:43 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (1034 windows).

23:18:43 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=17.685298 | val_mse_raw=0.02351957 | best=0.02351957
23:18:44 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=1.990210 | val_mse_raw=0.00004502 | best=0.00004502

23:18:44 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.157922 | val_mse_raw=0.00004152 | best=0.00004152
23:18:44 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.144747 | val_mse_raw=0.00004304 | best=0.00004152

23:18:44 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.137516 | val_mse_raw=0.00004455 | best=0.00004152
23:18:44 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.132416 | val_mse_raw=0.00004473 | best=0.00004152

23:18:44 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.128881 | val_mse_raw=0.00004152 | best=0.00004152
23:18:45 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.124902 | val_mse_raw=0.00004004 | best=0.00004004

23:18:45 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.122825 | val_mse_raw=0.00003913 | best=0.00003913
23:18:45 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.120694 | val_mse_raw=0.00003856 | best=0.00003856

23:18:45 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.119555 | val_mse_raw=0.00003855 | best=0.00003855
23:18:45 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.118402 | val_mse_raw=0.00003849 | best=0.00003849

23:18:45 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.117745 | val_mse_raw=0.00003859 | best=0.00003849
23:18:46 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.117028 | val_mse_raw=0.00003866 | best=0.00003849

23:18:46 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.116084 | val_mse_raw=0.00003917 | best=0.00003849
23:18:46 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.115600 | val_mse_raw=0.00003900 | best=0.00003849

23:18:46 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.114939 | val_mse_raw=0.00003880 | best=0.00003849
23:18:46 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.114501 | val_mse_raw=0.00003880 | best=0.00003849

23:18:46 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.114480 | val_mse_raw=0.00003867 | best=0.00003849
23:18:47 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.113471 | val_mse_raw=0.00003900 | best=0.00003849

23:18:47 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.113122 | val_mse_raw=0.00003884 | best=0.00003849
23:18:47 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.112588 | val_mse_raw=0.00003860 | best=0.00003849
23:18:47 | INFO    | train_LSTM_baseline | Early stopping at epoch 22
23:18:47 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00003849

23:18:47 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 1.771822826412972e-05, 'RMSE': 0.004209302365779877, 'MAE': 0.002519389148801565, 'n_test_windows': 1461}
23:18:47 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_B_seed43.pt
23:18:47 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_B_seed43_scaler.joblib
23:18:47 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
23:18:47 | INFO    | train_LSTM_regime | Regime volatile: train=2034 rows (190 in regime), val=1089 rows (52 in regime)
23:18:47 | INFO    | train_LSTM_regime | [volatile] Skipping Optuna — using fixed hparams from JSON.
23:18:47 | INFO    | train_LSTM_regime | [volatile] Fixed params: {'hidden_size': 32, 'n_layers': 3, 'dropout': 0.49826330933920426, 'lr': 0.0019110922048796155, 'batch_size': 128, 'seq_len': 42}
23:18:47 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:47 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept
23:18:47 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (24 windows).
23:18:47 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=13.190270 | val_mse_raw=0.63273942 | best=0.63273942
23:18:47 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=12.523436 | val_mse_raw=0.50601274 | best=0.50601274
23:18:47 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=11.768731 | val_mse_raw=0.37870470 | best=0.37870470
23:18:47 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=10.825659 | val_mse_raw=0.25013891 | best=0.25013891

23:18:47 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=9.625852 | val_mse_raw=0.13761382 | best=0.13761382
23:18:47 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=8.047474 | val_mse_raw=0.06622098 | best=0.06622098
23:18:47 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=6.291302 | val_mse_raw=0.03298885 | best=0.03298885
23:18:47 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=4.791090 | val_mse_raw=0.01768808 | best=0.01768808
23:18:47 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=3.619297 | val_mse_raw=0.00971311 | best=0.00971311

23:18:47 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=2.721452 | val_mse_raw=0.00529450 | best=0.00529450
23:18:47 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=1.972008 | val_mse_raw=0.00284331 | best=0.00284331
23:18:47 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=1.357256 | val_mse_raw=0.00150487 | best=0.00150487
23:18:48 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.916983 | val_mse_raw=0.00078192 | best=0.00078192
23:18:48 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.591776 | val_mse_raw=0.00039686 | best=0.00039686
23:18:48 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.354137 | val_mse_raw=0.00019621 | best=0.00019621

23:18:48 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.217240 | val_mse_raw=0.00009494 | best=0.00009494
23:18:48 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.140708 | val_mse_raw=0.00004613 | best=0.00004613
23:18:48 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.124353 | val_mse_raw=0.00002443 | best=0.00002443
23:18:48 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.126462 | val_mse_raw=0.00001623 | best=0.00001623
23:18:48 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.146888 | val_mse_raw=0.00001387 | best=0.00001387
23:18:48 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.170741 | val_mse_raw=0.00001355 | best=0.00001355

23:18:48 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.187622 | val_mse_raw=0.00001363 | best=0.00001355
23:18:48 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.190486 | val_mse_raw=0.00001360 | best=0.00001355
23:18:48 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.191103 | val_mse_raw=0.00001352 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.181000 | val_mse_raw=0.00001373 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.173566 | val_mse_raw=0.00001463 | best=0.00001352

23:18:48 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.158040 | val_mse_raw=0.00001653 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.149566 | val_mse_raw=0.00001958 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.134675 | val_mse_raw=0.00002374 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.125290 | val_mse_raw=0.00002861 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.124268 | val_mse_raw=0.00003386 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.119958 | val_mse_raw=0.00003925 | best=0.00001352

23:18:48 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.126155 | val_mse_raw=0.00004438 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.117630 | val_mse_raw=0.00004888 | best=0.00001352
23:18:48 | INFO    | train_LSTM_baseline | Early stopping at epoch 34
23:18:48 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00001352
23:18:48 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 0.00010016839951276779, 'RMSE': 0.010008416138589382, 'MAE': 0.009332914836704731, 'n_test_windows': 1440}
23:18:48 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_B_seed43.pt
23:18:48 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_B_seed43_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 32,
      "n_layers": 1,
      "dropout": 0.31566834032054875,
      "lr": 0.000821087758542746,
      "batch_size": 32,
      "seq_len": 21
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 3.849412314593792e-05,
    "test_metrics": {
      "MSE": 1.771822826412972e-05,
      "RMSE": 0.004209302365779877,
      "MAE": 0.002519389148801565,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish",
      "vix",
      "vix_log_change",
      "vix3m_minus_vix"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 1844,
    "n_val_windows": 1037,
    "seed": 43,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_B.json"
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 32,
      "n_layers": 3,
      "dropout": 0.49826330933920426,
      "lr": 0.0019110922048796155,
      "batch_size": 128,
      "seq_len": 42
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 1.3522015251510311e-05,
    "test_metrics": {
      "MSE": 0.00010016839951276779,
      "RMSE": 0.010008416138589382,
      "MAE": 0.009332914836704731,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish",
      "vix",
      "vix_log_change",
      "vix3m_minus_vix"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 190,
    "n_val_windows": 52,
    "seed": 43,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_B.json"
  }
}

================================================================================
[variant B  seed 44]
Command: /usr/bin/python3 -u /content/repo/src/train_LSTM_regime.py --features log_return abs_return oc_return intraday_range relative_volume_21d bullish bearish vix vix_log_change vix3m_minus_vix --regime both --output-suffix _B_seed44 --seed 44 --regime-probs-path /content/repo/data/processed/regime_probabilities_B.parquet --hmm-meta-path /content/repo/models/hmm_meta_B.joblib --fixed-hparams /content/repo/models/hparams_lstm_regime_B.json
--------------------------------------------------------------------------------

23:18:52 | INFO    | train_LSTM_regime | Regime-LSTM training — output_suffix=_B_seed44, regime_probs=/content/repo/data/processed/regime_probabilities_B.parquet, hmm_meta=/content/repo/models/hmm_meta_B.joblib
23:18:52 | INFO    | train_LSTM_regime | Loaded fixed hparams for regimes: ['calm', 'volatile']
23:18:52 | INFO    | train_LSTM_regime | Split sizes — train=3710, val=1089, test=1481
23:18:52 | INFO    | train_LSTM_regime | === Training regime LSTM: calm (state=0) ===
23:18:52 | INFO    | train_LSTM_regime | Regime calm: train=2034 rows (1844 in regime), val=1089 rows (1037 in regime)
23:18:52 | INFO    | train_LSTM_regime | [calm] Skipping Optuna — using fixed hparams from JSON.
23:18:52 | INFO    | train_LSTM_regime | [calm] Fixed params: {'hidden_size': 32, 'n_layers': 1, 'dropout': 0.31566834032054875, 'lr': 0.000821087758542746, 'batch_size': 32, 'seq_len': 21}
23:18:52 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1844 / 2014 windows kept
23:18:52 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=calm): 1034 / 1069 windows kept
23:18:52 | INFO    | train_LSTM_regime | [calm] Final retrain — using regime-filtered val loader (1034 windows).

23:18:53 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=19.868053 | val_mse_raw=0.02550105 | best=0.02550105
23:18:53 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=2.297649 | val_mse_raw=0.00005109 | best=0.00005109

23:18:53 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=0.165488 | val_mse_raw=0.00004421 | best=0.00004421
23:18:53 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=0.150736 | val_mse_raw=0.00004070 | best=0.00004070

23:18:53 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=0.140529 | val_mse_raw=0.00003816 | best=0.00003816
23:18:53 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=0.132044 | val_mse_raw=0.00003736 | best=0.00003736

23:18:54 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=0.127317 | val_mse_raw=0.00003700 | best=0.00003700
23:18:54 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=0.124721 | val_mse_raw=0.00003718 | best=0.00003700

23:18:54 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=0.122512 | val_mse_raw=0.00003720 | best=0.00003700
23:18:54 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=0.121279 | val_mse_raw=0.00003703 | best=0.00003700

23:18:54 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=0.120606 | val_mse_raw=0.00003673 | best=0.00003673
23:18:54 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.119113 | val_mse_raw=0.00003660 | best=0.00003660

23:18:55 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.118606 | val_mse_raw=0.00003695 | best=0.00003660
23:18:55 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.117719 | val_mse_raw=0.00003706 | best=0.00003660

23:18:55 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.116959 | val_mse_raw=0.00003623 | best=0.00003623
23:18:55 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.116582 | val_mse_raw=0.00003649 | best=0.00003623

23:18:55 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.115718 | val_mse_raw=0.00003686 | best=0.00003623
23:18:55 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.115571 | val_mse_raw=0.00003607 | best=0.00003607

23:18:56 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.115918 | val_mse_raw=0.00003600 | best=0.00003600
23:18:56 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.114191 | val_mse_raw=0.00003587 | best=0.00003587

23:18:56 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.114219 | val_mse_raw=0.00003652 | best=0.00003587
23:18:56 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.113393 | val_mse_raw=0.00003643 | best=0.00003587

23:18:56 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.112722 | val_mse_raw=0.00003581 | best=0.00003581
23:18:56 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.112786 | val_mse_raw=0.00003597 | best=0.00003581

23:18:57 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.112209 | val_mse_raw=0.00003639 | best=0.00003581
23:18:57 | INFO    | train_LSTM_baseline | epoch  26 | train_log_mse=0.111732 | val_mse_raw=0.00003617 | best=0.00003581

23:18:57 | INFO    | train_LSTM_baseline | epoch  27 | train_log_mse=0.110951 | val_mse_raw=0.00003680 | best=0.00003581
23:18:57 | INFO    | train_LSTM_baseline | epoch  28 | train_log_mse=0.110896 | val_mse_raw=0.00003576 | best=0.00003576

23:18:57 | INFO    | train_LSTM_baseline | epoch  29 | train_log_mse=0.110448 | val_mse_raw=0.00003679 | best=0.00003576
23:18:57 | INFO    | train_LSTM_baseline | epoch  30 | train_log_mse=0.110558 | val_mse_raw=0.00003568 | best=0.00003568

23:18:58 | INFO    | train_LSTM_baseline | epoch  31 | train_log_mse=0.109102 | val_mse_raw=0.00003655 | best=0.00003568
23:18:58 | INFO    | train_LSTM_baseline | epoch  32 | train_log_mse=0.108384 | val_mse_raw=0.00003703 | best=0.00003568

23:18:58 | INFO    | train_LSTM_baseline | epoch  33 | train_log_mse=0.107141 | val_mse_raw=0.00003667 | best=0.00003568
23:18:58 | INFO    | train_LSTM_baseline | epoch  34 | train_log_mse=0.105455 | val_mse_raw=0.00003635 | best=0.00003568

23:18:58 | INFO    | train_LSTM_baseline | epoch  35 | train_log_mse=0.104079 | val_mse_raw=0.00003588 | best=0.00003568
23:18:58 | INFO    | train_LSTM_baseline | epoch  36 | train_log_mse=0.102022 | val_mse_raw=0.00003676 | best=0.00003568

23:18:59 | INFO    | train_LSTM_baseline | epoch  37 | train_log_mse=0.101420 | val_mse_raw=0.00003722 | best=0.00003568

23:18:59 | INFO    | train_LSTM_baseline | epoch  38 | train_log_mse=0.101752 | val_mse_raw=0.00003691 | best=0.00003568
23:18:59 | INFO    | train_LSTM_baseline | epoch  39 | train_log_mse=0.099645 | val_mse_raw=0.00003720 | best=0.00003568

23:18:59 | INFO    | train_LSTM_baseline | epoch  40 | train_log_mse=0.098816 | val_mse_raw=0.00003685 | best=0.00003568
23:18:59 | INFO    | train_LSTM_baseline | Early stopping at epoch 40
23:18:59 | INFO    | train_LSTM_regime | [calm] Final retrain — best val MSE (raw): 0.00003568
23:18:59 | INFO    | train_LSTM_regime | [calm] Test metrics: {'MSE': 1.4824860045337118e-05, 'RMSE': 0.003850306384265423, 'MAE': 0.0024981223978102207, 'n_test_windows': 1461}
23:18:59 | INFO    | train_LSTM_regime | [calm] Saved model → /content/repo/models/lstm_calm_B_seed44.pt
23:18:59 | INFO    | train_LSTM_regime | [calm] Saved scaler → /content/repo/models/lstm_calm_B_seed44_scaler.joblib
23:18:59 | INFO    | train_LSTM_regime | === Training regime LSTM: volatile (state=1) ===
23:18:59 | INFO    | train_LSTM_regime | Regime volatile: train=2034 rows (190 in regime), val=1089 rows (52 in regime)
23:18:59 | INFO    | train_LSTM_regime | [volatile] Skipping Optuna — using fixed hparams from JSON.
23:18:59 | INFO    | train_LSTM_regime | [volatile] Fixed params: {'hidden_size': 32, 'n_layers': 3, 'dropout': 0.49826330933920426, 'lr': 0.0019110922048796155, 'batch_size': 128, 'seq_len': 42}
23:18:59 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 163 / 1993 windows kept
23:18:59 | INFO    | train_LSTM_regime | RegimeWindowDataset(regime=volatile): 24 / 1048 windows kept
23:18:59 | INFO    | train_LSTM_regime | [volatile] Final retrain — using regime-filtered val loader (24 windows).
23:18:59 | INFO    | train_LSTM_baseline | epoch   1 | train_log_mse=14.565086 | val_mse_raw=0.90410012 | best=0.90410012
23:18:59 | INFO    | train_LSTM_baseline | epoch   2 | train_log_mse=13.906063 | val_mse_raw=0.72750872 | best=0.72750872

23:18:59 | INFO    | train_LSTM_baseline | epoch   3 | train_log_mse=13.158384 | val_mse_raw=0.54301506 | best=0.54301506
23:18:59 | INFO    | train_LSTM_baseline | epoch   4 | train_log_mse=12.210953 | val_mse_raw=0.35531679 | best=0.35531679
23:19:00 | INFO    | train_LSTM_baseline | epoch   5 | train_log_mse=10.951779 | val_mse_raw=0.18796499 | best=0.18796499
23:19:00 | INFO    | train_LSTM_baseline | epoch   6 | train_log_mse=9.147070 | val_mse_raw=0.07853138 | best=0.07853138
23:19:00 | INFO    | train_LSTM_baseline | epoch   7 | train_log_mse=6.807508 | val_mse_raw=0.03085289 | best=0.03085289

23:19:00 | INFO    | train_LSTM_baseline | epoch   8 | train_log_mse=4.816643 | val_mse_raw=0.01269928 | best=0.01269928
23:19:00 | INFO    | train_LSTM_baseline | epoch   9 | train_log_mse=3.179798 | val_mse_raw=0.00534049 | best=0.00534049
23:19:00 | INFO    | train_LSTM_baseline | epoch  10 | train_log_mse=2.048946 | val_mse_raw=0.00217133 | best=0.00217133
23:19:00 | INFO    | train_LSTM_baseline | epoch  11 | train_log_mse=1.198136 | val_mse_raw=0.00083364 | best=0.00083364
23:19:00 | INFO    | train_LSTM_baseline | epoch  12 | train_log_mse=0.614820 | val_mse_raw=0.00029672 | best=0.00029672

23:19:00 | INFO    | train_LSTM_baseline | epoch  13 | train_log_mse=0.301959 | val_mse_raw=0.00009397 | best=0.00009397
23:19:00 | INFO    | train_LSTM_baseline | epoch  14 | train_log_mse=0.138330 | val_mse_raw=0.00002779 | best=0.00002779
23:19:00 | INFO    | train_LSTM_baseline | epoch  15 | train_log_mse=0.132403 | val_mse_raw=0.00001383 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | epoch  16 | train_log_mse=0.170195 | val_mse_raw=0.00001604 | best=0.00001383

23:19:00 | INFO    | train_LSTM_baseline | epoch  17 | train_log_mse=0.242558 | val_mse_raw=0.00002050 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | epoch  18 | train_log_mse=0.267296 | val_mse_raw=0.00002276 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | epoch  19 | train_log_mse=0.294547 | val_mse_raw=0.00002213 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | epoch  20 | train_log_mse=0.293765 | val_mse_raw=0.00001940 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | epoch  21 | train_log_mse=0.267360 | val_mse_raw=0.00001612 | best=0.00001383

23:19:00 | INFO    | train_LSTM_baseline | epoch  22 | train_log_mse=0.231474 | val_mse_raw=0.00001384 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | epoch  23 | train_log_mse=0.187544 | val_mse_raw=0.00001402 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | epoch  24 | train_log_mse=0.162181 | val_mse_raw=0.00001766 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | epoch  25 | train_log_mse=0.138271 | val_mse_raw=0.00002498 | best=0.00001383
23:19:00 | INFO    | train_LSTM_baseline | Early stopping at epoch 25
23:19:00 | INFO    | train_LSTM_regime | [volatile] Final retrain — best val MSE (raw): 0.00001383

23:19:01 | INFO    | train_LSTM_regime | [volatile] Test metrics: {'MSE': 0.00025878060841932893, 'RMSE': 0.016086658462882042, 'MAE': 0.01371015328913927, 'n_test_windows': 1440}
23:19:01 | INFO    | train_LSTM_regime | [volatile] Saved model → /content/repo/models/lstm_volatile_B_seed44.pt
23:19:01 | INFO    | train_LSTM_regime | [volatile] Saved scaler → /content/repo/models/lstm_volatile_B_seed44_scaler.joblib

=== Regime-Specific LSTM Results ===
{
  "calm": {
    "regime": "calm",
    "best_params": {
      "hidden_size": 32,
      "n_layers": 1,
      "dropout": 0.31566834032054875,
      "lr": 0.000821087758542746,
      "batch_size": 32,
      "seq_len": 21
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 3.567537714843638e-05,
    "test_metrics": {
      "MSE": 1.4824860045337118e-05,
      "RMSE": 0.003850306384265423,
      "MAE": 0.0024981223978102207,
      "n_test_windows": 1461
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish",
      "vix",
      "vix_log_change",
      "vix3m_minus_vix"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 1844,
    "n_val_windows": 1037,
    "seed": 44,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_B.json"
  },
  "volatile": {
    "regime": "volatile",
    "best_params": {
      "hidden_size": 32,
      "n_layers": 3,
      "dropout": 0.49826330933920426,
      "lr": 0.0019110922048796155,
      "batch_size": 128,
      "seq_len": 42
    },
    "best_val_mse_raw": NaN,
    "retrained_val_mse": 1.3825313544657547e-05,
    "test_metrics": {
      "MSE": 0.00025878060841932893,
      "RMSE": 0.016086658462882042,
      "MAE": 0.01371015328913927,
      "n_test_windows": 1440
    },
    "features": [
      "log_return",
      "abs_return",
      "oc_return",
      "intraday_range",
      "relative_volume_21d",
      "bullish",
      "bearish",
      "vix",
      "vix_log_change",
      "vix3m_minus_vix"
    ],
    "target": "realized_vol_21d",
    "n_trials": 0,
    "n_train_windows": 190,
    "n_val_windows": 52,
    "seed": 44,
    "fixed_hparams": "/content/repo/models/hparams_lstm_regime_B.json"
  }
}

## Aggregate per-(variant × regime × seed) test metrics

In [5]:
import numpy as np

marker = "=== Regime-Specific LSTM Results ==="
per_seed_results = {}

for vname, vdata in variant_outputs.items():
    per_seed_results[vname] = {}
    for seed, info in vdata["seeds"].items():
        if info.get("status") != "ok": continue
        text = info["output"]
        idx = text.find(marker)
        if idx == -1: continue
        try:
            per_seed_results[vname][seed] = json.loads(text[idx + len(marker):].strip())
        except json.JSONDecodeError:
            continue

# Long form: one row per (variant, seed, regime)
rows = []
for vname, seeds_dict in per_seed_results.items():
    for seed, vresults in seeds_dict.items():
        for regime, r in vresults.items():
            rows.append({
                "variant":     vname, "seed": seed, "regime": regime,
                "test_MSE":    r["test_metrics"]["MSE"],
                "test_MAE":    r["test_metrics"]["MAE"],
                "seq_len":     r["best_params"]["seq_len"],
                "hidden_size": r["best_params"]["hidden_size"],
                "n_train_windows": r["n_train_windows"],
            })
per_seed_df = pd.DataFrame(rows)
print("Per-(variant, seed, regime) test metrics:")
display(per_seed_df)

# Aggregate: mean ± std across seeds per (variant, regime)
agg_rows = []
for vname, seeds_dict in per_seed_results.items():
    if not seeds_dict: continue
    for regime in ["calm", "volatile"]:
        mses = [vr[regime]["test_metrics"]["MSE"]
                for vr in seeds_dict.values() if regime in vr]
        maes = [vr[regime]["test_metrics"]["MAE"]
                for vr in seeds_dict.values() if regime in vr]
        if not mses: continue
        agg_rows.append({
            "variant":   vname, "regime": regime, "n_seeds": len(mses),
            "MSE_mean":  np.mean(mses),
            "MSE_std":   np.std(mses, ddof=1) if len(mses) > 1 else 0.0,
            "MAE_mean":  np.mean(maes),
            "MAE_std":   np.std(maes, ddof=1) if len(maes) > 1 else 0.0,
        })
agg_df = pd.DataFrame(agg_rows).set_index(["variant", "regime"])
print("\nMean ± std across seeds, per (variant, regime):")
agg_df

Per-(variant, seed, regime) test metrics:

,variant,seed,regime,test_MSE,test_MAE,seq_len,hidden_size,n_train_windows
0,O,42,calm,0.001062,0.004418,21,64,1196
1,O,42,volatile,0.000014,0.002394,42,128,2495
2,O,43,calm,0.003018,0.006522,21,64,1196
3,O,43,volatile,0.000015,0.002553,42,128,2495
4,O,44,calm,0.003475,0.006952,21,64,1196
5,O,44,volatile,0.000014,0.002537,42,128,2495
6,A,42,calm,0.000015,0.002532,21,64,3485
7,A,42,volatile,0.589846,0.231495,42,128,206
8,A,43,calm,0.000014,0.002516,21,64,3485
9,A,43,volatile,0.070221,0.055013,42,128,206
10,A,44,calm,0.000014,0.002426,21,64,3485
11,A,44,volatile,0.840236,0.319279,42,128,206
12,B,42,calm,0.000018,0.002757,21,32,1844
13,B,42,volatile,0.004002,0.029104,42,32,190
14,B,43,calm,0.000018,0.002519,21,32,1844
15,B,43,volatile,0.000100,0.009333,42,32,190
16,B,44,calm,0.000015,0.002498,21,32,1844
17,B,44,volatile,0.000259,0.013710,42,32,190

Mean ± std across seeds, per (variant, regime):

                  n_seeds  MSE_mean       MSE_std  MAE_mean   MAE_std
variant regime
O       calm            3  0.002518  1.281668e-03  0.005964  0.001356
        volatile        3  0.000014  8.560267e-07  0.002495  0.000087
A       calm            3  0.000014  8.801379e-07  0.002491  0.000057
        volatile        3  0.500101  3.927741e-01  0.201929  0.134591
B       calm            3  0.000017  1.738997e-06  0.002591  0.000144
        volatile        3  0.001453  2.208082e-03  0.017382  0.010384

## Summary (fill in after execution)

For the paper:
- **F2 (volatile-LSTM degeneracy):** look for volatile LSTMs across seeds/variants with `prediction_std` ≪ target std (~1e-4 vs ~4e-3). If F2 appears consistently, it's a structural claim. If one seed's volatile LSTM blows up differently than another's, that's consistent with the "F2 seed-dependent failure mode" documented in `discussion.md`.
- **Training window asymmetry:** variant B's regime LSTMs train on ~180 volatile-majority windows (per the F4 data-scarcity framing), vs O / A's ~160 (both are 4-5 % of the full train set). Variance across seeds may differ across variants if the smaller volatile-subset leads to more unstable Optuna.
- **DM significance testing** across variants: in nb 06 (within-variant) and nb 07 (cross-variant).

## Verify saved artifacts

In [6]:
import torch, joblib

for v in VARIANTS:
    base = v["output_suffix_base"]
    print(f"[Variant {v['name']}]  base suffix='{base}'")
    for seed in SEEDS:
        suffix = f"{base}_seed{seed}"
        for regime in ["calm", "volatile"]:
            pt_path     = MODELS_DIR / f"lstm_{regime}{suffix}.pt"
            scaler_path = MODELS_DIR / f"lstm_{regime}{suffix}_scaler.joblib"
            if not pt_path.exists() or not scaler_path.exists():
                print(f"  seed {seed}  [{regime}]  MISSING")
                continue
            ckpt = torch.load(pt_path, map_location="cpu", weights_only=False)
            print(f"  seed {seed}  [{regime}]  n_features={ckpt['n_features']}  hidden={ckpt['hyperparameters']['hidden_size']}")
    print()

print("Verification complete.")

[Variant O]  base suffix='_O'
  seed 42  [calm]  n_features=5  hidden=64
  seed 42  [volatile]  n_features=5  hidden=128
  seed 43  [calm]  n_features=5  hidden=64
  seed 43  [volatile]  n_features=5  hidden=128
  seed 44  [calm]  n_features=5  hidden=64
  seed 44  [volatile]  n_features=5  hidden=128

[Variant A]  base suffix=''
  seed 42  [calm]  n_features=7  hidden=64
  seed 42  [volatile]  n_features=7  hidden=128
  seed 43  [calm]  n_features=7  hidden=64
  seed 43  [volatile]  n_features=7  hidden=128
  seed 44  [calm]  n_features=7  hidden=64
  seed 44  [volatile]  n_features=7  hidden=128

[Variant B]  base suffix='_B'
  seed 42  [calm]  n_features=10  hidden=32
  seed 42  [volatile]  n_features=10  hidden=32
  seed 43  [calm]  n_features=10  hidden=32
  seed 43  [volatile]  n_features=10  hidden=32
  seed 44  [calm]  n_features=10  hidden=32
  seed 44  [volatile]  n_features=10  hidden=32

Verification complete.

## Saved artifacts

| Pattern | Count | Description |
|---|---|---|
| `lstm_{calm,volatile}_O_seed{42,43,44}.pt` | 6 | variant O regime LSTMs (3 seeds × 2 regimes) |
| `lstm_{calm,volatile}_seed{42,43,44}.pt` | 6 | variant A regime LSTMs |
| `lstm_{calm,volatile}_B_seed{42,43,44}.pt` | 6 | variant B regime LSTMs |
| `*_scaler.joblib` | 18 | Matching scaler for each `.pt` |
| `hparams_lstm_regime{,_O,_B}.json` | 3 | Seed 42's per-regime `best_params` per variant |

**Total: 18 LSTM checkpoints + 18 scalers + 3 hparams JSONs.**

Feed into nb 06 (ensemble invocations for each of 3 variants × 3 seeds = 9 ensemble runs) which produces `data/processed/seeds/test_predictions{_O,,_B}_seed{N}.parquet`.